import { Annale } from './db.js';

export const additionalAnnales2: Annale[] = [
  // 1. BTS GÉNIE CIVIL — SÉNÉGAL
  {
    id: 'annale-bts-genie-civil-sn',
    slug: 'concours-bts-genie-civil-senegal-fascicule-complet',
    title: 'BTS Génie Civil — Sénégal : Fascicule Complet',
    ministry: "Ministère de la Formation Professionnelle, de l'Apprentissage et de l'Artisanat",
    category: 'BTS Génie Civil',
    target_corps: 'Techniciens Supérieurs en Génie Civil, Conducteurs de Travaux BTP, Projeteurs',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition BTP d’Élite 2026',
    total_exercises: 320,
    total_pages: 34,
    rating: 4.98,
    reviews_count: 279,
    cover_gradient: 'from-amber-950 via-yellow-900 to-slate-950',
    cover_image: '/covers/bts_genie_civil.jpg',
    accent_color: '#d97706',
    badge: 'BTP & Génie Civil',
    description: "320 exercices distincts avec corrections détaillées : mathématiques appliquées au BTP, topographie et implantation, résistance des matériaux (RDM), béton et technologie des matériaux, calcul des structures en béton armé, fondations et géotechnique, routes, terrassements et VRD, dessin technique et DAO, économie de construction (métrés et devis), organisation de chantier et sécurité + 4 concours blancs complets.",
    official_reference: "Brevet de Technicien Supérieur (BTS) Génie Civil — Direction des Examens et Concours (DECO) du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Mathématiques appliquées au génie civil", count: 32, description: "Trigonométrie, calculs de surfaces, volumes de prismes/cylindres, pentes et pourcentages, conversion d'unités de chantier." },
      { title: "2. Topographie et implantation", count: 32, description: "Nivellement direct, lectures avant/arrière, calcul d'altitudes, fermeture de cheminement, azimut, station totale et GPS." },
      { title: "3. Résistance des matériaux et mécanique", count: 32, description: "Réactions d'appuis, moments fléchissants, efforts tranchants, contraintes normales/tangentielles, loi de Hooke et flambement." },
      { title: "4. Béton, matériaux et technologie", count: 32, description: "Granulats, ciment, rapport E/C, affaissement au cône d'Abrams, résistance à la compression, cure du béton et adjuvants." },
      { title: "5. Structures en béton armé", count: 32, description: "Prédimensionnement de poutres, poteaux et dalles, hauteur utile, armatures longitudinales et transversales, enrobage." },
      { title: "6. Fondations et géotechnique", count: 32, description: "Semelles isolées et filantes, portance du sol, contrainte admissible, tassements différentiels, essais au pénétromètre et drainage." },
      { title: "7. Routes, terrassements et VRD", count: 32, description: "Couches de chaussée (forme, base, roulement), profils en long/travers, cubatures de déblais/remblais, réseaux d'assainissement." },
      { title: "8. Dessin technique, plans et DAO", count: 32, description: "Lecture de plans de coffrage et ferraillage, cotations fonctionnelles, coupes verticales, cartouches et calques DAO." },
      { title: "9. Économie de construction, métrés et devis", count: 32, description: "Bordereaux quantitatifs, sous-détails de prix, calculs HT/TTC, rendements de maçonnerie, ratios d'acier et déboursés secs." },
      { title: "10. Organisation de chantier, sécurité et conduite de travaux", count: 32, description: "Installation de chantier (base vie), planning Gantt, chemin critique, circulation des engins, analyse des risques et PV de réception." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Structure et RDM", duration: "3h30", questions_count: 10 },
      { title: "Concours blanc 2 — Béton armé et fondations", duration: "3h30", questions_count: 10 },
      { title: "Concours blanc 3 — Topographie, routes et VRD", duration: "3h30", questions_count: 10 },
      { title: "Concours blanc 4 — Étude de chantier intégrée", duration: "4h00", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 1, section: "Mathématiques appliquées", question: "Calculer une longueur inconnue dans un triangle rectangle appliqué à un bâtiment R+2.", answer_preview: "Correction attendue : Utiliser le théorème de Pythagore c = √(a² + b²) avec contrôle des unités et cohérence technique." },
      { id: 34, section: "Topographie", question: "Calculer la dénivelée ΔH entre deux repères A et B avec lecture arrière LAR = 1,450 m et lecture avant LAV = 0,820 m.", answer_preview: "Correction : ΔH = LAR − LAV = 1,450 − 0,820 = +0,630 m. Le point B est plus haut de 63 cm." },
      { id: 66, section: "Résistance des matériaux", question: "Calculer le moment fléchissant maximal d'une poutre de portée L=5m sous charge ponctuelle centrale F=40 kN.", answer_preview: "Correction : Mmax = (F × L) / 4 = (40 × 5) / 4 = 50 kNm." }
    ],
    protected_exercises: [
      { id: 1, section: "Mathématiques appliquées", question: "Calculer une longueur inconnue dans un triangle rectangle appliqué à un bâtiment R+2.", answer: "Correction : Identifier l'hypoténuse ou les côtés de l'angle droit, appliquer le théorème de Pythagore a² + b² = c², convertir toutes les dimensions dans la même unité (mètres) et vérifier que la longueur obtenue est géométriquement cohérente." },
      { id: 3, section: "Pentes et cotes", question: "Calculer un pourcentage de pente à partir d’une différence d’altitude de 1,20 m sur une distance horizontale de 40 m.", answer: "Correction : Pente = (Dénivelée / Distance horizontale) × 100 = (1,20 / 40) × 100 = 3 %." },
      { id: 8, section: "Volumes de terrassement", question: "Déterminer le volume d’un prisme trapézoïdal appliqué à une plateforme routière de base 12 m, sommet 8 m, hauteur 2 m et longueur 50 m.", answer: "Correction : Section S = [(B + b) × h] / 2 = [(12 + 8) × 2] / 2 = 20 m². Volume V = S × L = 20 × 50 = 1 000 m³." },
      { id: 34, section: "Topographie", question: "Calculer une dénivelée entre deux points à partir des lectures de mire.", answer: "Correction : Dénivelée ΔH = Lecture Arrière (LAR) − Lecture Avant (LAV). Si le résultat est positif, le terrain monte ; s'il est négatif, le terrain descend." },
      { id: 37, section: "Cheminement altimétrique", question: "Calculer une fermeture altimétrique sur un cheminement et vérifier la tolérance.", answer: "Correction : Écart de fermeture = Altitude finale calculée − Altitude finale connue. Comparer à la tolérance T = ± 2,5 mm × √K (où K est la longueur en km)." },
      { id: 65, section: "RDM", question: "Déterminer les réactions d'appuis RA et RB pour une poutre simplement appuyée de portée L soumise à une charge répartie q.", answer: "Correction : Par symétrie ou somme des moments : RA = RB = (q × L) / 2. L'effort tranchant maximal aux appuis vaut qL/2 et s'annule à mi-portée." },
      { id: 66, section: "RDM", question: "Calculer le moment fléchissant maximal d’une poutre sous charge ponctuelle centrale F.", answer: "Correction : Mmax = (F × L) / 4. Le moment fléchissant est maximal au point d'application de la charge." },
      { id: 70, section: "Contraintes mécaniques", question: "Calculer la contrainte normale dans un tirant en acier de section 4 cm² soumis à un effort de traction de 80 kN.", answer: "Correction : σ = N / S = 80 000 N / (4 × 10^-4 m²) = 200 × 10^6 Pa = 200 MPa. Comparer à la limite élastique fe." },
      { id: 101, section: "Technologie du béton", question: "Déterminer la quantité d’eau pour un béton dosé à 350 kg/m³ de ciment avec un rapport E/C = 0,50.", answer: "Correction : E = 350 × 0,50 = 175 litres d'eau par m³ de béton." },
      { id: 106, section: "Contrôles du béton", question: "Expliquer l'essai d'affaissement au cône d'Abrams (Slump Test) et ses classes de consistance.", answer: "Correction : Mesure de l'affaissement du béton frais démoulé du cône normalisé. Classes : S1 (ferme 10-40 mm), S2 (plastique 50-90 mm), S3 (très plastique 100-150 mm), S4 (fluide 160-210 mm)." },
      { id: 134, section: "Béton armé", question: "Prédimensionner la hauteur h d'une poutre continue en béton armé de portée L = 6,00 m.", answer: "Correction : Règle empirique de prédimensionnement : h comprise entre L/15 et L/10, soit 600/15 = 40 cm à 600/10 = 60 cm. On choisit couramment h = 50 cm avec une largeur b = 20 à 25 cm." },
      { id: 168, section: "Fondations", question: "Vérifier la contrainte transmise au sol par une semelle carrée de 1,50 m de côté recevant une charge de 450 kN. La contrainte admissible du sol est de 0,25 MPa.", answer: "Correction : Surface S = 1,50 × 1,50 = 2,25 m². Contrainte appliquée σ = N / S = 450 kN / 2,25 m² = 200 kPa = 0,20 MPa. Comme 0,20 MPa ≤ 0,25 MPa, la condition de portance est vérifiée." },
      { id: 193, section: "Voirie et Routes", question: "Définir les différentes couches composant la structure d’une chaussée.", answer: "Correction : 1. Sol support ; 2. Couche de forme ; 3. Couche de fondation ; 4. Couche de base (grave non traitée ou grave bitume) ; 5. Couche de roulement (enrobé bitumineux ou béton)." },
      { id: 257, section: "Métrés et devis", question: "Définir le rôle d’un métré et expliciter ses composantes (avant-métré, quantitatif, estimatif).", answer: "Correction : Le métré quantifie précisément les ouvrages élémentaires par nature de travaux. L'avant-métré détaille les calculs géométriques, le devis quantitatif récapitule les unités et volumes, et l'estimatif applique les prix unitaires pour déterminer le montant global." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 116,
    created_at: new Date().toISOString(),
  },

  // 2. BTS COMPTABILITÉ ET GESTION — SÉNÉGAL
  {
    id: 'annale-bts-comptabilite-sn',
    slug: 'concours-bts-comptabilite-gestion-senegal-tome-complet',
    title: 'BTS Comptabilité et Gestion — Sénégal : Tome Complet',
    ministry: "Ministère de la Formation Professionnelle, de l'Apprentissage et de l'Artisanat",
    category: 'BTS Comptabilité',
    target_corps: 'Comptables d’Entreprise, Gestionnaires Financiers, Collaborateurs de Cabinet Comptable',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition SYSCOHADA Révisé 2026',
    total_exercises: 320,
    total_pages: 33,
    rating: 4.97,
    reviews_count: 324,
    cover_gradient: 'from-emerald-950 via-teal-900 to-slate-950',
    cover_image: '/covers/bts_comptabilite.jpg',
    accent_color: '#10b981',
    badge: 'Comptabilité & Gestion',
    description: "320 exercices originaux corrigés couvrant le référentiel national SYSCOHADA : comptabilité générale et opérations courantes, TVA et déclarations fiscales, paie et charges sociales IPRES/CSS, immobilisations et amortissements, gestion des stocks et inventaires, travaux de clôture, analyse financière (SIG, bilans fonctionnels, FRNG, BFR), contrôle de gestion (seuils de rentabilité, coûts complets, budgets), trésorerie et modélisation Excel + 4 concours blancs.",
    official_reference: "Brevet de Technicien Supérieur (BTS) Comptabilité et Gestion — République du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Comptabilité générale et opérations courantes", count: 32, description: "Achats/ventes, réductions commerciales et financières, frais accessoires, emballages consignés, effets de commerce, rapprochements bancaires." },
      { title: "2. TVA, fiscalité et déclarations", count: 32, description: "TVA facturée/déductible, prorata de déduction, crédit de TVA, acomptes d'IS, retenues à la source (BRS, VRS) et déclarations mensuelles." },
      { title: "3. Paie, personnel et charges sociales", count: 32, description: "Calcul du salaire brut, heures supplémentaires, retenues salariales IPRES/CSS, charges patronales, bulletin de paie et écritures de salaires." },
      { title: "4. Immobilisations, amortissements et provisions", count: 32, description: "Coût d'acquisition, amortissement linéaire/dégressif, cessions d'actifs, plus/moins-values, dépréciations d'actifs et provisions pour risques." },
      { title: "5. Stocks, inventaire et variations", count: 32, description: "Méthodes CUMP et FIFO, fiches de stocks, variations de stocks, démarque inconnue, provisions sur stocks et inventaire physique." },
      { title: "6. Travaux d'inventaire et clôture", count: 32, description: "Charges à payer, produits à recevoir, charges/produits constatés d'avance, régularisations d'intérêts et balance après inventaire." },
      { title: "7. Analyse financière et états financiers", count: 32, description: "Bilan fonctionnel, FRNG, BFR d'exploitation, trésorerie nette, SIG (marge commerciale, valeur ajoutée, EBE), ratios de rentabilité et liquidité." },
      { title: "8. Contrôle de gestion, coûts et marges", count: 32, description: "Coûts variables et fixes, marge sur coût variable, seuil de rentabilité en valeur et quantité, point mort, imputation rationnelle et centres d'analyse." },
      { title: "9. Gestion, financement et trésorerie", count: 32, description: "Budgets des ventes, achats et trésorerie, plan de financement, escompte d'effets, capacité d'autofinancement (CAF) et tableaux de flux." },
      { title: "10. Informatique de gestion, Excel et systèmes comptables", count: 32, description: "Formules conditionnelles SI/RECHERCHEV, tableaux croisés dynamiques, macro-commandes, progiciels ERP et sécurisation des bases comptables." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Comptabilité générale et fiscalité", duration: "3h30", questions_count: 4 },
      { title: "Concours blanc 2 — Paie, stocks et inventaire", duration: "3h30", questions_count: 4 },
      { title: "Concours blanc 3 — Analyse financière et contrôle de gestion", duration: "3h30", questions_count: 4 },
      { title: "Concours blanc 4 — Épreuve intégrée BTS Comptabilité-Gestion", duration: "4h00", questions_count: 4 }
    ],
    sample_exercises: [
      { id: 9, section: "Comptabilité générale", question: "Établir les écritures d’une facture comportant remise 5 %, rabais 2 % et escompte 1 %.", answer_preview: "Correction attendue : Déduire d'abord les réductions commerciales en cascade pour obtenir le Net Commercial, calculer l'escompte sur le net commercial pour obtenir le Net Financier, puis calculer la TVA à 18 % sur le net financier." },
      { id: 37, section: "TVA et fiscalité", question: "Déterminer la TVA à décaisser : TVA collectée = 4 500 000 FCFA, TVA déductible sur biens et services = 2 800 000 FCFA, crédit de TVA antérieur = 500 000 FCFA.", answer_preview: "Correction : TVA nette = 4 500 000 − 2 800 000 − 500 000 = 1 200 000 FCFA à reverser au Trésor public." },
      { id: 233, section: "Contrôle de gestion", question: "Calculer le seuil de rentabilité : Chiffre d'affaires = 80 000 000 FCFA, Charges variables = 48 000 000 FCFA, Charges fixes = 20 000 000 FCFA.", answer_preview: "Correction : Taux de M/CV = (80M − 48M) / 80M = 40 %. Seuil de rentabilité SR = 20 000 000 / 0,40 = 50 000 000 FCFA." }
    ],
    protected_exercises: [
      { id: 1, section: "Comptabilité générale", question: "Enregistrer l’apport initial d’un associé : 15 000 000 FCFA déposés en banque et matériel évalué à 10 000 000 FCFA.", answer: "Correction : Débit du compte 521 Banque (15 000 000) et Débit du compte 241 Matériel (10 000 000) par le Crédit du compte 101 Capital social (25 000 000 FCFA)." },
      { id: 6, section: "Comptabilité générale", question: "Comptabiliser un escompte de règlement de 2 % accordé par un fournisseur sur une dette de 3 000 000 FCFA réglée par virement.", answer: "Correction : Montant escompte = 60 000 FCFA. Règlement net = 2 940 000 FCFA. Écriture : Débit 401 Fournisseurs (3 000 000) / Crédit 773 Escomptes obtenus (60 000) et Crédit 521 Banque (2 940 000 FCFA)." },
      { id: 35, section: "Fiscalité", question: "Calculer le montant TTC d'une facture ayant un montant HT de 1 250 000 FCFA au taux légal de TVA de 18 % au Sénégal.", answer: "Correction : TVA = 1 250 000 × 0,18 = 225 000 FCFA. Montant TTC = 1 250 000 + 225 000 = 1 475 000 FCFA." },
      { id: 65, section: "Paie et social", question: "Calculer le salaire brut d’un employé : salaire de base 250 000 FCFA, prime de transport légale 20 800 FCFA, prime d’ancienneté (5%) 12 500 FCFA, heures supplémentaires 35 000 FCFA.", answer: "Correction : Salaire brut = 250 000 + 20 800 + 12 500 + 35 000 = 318 300 FCFA." },
      { id: 98, section: "Immobilisations", question: "Calculer l’annuité d’amortissement linéaire d’un matériel industriel acquis le 01/01/N pour 12 000 000 FCFA HT avec une durée d'utilité de 5 ans.", answer: "Correction : Taux linéaire t = 100 / 5 = 20 %. Annuité = 12 000 000 × 0,20 = 2 400 000 FCFA par an." },
      { id: 131, section: "Gestion des stocks", question: "Calculer le CUMP après une nouvelle entrée : Stock initial 100 unités à 2 000 FCFA, Entrée 200 unités à 2 600 FCFA.", answer: "Correction : Valeur totale = (100 × 2 000) + (200 × 2 600) = 200 000 + 520 000 = 720 000 FCFA. Quantité totale = 300 unités. CUMP = 720 000 / 300 = 2 400 FCFA." },
      { id: 162, section: "Régularisations", question: "Une prime d’assurance annuelle de 1 200 000 FCFA a été payée et comptabilisée le 01/10/N pour la période du 01/10/N au 30/09/N+1. Calculer la charge constatée d’avance au 31/12/N.", answer: "Correction : La prime couvre 12 mois dont 9 mois concernent l'exercice N+1 (du 01/01 au 30/09/N+1). Charge constatée d'avance (CCA) = 1 200 000 × (9 / 12) = 900 000 FCFA. Écriture : Débit 476 CCA / Crédit 625 Primes d'assurance pour 900 000 FCFA." },
      { id: 197, section: "Analyse financière", question: "Calculer le Fonds de Roulement Net Global (FRNG) à partir des Capitaux permanents = 65 000 000 FCFA et de l'Actif immobilisé = 45 000 000 FCFA.", answer: "Correction : FRNG = Capitaux permanents (Ressources stables) − Actif immobilisé (Emplois stables) = 65 000 000 − 45 000 000 = +20 000 000 FCFA. L'excédent de ressources stables finance l'exploitation." },
      { id: 198, section: "Analyse financière", question: "Calculer la Trésorerie Nette sachant que FRNG = +20 000 000 FCFA et BFR = +14 000 000 FCFA.", answer: "Correction : Trésorerie Nette = FRNG − BFR = 20 000 000 − 14 000 000 = +6 000 000 FCFA (trésorerie active positive en banque)." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 117,
    created_at: new Date().toISOString(),
  },

  // 3. BT SECRÉTARIAT-BUREAUTIQUE — SÉNÉGAL
  {
    id: 'annale-bt-secretariat-sn',
    slug: 'concours-bt-secretariat-bureautique-senegal-tome-complet',
    title: 'BT Secrétariat-Bureautique — Sénégal : Tome Complet',
    ministry: "Ministère de la Formation Professionnelle, de l'Apprentissage et de l'Artisanat",
    category: 'BT Secrétariat',
    target_corps: 'Secrétaires Bureautiques, Agents d’Accueil et de Liaison, Assistants de Service',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Brevet de Technicien 2026',
    total_exercises: 320,
    total_pages: 33,
    rating: 4.96,
    reviews_count: 185,
    cover_gradient: 'from-pink-950 via-rose-900 to-slate-950',
    cover_image: '/covers/bt_secretariat.jpg',
    accent_color: '#ec4899',
    badge: 'Secrétariat & Bureau',
    description: "320 exercices pratiques d'entraînement intensif pour l'examen du Brevet de Technicien (BT) : organisation du travail administratif et gestion des priorités, accueil physique et filtrage téléphonique, rédaction de correspondance officielle, traitement de texte Word, tableur Excel, communication électronique et sécurité numérique, facturation commerciale, gestion RH du personnel, anglais professionnel bilingue et droit du travail + 4 concours blancs.",
    official_reference: "Brevet de Technicien (BT) Secrétariat-Bureautique — Direction des Examens et Concours du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Techniques de secrétariat et organisation du travail", count: 32, description: "Planning quotidien, tenue de l'agenda, préparation des réunions, gestion du courrier entrant/sortant, archivage et méthode des priorités." },
      { title: "2. Communication professionnelle et accueil", count: 32, description: "Accueil physique, standard téléphonique, prise de messages précis, traitement des usagers mécontents, écoute active et confidentialité." },
      { title: "3. Français professionnel, correspondance et rédaction", count: 32, description: "Lettres commerciales, notes de service, comptes rendus, procès-verbaux, syntaxe administrative et correction orthographique." },
      { title: "4. Traitement de texte et bureautique numérique", count: 32, description: "Mise en page normalisée, styles, tableaux, publipostage, étiquettes, pagination et exportation au format PDF." },
      { title: "5. Tableur, calculs et gestion de données", count: 32, description: "Tableaux de bord des activités, calculs de moyennes/totaux, formules conditionnelles SI, listes déroulantes et graphiques statistiques." },
      { title: "6. Communication électronique, internet et sécurité numérique", count: 32, description: "Rédaction de courriels, gestion des pièces jointes, arborescence partagée, détection de phishing, mots de passe et sauvegardes." },
      { title: "7. Comptabilité, facturation et gestion administrative", count: 32, description: "Contrôle des factures fournisseurs/clients, calculs HT/TVA/TTC, remises commerciales, relances d'impayés et transmission comptable." },
      { title: "8. Ressources humaines et administration du personnel", count: 32, description: "Dossiers des salariés, fiches de congés, suivi des absences, attestations de travail, organisation des entretiens et turnover." },
      { title: "9. Anglais professionnel et correspondance bilingue", count: 32, description: "Accueil en anglais, courriels bilingues, vocabulaire commercial (invoice, delivery, meeting), messages téléphoniques en anglais." },
      { title: "10. Droit, administration, logique et épreuves pratiques", count: 32, description: "Contrats de travail, secret professionnel, règles de déontologie, gestion des incidents administratifs et mise en situation réelle." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Secrétariat et communication", duration: "3h00", questions_count: 4 },
      { title: "Concours blanc 2 — Bureautique et gestion de données", duration: "3h00", questions_count: 4 },
      { title: "Concours blanc 3 — Administration et personnel", duration: "3h00", questions_count: 4 },
      { title: "Concours blanc 4 — Épreuve intégrée BT Secrétariat", duration: "4h00", questions_count: 4 }
    ],
    sample_exercises: [
      { id: 1, section: "Techniques de secrétariat", question: "Classer chronologiquement les tâches d’une journée de secrétariat selon leur urgence et importance.", answer_preview: "Correction attendue : Dépouillement du courrier urgent et des messages prioritaires, validation de l'agenda avec la direction, accueil des rendez-vous et traitement du travail de fond." },
      { id: 35, section: "Communication professionnelle", question: "Prendre un message téléphonique complet en précisant les 6 mentions obligatoires.", answer_preview: "Correction attendue : Date et heure de l'appel, identité complète de l'interlocuteur, organisme/entreprise, numéro de rappel, objet clair du message et nom de l'agent récepteur." },
      { id: 194, section: "Facturation", question: "Calculer le montant TTC d'une facture ayant un montant HT de 450 000 FCFA avec une TVA à 18 %.", answer_preview: "Correction : TVA = 450 000 × 0,18 = 81 000 FCFA. Montant TTC = 531 000 FCFA." }
    ],
    protected_exercises: [
      { id: 1, section: "Techniques de secrétariat", question: "Classer chronologiquement les tâches d’une journée de secrétariat selon leur urgence.", answer: "Correction : 1. Ouverture du secrétariat et consultation des courriels/urgences ; 2. Mise à jour de l'agenda de direction ; 3. Traitement des parapheurs et courriers prioritaires ; 4. Accueil des visiteurs programmés ; 5. Classement et préparation des dossiers du lendemain." },
      { id: 12, section: "Gestion du temps", question: "Prioriser dix tâches administratives selon les critères d'urgence et d'importance.", answer: "Correction : Appliquer la matrice d'Eisenhower : Priorité 1 (Urgent et Important : réunion immédiate, note au ministre) ; Priorité 2 (Non urgent mais important : classement, commande de fournitures) ; Priorité 3 (Urgent non important : certains appels téléphoniques) ; Priorité 4 (Non urgent non important : tri de vieux prospectus)." },
      { id: 38, section: "Accueil professionnel", question: "Comment gérer un visiteur mécontent à l'accueil d'un service ?", answer: "Correction : Conserver son calme, adopter une posture d'écoute active sans l'interrompre, reformuler ses doléances pour valider la compréhension, lui proposer une solution concrète ou l'orienter poliment vers le responsable compétent." },
      { id: 69, section: "Correspondance commerciale", question: "Rédiger une lettre de relance de premier niveau pour une facture impayée.", answer: "Correction : Rappel courtois des références de la facture (numéro, date, montant), constatation du dépassement de l'échéance convenue, transmission d'un duplicata de la facture et invitation à régulariser sous 8 jours." },
      { id: 113, section: "Bureautique Word", question: "Présenter les étapes de réalisation d'un publipostage de convocations officielles.", answer: "Correction : 1. Création de la lettre-type sous Word avec espacement des zones de fusion ; 2. Préparation du tableau de données sous Excel (Nom, Prénom, Adresse, Date) ; 3. Fusion et insertion des champs ; 4. Vérification individuelle des aperçus avant édition finale." },
      { id: 130, section: "Tableur Excel", question: "Écrire la formule permettant de calculer le total et la moyenne de la plage de cellules C5 à C25.", answer: "Correction : Total : =SOMME(C5:C25) ; Moyenne : =MOYENNE(C5:C25)." },
      { id: 166, section: "Sécurité numérique", question: "Différencier l'usage du champ CC (copie conforme) et du champ Cci (copie cachée) dans un courriel.", answer: "Correction : Le champ CC informe les destinataires secondaires de façon visible par tous. Le champ Cci masque les adresses électroniques pour préserver la vie privée et respecter la législation sur la protection des données personnelles." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 118,
    created_at: new Date().toISOString(),
  },

  // 4. PROBATOIRE — SÉNÉGAL
  {
    id: 'annale-probatoire-sn',
    slug: 'concours-probatoire-senegal-fascicule-complet',
    title: 'Probatoire — Sénégal : Fascicule Complet de Préparation',
    ministry: "Ministère de l'Éducation Nationale — Enseignement Moyen & Secondaire",
    category: 'Probatoire',
    target_corps: 'Candidats au Probatoire, Lycéens et Préparation aux Concours d’Entrée',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Académique Renforcée 2026',
    total_exercises: 320,
    total_pages: 12,
    rating: 4.95,
    reviews_count: 290,
    cover_gradient: 'from-blue-950 via-indigo-900 to-slate-950',
    cover_image: '/covers/probatoire.jpg',
    accent_color: '#2563eb',
    badge: 'Probatoire & Lycée',
    description: "320 exercices originaux progressifs couvrant les 10 matières fondamentales du programme du Probatoire sénégalais : langue et grammaire française, calcul et algèbre, géométrie et statistiques, physique (mécanique et électricité), chimie et environnement, sciences de la vie et de la Terre (SVT), histoire et géographie du Sénégal, anglais, raisonnement logique et méthodologie d'examen + 4 concours blancs intégraux.",
    official_reference: "Programme officiel de l'Enseignement Secondaire et du Probatoire — République du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Français — langue, grammaire et expression", count: 32, description: "Accords des adjectifs et participes, concordance des temps, discours direct/indirect, figures de style, connecteurs et résumés de textes." },
      { title: "2. Mathématiques — calcul et algèbre", count: 32, description: "Calcul fractionnaire, factorisation, équations et inéquations du premier degré, pourcentages, vitesses moyennes et suites arithmétiques." },
      { title: "3. Géométrie, fonctions et statistiques", count: 32, description: "Pythagore, aires et volumes de solides, fonctions affines, représentations graphiques, probabilités simples et diagrammes statistiques." },
      { title: "4. Physique — mécanique, électricité et énergie", count: 32, description: "Poids et masse (P=mg), travail et puissance, énergie cinétique, loi d'Ohm (U=RI), puissance électrique consommée et circuits." },
      { title: "5. Chimie — matière, réactions et environnement", count: 32, description: "États de la matière, formules chimiques, équilibrage d'équations, pH des solutions aqueuses, combustion et effet de serre." },
      { title: "6. Sciences de la vie et de la Terre (SVT)", count: 32, description: "Appareils digestif et respiratoire, circulation sanguine, cellule végétale/animale, photosynthèse, écosystèmes et chaînes trophiques." },
      { title: "7. Histoire, géographie et Sénégal", count: 32, description: "Climat sahélien, façade atlantique, fleuve Sénégal, pêche, agriculture, décolonisation, histoire des Quatre Communes et institutions." },
      { title: "8. Anglais — compréhension et communication", count: 32, description: "Conjugaison au présent simple et continu, verbes irréguliers, modaux (can, must, should), prépositions de lieu et traductions courtes." },
      { title: "9. Logique, informatique et raisonnement", count: 32, description: "Suites logiques, analogies, syllogismes, fonctions de base des tableurs et traitements de texte, cybersécurité élémentaire." },
      { title: "10. Méthodologie, citoyenneté et préparation à l’examen", count: 32, description: "Technique de la dissertation, gestion du temps d'épreuve, règles de relecture, valeurs civiques républicaines et lutte contre la corruption." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Français, mathématiques et logique", duration: "3h00", questions_count: 6 },
      { title: "Concours blanc 2 — Sciences et culture générale", duration: "3h00", questions_count: 6 },
      { title: "Concours blanc 3 — Anglais, informatique et raisonnement", duration: "2h30", questions_count: 6 },
      { title: "Concours blanc 4 — Épreuve intégrée probatoire", duration: "4h00", questions_count: 6 }
    ],
    sample_exercises: [
      { id: 4, section: "Français", question: "Corriger un texte comportant des erreurs d'accord entre sujet et verbe.", answer_preview: "Correction attendue : « La plupart des candidats réussissent l'épreuve lorsque le travail et la persévérance guident leur révision. »" },
      { id: 42, section: "Mathématiques", question: "Calculer une augmentation de 15 % sur un montant initial de 48 000 FCFA.", answer_preview: "Correction : Augmentation = 48 000 × 0,15 = 7 200 FCFA. Nouveau montant = 55 200 FCFA." },
      { id: 110, section: "Physique", question: "Appliquer la relation d'Ohm U = R × I pour calculer la tension aux bornes d'une résistance de 45 Ω traversée par 0,6 A.", answer_preview: "Correction : U = 45 × 0,6 = 27 Volts." }
    ],
    protected_exercises: [
      { id: 1, section: "Français", question: "Accorder correctement les adjectifs qualificatifs : « Des décision (rapide) et des mesure (efficace) ont été prise. »", answer: "Correction : « Des décisions rapides et des mesures efficaces ont été prises. » Les adjectifs et le participe passé s'accordent en genre et en nombre avec leurs noms féminins pluriels." },
      { id: 8, section: "Français", question: "Mettre au discours indirect : Le professeur affirme : « Vous terminerez votre devoir avant midi. »", answer: "Correction : Le professeur affirme que nous terminerons notre devoir avant midi." },
      { id: 37, section: "Mathématiques", question: "Résoudre l’équation du premier degré : 5x − 18 = 2x + 12.", answer: "Correction : 5x − 2x = 12 + 18 => 3x = 30 => x = 10. La solution est S = {10}." },
      { id: 43, section: "Mathématiques", question: "Un article subit une réduction de 10 % puis une seconde réduction de 20 %. Quel est le pourcentage total de réduction ?", answer: "Correction : Coefficient multiplicateur global = (1 − 0,10) × (1 − 0,20) = 0,90 × 0,80 = 0,72. Réduction totale = (1 − 0,72) × 100 = 28 % (et non 30 %)." },
      { id: 72, section: "Géométrie", question: "Dans un triangle rectangle ABC en A, AB = 6 cm et AC = 8 cm. Calculer la longueur BC de l'hypoténuse.", answer: "Correction : D'après le théorème de Pythagore : BC² = AB² + AC² = 6² + 8² = 36 + 64 = 100. BC = √100 = 10 cm." },
      { id: 102, section: "Physique", question: "Calculer le poids P d’un corps de masse m = 75 kg sur Terre où l'intensité de la pesanteur g = 9,8 N/kg.", answer: "Correction : P = m × g = 75 × 9,8 = 735 Newtons." },
      { id: 138, section: "Chimie", question: "Équilibrer l’équation chimique de combustion du méthane : CH4 + O2 → CO2 + H2O.", answer: "Correction : Équation équilibrée : CH4 + 2 O2 → CO2 + 2 H2O." },
      { id: 167, section: "SVT", question: "Décrire le rôle et le fonctionnement du cœur dans la circulation sanguine.", answer: "Correction : Muscle creux assurant la fonction de pompe : le cœur droit envoie le sang désoxygéné vers les poumons pour être réoxygéné (petite circulation), et le cœur gauche propulse le sang oxygéné dans tout l'organisme via l'aorte (grande circulation)." },
      { id: 196, section: "Histoire-Géographie", question: "Décrire les caractéristiques principales du climat sahélien qui touche la partie nord du Sénégal.", answer: "Correction : Climat semi-aride caractérisé par une longue saison sèche (8 à 9 mois), une saison des pluies courte (hivernage de juillet à septembre), des précipitations faibles et irrégulières (300 à 500 mm/an) et de fortes chaleurs." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 119,
    created_at: new Date().toISOString(),
  },

  // 5. CONCOURS IFACE — SÉNÉGAL (UCAD)
  {
    id: 'annale-iface-sn',
    slug: 'concours-iface-senegal-ucad-tome-complet',
    title: 'Concours IFACE — Sénégal : Tome Complet',
    ministry: "Ministère de l'Enseignement Supérieur, de la Recherche et de l'Innovation — UCAD",
    category: 'IFACE Dakar',
    target_corps: 'Étudiants en Administration des Affaires, Créateurs d’Entreprise, Gestionnaires IFACE',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale Entrée IFACE 2026',
    total_exercises: 320,
    total_pages: 23,
    rating: 4.98,
    reviews_count: 245,
    cover_gradient: 'from-slate-950 via-sky-950 to-indigo-950',
    cover_image: '/covers/iface.jpg',
    accent_color: '#0284c7',
    badge: 'Management & Entreprise',
    description: "320 exercices professionnels corrigés couvrant tout le concours d'admission à l'IFACE (Institut de Formation en Administration et Création d'Entreprise — UCAD) : comptabilité financière et écritures, gestion des sociétés commerciales, contrôle de gestion, diagnostic financier, fiscalité, mathématiques financières et probabilités, macroéconomie, droit des affaires OHADA, management RH, audit et entrepreneuriat + 4 concours blancs.",
    official_reference: "Concours d'accès à l'IFACE (Université Cheikh Anta Diop de Dakar) — Faculté des Sciences Économiques et de Gestion.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Comptabilité générale et écritures", count: 32, description: "Apports en capital, achats/ventes avec TVA, créances douteuses, états de rapprochement bancaire et régularisations." },
      { title: "2. Comptabilité des sociétés et opérations financières", count: 32, description: "Constitution de sociétés (SARL, SA), affectation du résultat, distribution des dividendes, emprunts bancaires et capitaux propres." },
      { title: "3. Comptabilité analytique, coûts et contrôle de gestion", count: 32, description: "Coûts complets, unités d'œuvre, marges sur coûts variables, seuils de rentabilité, budgets de ventes et de trésorerie." },
      { title: "4. Analyse financière et états financiers", count: 32, description: "Bilan fonctionnel, FRNG, BFR, trésorerie nette, SIG, soldes de gestion, rentabilité financière (ROE) et ratios de liquidité." },
      { title: "5. Fiscalité et TVA", count: 32, description: "TVA collectée et déductible, prorata de déduction, calculs de l'IS, acomptes provisionnels, retenues à la source et contrôle fiscal." },
      { title: "6. Mathématiques financières, statistiques et probabilités", count: 32, description: "Intérêts simples et composés, valeurs actuelles nettes, annuités constantes, moyennes pondérées, variances et arbres de probabilité." },
      { title: "7. Économie générale et développement", count: 32, description: "Circuit économique, inflation, chômage, déterminants de l'investissement, politiques budgétaire et monétaire, solde commercial." },
      { title: "8. Droit des affaires et droit social", count: 32, description: "Contrats commerciaux, Acte Uniforme OHADA, responsabilité des dirigeants, contrats de travail (CDD/CDI) et licenciement." },
      { title: "9. Gestion, management et ressources humaines", count: 32, description: "Objectifs SMART, organigrammes, motivation des équipes, fiches de poste, plans de formation, absentéisme et turnover." },
      { title: "10. Français, culture générale, informatique et entrepreneuriat", count: 32, description: "Audit interne, contrôle interne, cartographie des risques, business model canvas, seuil de rentabilité de start-up et soutenance orale." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Comptabilité, fiscalité et mathématiques", duration: "3h30", questions_count: 4 },
      { title: "Concours blanc 2 — Économie, droit et management", duration: "3h30", questions_count: 4 },
      { title: "Concours blanc 3 — Contrôle de gestion, finance et audit", duration: "3h30", questions_count: 4 },
      { title: "Concours blanc 4 — Épreuve intégrée IFACE", duration: "4h00", questions_count: 4 }
    ],
    sample_exercises: [
      { id: 1, section: "Comptabilité générale", question: "Enregistrer l’apport en capital d’une entreprise de 10 000 000 FCFA effectué par virement bancaire.", answer_preview: "Correction : Débit du compte 521 Banque par le Crédit du compte 101 Capital social pour 10 000 000 FCFA." },
      { id: 73, section: "Contrôle de gestion", question: "Calculer le seuil de rentabilité à partir des charges fixes (15 000 000 FCFA) et d'un taux de marge sur coût variable de 30 %.", answer_preview: "Correction : SR = 15 000 000 / 0,30 = 50 000 000 FCFA." },
      { id: 169, section: "Mathématiques financières", question: "Calculer l’intérêt simple produit par un capital de 5 000 000 FCFA placé à 6 % l'an pendant 8 mois.", answer_preview: "Correction : I = (C × t × n) / 1 200 = (5 000 000 × 6 × 8) / 1 200 = 200 000 FCFA." }
    ],
    protected_exercises: [
      { id: 1, section: "Comptabilité générale", question: "Enregistrer l’apport en capital d’une entreprise effectué par virement bancaire pour 10 000 000 FCFA.", answer: "Correction : Débit 521 Banque (10 000 000) / Crédit 101 Capital social (10 000 000 FCFA). L'actif circulant augmente et les capitaux propres sont constatés." },
      { id: 42, section: "Comptabilité des sociétés", question: "Calculer le dividende par action d'une société ayant dégagé un bénéfice distribuable de 18 000 000 FCFA divisé en 6 000 actions ordinaires.", answer: "Correction : Dividende unitaire = 18 000 000 / 6 000 = 3 000 FCFA par action." },
      { id: 73, section: "Contrôle de gestion", question: "Calculer le seuil de rentabilité à partir des charges fixes et du taux de marge sur coût variable.", answer: "Correction : SR = Charges Fixes / Taux de M/CV. Il représente le chiffre d'affaires minimum pour lequel l'entreprise ne réalise ni bénéfice ni perte." },
      { id: 101, section: "Analyse financière", question: "Calculer le fonds de roulement net global (FRNG) et expliquer sa signification économique.", answer: "Correction : FRNG = Ressources durables (Capitaux propres + Dettes à long terme) − Emplois stables (Actif immobilisé net). Un FRNG positif garantit une marge de sécurité financière pour financer le cycle d'exploitation." },
      { id: 133, section: "Fiscalité", question: "Calculer la TVA due au titre du mois : Ventes HT taxables à 18 % = 30 000 000 FCFA, Achats HT ouvrant droit à déduction = 18 000 000 FCFA.", answer: "Correction : TVA collectée = 30 000 000 × 0,18 = 5 400 000 FCFA. TVA déductible = 18 000 000 × 0,18 = 3 240 000 FCFA. TVA à reverser = 5 400 000 − 3 240 000 = 2 160 000 FCFA." },
      { id: 173, section: "Mathématiques financières", question: "Calculer la valeur acquise d'un placement de 2 000 000 FCFA placé à intérêts composés au taux annuel de 5 % pendant 4 ans.", answer: "Correction : Cn = C0 × (1 + i)^n = 2 000 000 × (1,05)^4 = 2 000 000 × 1,215506 = 2 431 012 FCFA." },
      { id: 225, section: "Droit des affaires", question: "Quelles sont les 4 conditions de validité d’un contrat commercial selon le droit sénégalais et OHADA ?", answer: "Correction : 1. Le consentement non vicié des parties contractantes ; 2. La capacité juridique d'exercer le commerce ; 3. Un objet certain, licite et déterminable ; 4. Une cause licite et conforme aux bonnes mœurs." },
      { id: 261, section: "Management", question: "Définir les caractéristiques d'un objectif SMART dans la conduite d'une équipe commerciale.", answer: "Correction : S (Spécifique/Clair), M (Mesurable avec indicateurs chiffrés), A (Atteignable), R (Réaliste/Pertinent), T (Temporellement défini avec une échéance précise)." },
      { id: 316, section: "Entrepreneuriat", question: "Calculer le point mort en jours pour un projet ayant un chiffre d'affaires prévisionnel de 36 000 000 FCFA et un seuil de rentabilité de 24 000 000 FCFA sur une année de 360 jours.", answer: "Correction : Point mort = (Seuil de rentabilité / Chiffre d'affaires) × 360 jours = (24 000 000 / 36 000 000) × 360 = (2/3) × 360 = 240 jours d'activité." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 120,
    created_at: new Date().toISOString(),
  },

  // 6. CONCOURS ÉCOLE D'AGRICULTURE DE L'ARMÉE — SÉNÉGAL
  {
    id: 'annale-eaa-sn',
    slug: 'concours-ecole-agriculture-armee-senegal-fascicule-complet',
    title: "Concours École d'Agriculture de l'Armée — Sénégal : Fascicule Complet",
    ministry: "Ministère des Forces Armées & Ministère de l'Agriculture — Sénégal",
    category: "Agriculture de l'Armée",
    target_corps: "Militaires techniciens agricoles, exploitants agro-pastoraux des Armées et sous-officiers spécialistes ruraux",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Militaire Agro-Pastorale 2026',
    total_exercises: 320,
    total_pages: 12,
    rating: 4.99,
    reviews_count: 367,
    cover_gradient: 'from-emerald-950 via-teal-900 to-slate-950',
    cover_image: '/covers/agriculture_armee.jpg',
    accent_color: '#10b981',
    badge: 'Agro-Militaire & Souveraineté',
    description: "320 exercices distincts sans répétition pour réussir le concours de l'École d'Agriculture de l'Armée du Sénégal : agronomie générale, productions végétales et maraîchères, élevage et santé animale, gestion des fermes militaires, mathématiques et calculs agricoles de rendement, déontologie et discipline militaire, tests psychotechniques et préparation physique + 4 concours blancs complets.",
    official_reference: "Programme de Formation Agricole des Forces Armées — Ministère des Forces Armées de la République du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Français, rédaction technique et comptes rendus", count: 32, description: "Accords, syntaxe, rédaction de fiches d'exploitation agricole, rapports techniques et comptes rendus de service." },
      { title: "2. Mathématiques, surfaces et calculs de rendement", count: 32, description: "Calculs de doses d'engrais, périmètres et surfaces de parcelles, débits d'irrigation, pourcentages et calculs d'amortissement." },
      { title: "3. Agronomie générale et sciences du sol", count: 32, description: "Texture, structure des sols, pédologie du Sénégal, fertilisation organique, compostage et préservation des ressources en eau." },
      { title: "4. Productions végétales et cultures vivrières", count: 32, description: "Céréales (mil, maïs, riz), maraîchage, arboriculture, rotation des cultures, lutte intégrée contre les ravageurs et calendrier cultural." },
      { title: "5. Productions animales et élevage agro-pastoral", count: 32, description: "Aviculture, embouche bovine et ovine, alimentation du cheptel, hygiène vétérinaire, prophylaxie et gestion des pâturages." },
      { title: "6. Machinisme, hydraulique et gestion de fermes", count: 32, description: "Entretien des motopompes, systèmes de goutte-à-goutte, forages solaires, maintenance des équipements et logistique de stockage." },
      { title: "7. Discipline militaire, éthique et chaîne de commandement", count: 32, description: "Règlement de discipline générale dans les armées, sens de la mission, sécurité des installations et obéissance légitime." },
      { title: "8. Logique, psychotechnique et organisation du travail", count: 32, description: "Suites logiques, planification de chantier agricole, priorisation des tâches opérationnelles et gestion des imprévus." },
      { title: "9. Condition physique, hygiène de terrain et secourisme", count: 32, description: "Endurance opérationnelle, rusticité, hydratation, gestes d'urgence et secourisme en milieu rural et isolé." },
      { title: "10. Grand oral et projet professionnel agro-militaire", count: 32, description: "Présentation de son parcours, motivation pour la souveraineté alimentaire nationale, posture militaire et entretien avec le jury." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Écrit général, calculs et sciences du sol", duration: "3h00", questions_count: 6 },
      { title: "Concours blanc 2 — Productions végétales et animales", duration: "3h00", questions_count: 6 },
      { title: "Concours blanc 3 — Machinisme, hydraulique et gestion", duration: "2h30", questions_count: 6 },
      { title: "Concours blanc 4 — Épreuve intégrée Agro-Militaire", duration: "4h00", questions_count: 6 }
    ],
    sample_exercises: [
      { id: 1, section: "Rédaction Technique", question: "Rédigez un compte rendu succinct après la détection d'une invasion d'acridiens sur une parcelle de maïs militaire.", answer_preview: "Correction attendue : Localisation précise de la parcelle, superficie impactée, stade végétatif du maïs, densité des ravageurs et mesures conservatoires immédiates." },
      { id: 34, section: "Calcul Agricole", question: "Une motopompe débite 18 m³/h. Combien de temps faut-il pour apporter 72 m³ d'eau à un casier rizicole ?", answer_preview: "Correction : Temps = Volume / Débit = 72 m³ / 18 m³/h = 4 heures d'arrosage." },
      { id: 194, section: "Agronomie", question: "Quels sont les avantages d'une fumure organique par rapport aux seuls engrais chimiques ?", answer_preview: "Correction attendue : Amélioration durable de la structure et de la rétention d'eau du sol, stimulation de l'activité microbienne, apport progressif d'oligo-éléments et diminution du risque de salinisation." }
    ],
    protected_exercises: [
      { id: 1, section: "Français & Rapport de Ferme", question: "Accorder les participes passés : « Les semences sélectionnées que l'intendance a (fourni) ont été (semé) dès les premières pluies. »", answer: "Correction : « Les semences sélectionnées que l'intendance a fournies ont été semées dès les premières pluies. » « fournies » s'accorde avec le COD antéposé « que » (féminin pluriel) ; « semées » s'accorde avec le sujet passif." },
      { id: 34, section: "Mathématiques et Irrigation", question: "Une parcelle de 2 hectares reçoit un apport d'eau équivalent à une lame d'eau de 30 mm. Quel est le volume total en m³ nécessaire ?", answer: "Correction : 1 ha = 10 000 m². 2 ha = 20 000 m². 30 mm = 0,03 m. Volume = 20 000 × 0,03 = 600 m³ d'eau." },
      { id: 65, section: "Calcul de Doses d'Engrais", question: "Pour apporter 60 unités d'azote par hectare sur une parcelle de 3 ha avec de l'urée à 46 %, quelle masse totale d'urée faut-il ?", answer: "Correction : Besoin total = 60 × 3 = 180 unités de N. Masse d'urée = 180 / 0,46 = 391,3 kg d'urée (soit 8 sacs de 50 kg)." },
      { id: 98, section: "Pédologie & Conservation", question: "Expliquer le rôle de la matière organique dans la lutte contre l'érosion des sols sous climat sahélien.", answer: "Correction : La matière organique forme des agrégats stables avec l'argile (complexe argilo-humique), augmente la cohésion du sol face au vent (déflation éolienne) et améliore l'infiltration lors des pluies orageuses, limitant le ruissellement décapant." },
      { id: 161, section: "Productions Végétales", question: "Définir la rotation culturale et citer deux bénéfices agronomiques majeurs pour une exploitation.", answer: "Correction : La rotation est la succession ordonnée de cultures différentes sur une même parcelle au fil des campagnes. Bénéfices : rupture des cycles de ravageurs et maladies spécifiques, et valorisation optimale des nutriments (ex. alternance légumineuse fixatrice d'azote et céréale gourmande)." },
      { id: 193, section: "Discipline Militaire & Sécurité", question: "Pourquoi la tenue d'un carnet d'exploitation et d'un registre des stocks d'intrants est-elle une exigence de sécurité militaire ?", answer: "Correction : Elle garantit la traçabilité des ressources publiques de l'État, prévient les pertes et détournements d'intrants stratégiques, et permet au commandement d'anticiper les approvisionnements vitaux des cantonnements." },
      { id: 257, section: "Machinisme & Hydraulique", question: "Quels sont les trois points de contrôle quotidiens obligatoires avant le démarrage d'un tracteur ou d'une motopompe ?", answer: "Correction : 1. Niveau d'huile moteur ; 2. Niveau du liquide de refroidissement / état du radiateur ; 3. Propreté du filtre à air et absence de fuite de carburant." },
      { id: 289, section: "Grand Oral", question: "Comment convaincre le jury militaire de votre motivation pour la filière agricole des Forces Armées ?", answer: "Correction : 1. Souligner que la souveraineté alimentaire est le premier pilier de la sécurité nationale ; 2. Montrer son attachement à la terre et à la rigueur militaire ; 3. Exprimer sa fierté de produire pour nourrir les troupes et les populations en zone de déploiement." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 121,
    created_at: new Date().toISOString(),
  },

  // 7. CONCOURS ESOGN — SÉNÉGAL (École des Sous-Officiers de la Gendarmerie Nationale)
  {
    id: 'annale-esogn-sn',
    slug: 'concours-esogn-gendarmerie-senegal-fascicule-complet',
    title: "Concours ESOGN — Sénégal : École des Sous-Officiers de la Gendarmerie Nationale",
    ministry: "Ministère des Forces Armées — Haut Commandement de la Gendarmerie Nationale",
    category: "Gendarmerie (ESOGN)",
    target_corps: "Élèves Sous-Officiers de Gendarmerie (ESOGN Fatick - Camp Capitaine Saïdou Nourou Tall)",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale Sous-Officiers Gendarmerie',
    total_exercises: 320,
    total_pages: 22,
    rating: 4.96,
    reviews_count: 248,
    cover_gradient: 'from-emerald-950 via-slate-900 to-teal-950',
    cover_image: '/covers/esogn.jpg',
    accent_color: '#059669',
    badge: 'Sous-Officiers Gendarmerie',
    description: "320 exercices distincts sans répétition pour réussir le concours direct d'entrée à l'École des Sous-Officiers de la Gendarmerie Nationale (ESOGN Fatick). Français militaire, mathématiques et logique, institutions républicaines, missions de la Gendarmerie (ordre public, police judiciaire, sécurité routière), tests psychotechniques et préparation physique + 4 concours blancs complets.",
    official_reference: "Haut Commandement de la Gendarmerie Nationale et Direction de la Justice Militaire — Sénégal (ESOGN Fatick).",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Français militaire et rédaction de comptes-rendus", count: 40, description: "Grammaire, vocabulaire militaire, compte-rendu d'incident, procès-verbal sommaire et synthèse." },
      { title: "2. Mathématiques opérationnelles et calcul mental", count: 40, description: "Arithmétique, pourcentages, vitesses de patrouille, consommation de carburant et calculs d'itinéraires." },
      { title: "3. Institutions de la République et instruction civique", count: 35, description: "Constitution du Sénégal, pouvoirs publics, droits fondamentaux du citoyen et symboles de l'État." },
      { title: "4. Organisation et missions de la Gendarmerie", count: 35, description: "Gendarmerie territoriale, gendarmerie mobile, police judiciaire, police administrative et prévôté." },
      { title: "5. Notions de Droit pénal et procédure", count: 35, description: "Infractions, flagrant délit, cadre d'action de l'APJ et de l'OPJ, légitime défense et usage des armes." },
      { title: "6. Sécurité routière et constatations d'accidents", count: 30, description: "Code de la route sénégalais, contrôle des véhicules, mesures conservatoires et secours d'urgence." },
      { title: "7. Topographie, orientation et lecture de cartes", count: 30, description: "Coordonnées géographiques, boussole, azimut, calcul de distances et repérage de zone." },
      { title: "8. Logique, suites et tests psychotechniques", count: 30, description: "Suites numériques, dominos, matrices visuelles, raisonnement spatial et déduction sous stress." },
      { title: "9. Discipline militaire et déontologie", count: 25, description: "Devise Honneur et Patrie, règlement de discipline générale, obéissance légale et hiérarchie." },
      { title: "10. Grand Oral avec le jury et entretien de motivation", count: 20, description: "Présentation martiale, motivation pour le métier des armes, connaissance du territoire national et sang-froid." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Français & Dictée militaire", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 2 — Mathématiques & Logique", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 3 — Institutions & Sécurité Publique", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 4 — Simulation finale intégrale ESOGN", duration: "4h00", questions_count: 20 }
    ],
    sample_exercises: [
      { id: 1, section: "Organisation Militaire", question: "Quelle est la devise officielle de la Gendarmerie Nationale du Sénégal et quel est son ministère de tutelle ?", answer_preview: "Devise : « Honneur et Patrie ». Tutelle : Ministère des Forces Armées (pour l'emploi militaire) et Ministère de l'Intérieur / Justice (pour l'emploi civil et judiciaire)." },
      { id: 2, section: "Français & Rédaction", question: "Distinguez un compte-rendu d'un rapport dans la correspondance militaire.", answer_preview: "Le compte-rendu expose rapidement et fidèlement un fait survenu (qui, quoi, où, quand) ; le rapport est plus détaillé, analyse les causes et propose des mesures ou sanctions." }
    ],
    protected_exercises: [
      { id: 1, section: "Organisation Militaire", question: "Quelle est la devise officielle de la Gendarmerie Nationale du Sénégal et quelles sont ses missions fondamentales ?", answer: "Correction : La devise officielle de la Gendarmerie Nationale du Sénégal est « Honneur et Patrie ». Ses missions fondamentales se divisent en trois volets majeurs : 1) La police administrative (maintien et rétablissement de l'ordre public, surveillance du territoire et des voies de communication), 2) La police judiciaire (constatation des infractions pénales, rassemblement des preuves et recherche des auteurs), et 3) Les missions militaires (défense opérationnelle du territoire et prévôté auprès des forces armées)." },
      { id: 2, section: "Français militaire & Procédures", question: "Rédigez la trame réglementaire d'un compte-rendu d'incident d'ordre public survenu lors d'un rassemblement forain.", answer: "Correction : La structure réglementaire d'un compte-rendu militaire comprend : 1) En-tête officiel de l'unité de Gendarmerie émettrice avec date, lieu et heure de rédaction, 2) Mention d'urgence et destinataire hiérarchique (Commandant de Compagnie / Légion), 3) Objet clair et précis de l'incident, 4) Exposé chronologique et objectif des faits (circonstances de survenue, acteurs identifiés, incidents constatés), 5) Mesures d'urgence prises (dispersion, évacuation, interpellations sous contrôle d'OPJ, sécurisation des biens et personnes), 6) Bilan humain et matériel provisoire, 7) Dispositif de veille maintenu et signature du gradé rédacteur." },
      { id: 3, section: "Mathématiques opérationnelles", question: "Une patrouille de gendarmerie quitte Kaolack pour Fatick (distance 45 km) à la vitesse moyenne de 75 km/h. À quelle heure arrivera-t-elle si elle part à 08h20 min ?", answer: "Correction : Temps de trajet t = distance / vitesse = 45 / 75 = 0,6 heure. En minutes : 0,6 × 60 = 36 minutes. Heure d'arrivée : 08h20 min + 36 min = 08h56 min." },
      { id: 4, section: "Institutions & Droits", question: "Quelle est la distinction fondamentale entre un Officier de Police Judiciaire (OPJ) et un Agent de Police Judiciaire (APJ) dans le Code de Procédure Pénale sénégalais ?", answer: "Correction : L'OPJ a la plénitude de compétence pour diriger les enquêtes, recevoir les plaintes et dénonciations, procéder aux auditions, ordonner des perquisitions dans les formes légales et décider de mesures de garde à vue avec information immédiate du Procureur de la République. L'APJ seconde l'OPJ dans l'exercice de ses fonctions, constate les infractions et rend compte fidèlement à son supérieur hiérarchique, mais n'a pas compétence autonome pour décider seul de gardes à vue ou signer des procès-verbaux de clôture." },
      { id: 5, section: "Topographie & Orientation", question: "Définissez un azimut en topographie militaire et expliquez la méthode pour le mesurer avec une boussole.", answer: "Correction : L'azimut est l'angle horizontal formé entre la direction du Nord (magnétique ou géographique) et la ligne de visée orientée vers un objectif précis, mesuré en degrés (de 0° à 360°) dans le sens des aiguilles d'une montre. Pour le mesurer : 1) Orienter la boussole à plat, 2) Aligner la ligne de visée vers l'objectif visible, 3) Tourner le cadran mobile pour superposer l'aiguille magnétique avec le repère Nord du boîtier, 4) Lire la graduation en degrés en face du repère d'index." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 122,
    created_at: new Date().toISOString(),
  },

  // 8. CONCOURS BT COMPTABILITÉ — SÉNÉGAL
  {
    id: 'annale-bt-comptabilite-sn',
    slug: 'concours-bt-comptabilite-senegal-fascicule-complet',
    title: "Concours BT Comptabilité — Sénégal : Fascicule Complet",
    ministry: "Ministère de la Formation Professionnelle, de l'Apprentissage et de l'Insertion",
    category: "BT Comptabilité",
    target_corps: "Comptables assistants, aides-comptables certifiés et teneurs de livres en cabinet ou entreprise",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Conforme Brevet de Technicien 2026',
    total_exercises: 320,
    total_pages: 20,
    rating: 4.95,
    reviews_count: 219,
    cover_gradient: 'from-blue-950 via-sky-900 to-slate-950',
    cover_image: '/covers/bt_comptabilite.jpg',
    accent_color: '#0284c7',
    badge: 'Comptabilité Pratique',
    description: "320 exercices d'application corrigés pas-à-pas pour réussir le concours et l'examen du Brevet de Technicien (BT) Comptabilité au Sénégal : comptabilité générale, analyse financière, fiscalité (TVA, BRS, VRS), gestion des entreprises, informatique de gestion et communication professionnelle + 4 concours blancs complets.",
    official_reference: "Direction des Examens et Concours Professionnels (DECPC) — Brevet de Technicien en Comptabilité.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Comptabilité générale et écritures courantes", count: 45, description: "Facturation, achats, ventes, règlements, TVA et état de rapprochement bancaire." },
      { title: "2. Opérations d'inventaire et de régularisation", count: 45, description: "Amortissements linéaires et dégressifs, provisions, stocks et charges/produits constatés d'avance." },
      { title: "3. Fiscalité pratique sénégalaise", count: 35, description: "Calcul et déclaration de TVA, acomptes provisionnels, VRS et retenue à la source (BRS)." },
      { title: "4. Gestion de la paie et charges sociales", count: 35, description: "Salaire brut, cotisations IPRES, CSS, CFCE, impôt sur le revenu (IR) et net à payer." },
      { title: "5. Analyse financière élémentaire", count: 30, description: "Bilan fonctionnel, FRNG, BFR, trésorerie nette et ratios de solvabilité." },
      { title: "6. Informatique et tableur Excel de gestion", count: 30, description: "Formules conditionnelles, tableaux croisés dynamiques, fonctions financières et sécurité." },
      { title: "7. Mathématiques financières et commerciales", count: 30, description: "Taux d'intérêt, escompte commercial, équivalence d'effets et amortissement d'emprunt." },
      { title: "8. Droit des affaires et de l'entreprise (SYSCOHADA)", count: 25, description: "Principes comptables OHADA révisé, forme des sociétés et tenue des livres légaux." },
      { title: "9. Communication professionnelle et secrétariat comptable", count: 25, description: "Rédaction de notes de service, correspondances bancaires et classement d'archives." },
      { title: "10. Grand oral et mise en situation professionnelle", count: 20, description: "Présentation devant la commission d'examen, défense d'un dossier comptable et maîtrise pratique." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Écritures courantes et TVA", duration: "3h00", questions_count: 10 },
      { title: "Concours blanc 2 — Travaux d'inventaire et paie", duration: "3h00", questions_count: 10 },
      { title: "Concours blanc 3 — Analyse financière et mathématiques", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 4 — Épreuve finale intégrale BT Comptabilité", duration: "4h00", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 1, section: "SYSCOHADA", question: "Enregistrez au journal une facture d'achat de marchandises de 1 000 000 F CFA HT, remise 5 %, port forfaitaire 50 000 F, TVA 18 %.", answer_preview: "Correction : Net commercial = 950 000 F. Base TVA = 950 000 + 50 000 = 1 000 000 F. TVA = 180 000 F. Net à payer TTC = 1 180 000 F." },
      { id: 25, section: "Fiscalité", question: "Quel est le taux normal de la TVA au Sénégal et la date limite mensuelle de dépôt de la déclaration ?", answer_preview: "Correction : Taux normal de 18 %. La déclaration doit être déposée et payée au plus tard le 15 du mois suivant." }
    ],
    protected_exercises: [
      { id: 1, section: "Comptabilité des Salaires", question: "Un salarié a un salaire de base de 250 000 FCFA, prime d'ancienneté 30 000 FCFA. Calculez l'assiette des cotisations sociales et les parts IPRES RG (3 % salarié, 4,2 % employeur).", answer: "Correction : Brut imposable = 280 000 FCFA. Part salariale IPRES RG = 280 000 × 3 % = 8 400 FCFA. Part patronale = 280 000 × 4,2 % = 11 760 FCFA." },
      { id: 2, section: "Amortissements", question: "Un matériel acquis 6 000 000 FCFA HT le 01/04/N a une durée de 5 ans en linéaire. Calculez l'annuité de l'année N.", answer: "Correction : Taux = 20 %. Prorata temporis du 01/04 au 31/12 = 9 mois. Annuité N = 6 000 000 × 20 % × (9 / 12) = 900 000 FCFA." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 123,
    created_at: new Date().toISOString(),
  }
];
