import { Annale } from './db.js';

export const additionalAnnales: Annale[] = [
  // 1. BTS TRANSIT — SÉNÉGAL : TOME 1
  {
    id: 'annale-bts-transit-sn',
    slug: 'concours-bts-transit-senegal-tome-1',
    title: 'BTS Transit — Sénégal : Tome 1',
    ministry: "Ministère de la Formation Professionnelle, de l'Apprentissage et de l'Artisanat",
    category: 'BTS Transit',
    target_corps: 'Déclarants en douane, Agents de transit, Gestionnaires de fret maritime et aérien',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale BTS 2026',
    total_exercises: 320,
    total_pages: 36,
    rating: 4.96,
    reviews_count: 248,
    cover_gradient: 'from-cyan-950 via-teal-900 to-slate-950',
    cover_image: '/covers/bts_transit.jpg',
    accent_color: '#06b6d4',
    badge: 'Transit & Douane',
    description: "320 exercices distincts avec corrections détaillées : douane et réglementation douanière, transit douanier et transport, commerce international et Incoterms, transport maritime/portuaire/conteneurs, logistique routière, documents commerciaux (facture, packing list), calculs douaniers et financiers, anglais professionnel, informatique/GAINDE et cas pratiques professionnels + 4 concours blancs complets.",
    official_reference: "Brevet de Technicien Supérieur (BTS) Transit — Direction des Examens et Concours (DECO) du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Douane et réglementation douanière", count: 32, description: "Fonctions fiscale et économique, territoire douanier, déclaration, commissionnaire agréé, valeur en douane, origine et classement tarifaire." },
      { title: "2. Transit douanier et opérations de transport", count: 32, description: "Régime du transit, bureaux de départ/destination, garanties douanières, délais, scellés, traçabilité et apurement du transit." },
      { title: "3. Commerce international et Incoterms", count: 32, description: "Contrat de vente internationale, facture commerciale, packing list, Incoterms (EXW, FCA, FOB, CIF, DAP, DDP) et lettre de crédit." },
      { title: "4. Transport maritime, portuaire et conteneurs", count: 32, description: "Armateur, consignataire, connaissement (Bill of Lading), FCL/LCL, dépotage/empotage, surestaries et avaries maritimes." },
      { title: "5. Transport routier, logistique et chaîne d’approvisionnement", count: 32, description: "Lettre de voiture, planning de livraison, taux de service, coût au km/tonne, gestion des stocks et tournées de livraison." },
      { title: "6. Documents commerciaux, administratifs et opérations de transit", count: 32, description: "Dossier import/export, facture pro forma, certificat d'origine, cohérence documentaire et archivage professionnel." },
      { title: "7. Calculs douaniers, financiers et statistiques", count: 32, description: "TVA, remises commerciales, devises, coût de fret, marge commerciale, rotation des stocks et productivité d'agence." },
      { title: "8. Anglais professionnel et communication", count: 32, description: "Terminologie maritime (shipment, consignee, bill of lading, customs clearance), correspondance et relances en anglais." },
      { title: "9. Informatique, systèmes et traçabilité du transit", count: 32, description: "Systèmes d'information logistique, GAINDE, dématérialisation, sécurité des données et tableaux de suivi Excel." },
      { title: "10. Cas pratiques intégrés et gestion professionnelle", count: 32, description: "Traitement des anomalies documentaires, scellés rompus, sous-évaluation, litiges et tableaux de bord d'exploitation." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Douane et déclaration", duration: "3h00", questions_count: 8 },
      { title: "Concours blanc 2 — Transit et transport", duration: "3h00", questions_count: 8 },
      { title: "Concours blanc 3 — Commerce international", duration: "3h00", questions_count: 8 },
      { title: "Concours blanc 4 — Épreuve intégrée BTS Transit", duration: "4h00", questions_count: 8 }
    ],
    sample_exercises: [
      { id: 1, section: "Douane et réglementation", question: "Définir la fonction économique et fiscale de la douane.", answer_preview: "Correction attendue : Identifier les missions de perception fiscale (droits de porte, TVA à l'import) et de protection économique (sauvegarde de la production locale, contrôle sanitaire et répression des fraudes)." },
      { id: 76, section: "Commerce international", question: "Définir un Incoterm.", answer_preview: "Correction attendue : Les Incoterms (International Commercial Terms) de la CCI déterminent la répartition précise des frais, des risques de transport et des formalités documentaires entre vendeur et acheteur." },
      { id: 103, section: "Transport maritime", question: "Définir un connaissement maritime (Bill of Lading).", answer_preview: "Correction attendue : Document délivré par le transporteur maritime attestant de la prise en charge de la marchandise, matérialisant le contrat de transport et conférant la propriété des biens au porteur régulier." }
    ],
    protected_exercises: [
      { id: 1, section: "Douane et réglementation", question: "Définir la fonction économique et fiscale de la douane.", answer: "Correction : La douane assure une double fonction : fiscale (perception des droits de douane et taxes pour le Trésor public) et économique (protection du tissu industriel national, régulation des flux commerciaux, surveillance du territoire et application des accords préférentiels)." },
      { id: 4, section: "Douane et réglementation", question: "Différencier importation, exportation et transit.", answer: "Correction : L'importation est l'introduction définitive de marchandises étrangères sur le territoire douanier ; l'exportation est la sortie définitive de marchandises nationales vers l'étranger ; le transit est le transport sous contrôle douanier sans acquittement immédiat des droits et taxes." },
      { id: 8, section: "Douane et réglementation", question: "Définir le déclarant en douane et préciser son statut.", answer: "Correction : Le déclarant est la personne physique ou morale qui effectue la déclaration en douane en son nom propre ou pour le compte d'autrui (commissionnaire en douane agréé détenant un agrément ministériel officiel au Sénégal)." },
      { id: 11, section: "Valeur en douane", question: "Définir la valeur en douane à l'importation.", answer: "Correction : La valeur en douane à l'importation est la valeur transactionnelle (prix payé ou à payer) ajustée des éléments obligatoires (fret maritime, assurance jusqu'au port de Dakar selon l'Incoterm CIF)." },
      { id: 15, section: "Origine des marchandises", question: "Différencier origine préférentielle et origine non préférentielle.", answer: "Correction : L'origine non préférentielle sert à appliquer le tarif de droit commun, les mesures antidumping et les statistiques ; l'origine préférentielle (ex: CEDEAO, ZLECAF) permet de bénéficier de droits réduits ou nuls." },
      { id: 33, section: "Transit douanier", question: "Définir le régime du transit douanier.", answer: "Correction : Régime suspensif permettant l'acheminement de marchandises sous surveillance douanière d'un bureau de départ à un bureau de destination (ex: Port de Dakar vers Kidira ou Bamako) en suspension des droits et taxes." },
      { id: 42, section: "Garantie de transit", question: "Présenter le principe de la garantie en matière de transit.", answer: "Correction : L'acquit-à-caution exige une caution financière ou bancaire garantissant à l'administration douanière le paiement des droits et taxes si les marchandises venaient à être détournées frauduleusement sur le territoire national." },
      { id: 48, section: "Sécurité du transit", question: "Analyser un cas de rupture de scellé douanier en cours de route.", answer: "Correction : Le transporteur doit immédiatement alerter le poste de douane ou de gendarmerie le plus proche pour dresser un procès-verbal de constatation d'avarie ou d'incident avant toute manipulation de la cargaison." },
      { id: 65, section: "Commerce international", question: "Définir le commerce international et ses flux.", answer: "Correction : Échange de biens et de services à travers les frontières nationales, impliquant des flux physiques de marchandises, des flux documentaires et des flux financiers internationaux." },
      { id: 78, section: "Incoterms", question: "Comparer EXW (Ex Works) et FCA (Free Carrier).", answer: "Correction : En EXW, l'acheteur assume tous les frais et risques dès la mise à disposition dans les locaux du vendeur (dédouanement export à sa charge). En FCA, le vendeur charge et dédouane la marchandise à l'exportation." },
      { id: 79, section: "Incoterms", question: "Comparer FOB (Free On Board) et CIF (Cost, Insurance and Freight).", answer: "Correction : En FOB, le transfert des risques et des frais a lieu lorsque la marchandise est chargée à bord du navire au port de départ. En CIF, le vendeur paie le fret maritime et l'assurance jusqu'au port d'arrivée, mais le risque est transféré dès le chargement." },
      { id: 89, section: "Paiement international", question: "Définir la lettre de crédit (crédit documentaire).", answer: "Correction : Engagement irrévocable pris par la banque de l'importateur de payer l'exportateur contre présentation stricte de documents conformes attestant de l'expédition des marchandises dans les délais stipulés." },
      { id: 97, section: "Transport maritime", question: "Présenter les caractéristiques majeures du transport maritime.", answer: "Correction : Capacité d'emport massive, coûts unitaires faibles au conteneur, lenteur relative des traversées, standardisation des unités de charge (EVP/TEU) et soumission aux règles internationales de La Haye-Visby." },
      { id: 103, section: "Connaissement", question: "Définir le connaissement maritime (Bill of Lading).", answer: "Correction : Document émis par le transporteur maritime constatant la mise à bord des marchandises, concrétisant le contrat d'affrètement maritime et représentant la propriété de la cargaison." },
      { id: 112, section: "Conteneurisation", question: "Différencier conteneur FCL (Full Container Load) et LCL (Less than Container Load).", answer: "Correction : En FCL (complet), le conteneur est empoté par un seul chargeur pour un seul destinataire. En LCL (groupage), plusieurs lots appartenant à différents expéditeurs sont regroupés dans un même conteneur." },
      { id: 118, section: "Gestion portuaire", question: "Expliquer la notion de surestaries (demurrage).", answer: "Correction : Pénalités financières facturées par la compagnie maritime pour dépassement de la franchise accordée pour le déchargement et la restitution du conteneur vide après arrivée au port." },
      { id: 135, section: "Transport routier", question: "Expliquer le rôle de la lettre de voiture (CMR).", answer: "Correction : Document contractuel de transport routier matérialisant l'accord entre l'expéditeur et le transporteur, attestant de la prise en charge des colis et fixant les réserves éventuelles à la livraison." },
      { id: 161, section: "Documents de transit", question: "Identifier les pièces fondamentales d’un dossier d’importation au Sénégal.", answer: "Correction : Facture commerciale originale, connaissement maritime (B/L), liste de colisage (packing list), certificat d'origine, déclaration préalable d'importation (DPI), attestation d'assurance locale et certificat de vérification (ex: AV/ORIBUS)." },
      { id: 196, section: "Calculs douaniers", question: "Calculer la TVA à 18 % sur une base taxable de 12 500 000 FCFA.", answer: "Correction : TVA = 12 500 000 × 0,18 = 2 250 000 FCFA." },
      { id: 226, section: "Anglais professionnel", question: "Définir shipment, consignee, shipper et freight.", answer: "Correction : Shipment = expédition/cargaison ; Shipper = chargeur/expéditeur ; Consignee = destinataire ; Freight = fret (prix du transport)." },
      { id: 261, section: "Systèmes d'information", question: "Présenter le rôle du système GAINDE dans la douane sénégalaise.", answer: "Correction : GAINDE (Gestion Automatisée des Informations Douanières et des Échanges) permet la transmission électronique des manifestes, l'enregistrement des déclarations, le dédouanement informatisé et le paiement électronique des droits." },
      { id: 320, section: "Pratique professionnelle", question: "Construire une checklist finale de conformité d’une opération de transit avant apurement.", answer: "Correction : Vérifier la concordance B/L - manifeste, la validation du certificat de visite, la preuve d'apurement de l'acquit au bureau frontière et la restitution de la caution bancaire." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 110,
    created_at: new Date().toISOString(),
  },

  // 2. BTS SECRÉTARIAT-BUREAUTIQUE — SÉNÉGAL : TOME 1
  {
    id: 'annale-bts-secretariat-sn',
    slug: 'concours-bts-secretariat-bureautique-senegal-tome-1',
    title: 'BTS Secrétariat-Bureautique — Sénégal : Tome 1',
    ministry: "Ministère de la Formation Professionnelle, de l'Apprentissage et de l'Artisanat",
    category: 'BTS Secrétariat',
    target_corps: 'Assistants de Direction, Secrétaires de Direction, Gestionnaires Administratifs',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Bureautique d’Élite 2026',
    total_exercises: 320,
    total_pages: 35,
    rating: 4.95,
    reviews_count: 210,
    cover_gradient: 'from-purple-950 via-fuchsia-900 to-slate-950',
    cover_image: '/covers/bts_secretariat.jpg',
    accent_color: '#c026d3',
    badge: 'Secrétariat & Bureautique',
    description: "320 exercices pratiques corrigés sans répétition : communication professionnelle et accueil, secrétariat et agenda de direction, français et rédaction administrative (lettres officielles, notes de service, comptes rendus, PV de réunion), Word avancé, Excel et calculs de gestion, PowerPoint, archivage et gestion documentaire, comptabilité commerciale et facturation, anglais professionnel et management de bureau + 4 concours blancs.",
    official_reference: "Brevet de Technicien Supérieur (BTS) Secrétariat-Bureautique — Ministère de la Formation Professionnelle du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Communication professionnelle et expression", count: 32, description: "Communication verbale et non verbale, accueil physique/téléphonique, gestion des usagers difficiles et courriels professionnels." },
      { title: "2. Secrétariat, accueil et organisation administrative", count: 32, description: "Tenue d'agenda, réunions de direction, ordres du jour, feuilles de présence, comptes rendus et missions de déplacement." },
      { title: "3. Français, rédaction administrative et correction", count: 32, description: "Grammaire administrative, accords, notes de service, attestations, bordereaux de transmission et synthèse de textes." },
      { title: "4. Bureautique Word et traitement de texte", count: 32, description: "Feuilles de style, tableaux complexes, publipostage, en-têtes/pieds de page, tables des matières et suivi des révisions." },
      { title: "5. Excel, tableaux et calculs de gestion", count: 32, description: "Formules Arithmétiques, fonctions SI, SOMME, MOYENNE, calculs de TVA/TTC, graphiques de suivi et tableaux de bord." },
      { title: "6. PowerPoint, présentation et outils numériques", count: 32, description: "Création de diaporamas percutants, transitions professionnelles, formats de fichiers (PDF, PPTX) et synthèses visuelles." },
      { title: "7. Gestion documentaire, archivage et classement", count: 32, description: "Plans de classement alphabétique/numérique, arborescence réseau, nommage normalisé et dématérialisation." },
      { title: "8. Comptabilité, gestion commerciale et facturation", count: 32, description: "Devis, bons de commande, bons de livraison, facturation, relances clients et échéanciers de paiement." },
      { title: "9. Anglais professionnel et communication numérique", count: 32, description: "Vocabulaire de secrétariat en anglais (meeting, invoice, schedule), courriels internationaux et accueil de visiteurs anglophones." },
      { title: "10. Situations professionnelles, management et droit du travail", count: 32, description: "Gestion des priorités, confidentialité absolue, ergonomie du poste de travail et prévention des conflits d'intérêts." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Secrétariat et communication", duration: "3h00", questions_count: 8 },
      { title: "Concours blanc 2 — Bureautique Word et Excel", duration: "3h00", questions_count: 8 },
      { title: "Concours blanc 3 — Gestion documentaire et commerciale", duration: "3h00", questions_count: 8 },
      { title: "Concours blanc 4 — Épreuve intégrée BTS Secrétariat", duration: "4h00", questions_count: 8 }
    ],
    sample_exercises: [
      { id: 1, section: "Communication professionnelle", question: "Définir la communication professionnelle et ses objectifs.", answer_preview: "Correction attendue : Transmission structurée d'informations au sein d'une organisation visant l'efficacité opérationnelle, la coordination des équipes et la qualité du service rendu." },
      { id: 47, section: "Secrétariat et réunions", question: "Différencier procès-verbal, compte rendu et relevé de décisions.", answer_preview: "Correction attendue : Le PV a une valeur juridique probante et retranscrit fidèlement les débats ; le compte rendu résume l'essentiel des échanges ; le relevé de décisions liste uniquement les actions adoptées avec leurs responsables." },
      { id: 139, section: "Calculs commerciaux", question: "Calculer un prix TTC à partir d’un prix HT de 85 000 FCFA au taux de TVA de 18 %.", answer_preview: "Correction : Montant TVA = 85 000 × 0,18 = 15 300 FCFA. Prix TTC = 85 000 + 15 300 = 100 300 FCFA." }
    ],
    protected_exercises: [
      { id: 1, section: "Communication professionnelle", question: "Définir la communication professionnelle et ses objectifs.", answer: "Correction : Processus d'émission et de réception de messages au sein ou en dehors de l'entreprise ayant pour but d'informer, de convaincre, de coordonner l'action administrative et de valoriser l'image de marque." },
      { id: 4, section: "Accueil professionnel", question: "Présenter les qualités d’un bon accueil professionnel.", answer: "Correction : Écoute active, disponibilité, courtoisie, présentation soignée, clarté dans l'orientation du visiteur et respect de la confidentialité." },
      { id: 12, section: "Communication écrite", question: "Présenter les règles de politesse dans un courriel professionnel.", answer: "Correction : Objet explicite, formule d'appel personnalisée (ex: « Monsieur le Directeur »), concision du corps, formule de salutation professionnelle adaptée et signature automatique avec coordonnées complètes." },
      { id: 36, section: "Organisation du travail", question: "Organiser une journée de travail comportant plusieurs urgences.", answer: "Correction : Utiliser la matrice d'Eisenhower : traiter immédiatement ce qui est urgent et important, planifier ce qui est important mais non urgent, déléguer ce qui est urgent non important et éliminer les distractions." },
      { id: 46, section: "Organisation de réunions", question: "Rédiger un ordre du jour de réunion de direction.", answer: "Correction : Document listant les points à débattre par ordre de priorité, les intervenants associés et la durée allouée pour chaque séquence afin de cadrer les travaux." },
      { id: 47, section: "Secrétariat administratif", question: "Rédiger un procès-verbal de réunion conforme aux usages.", answer: "Correction : Mentionner la date, l'heure, le lieu, la liste des membres présents/excusés, la présidence de séance, le résumé chronologique des débats et les résolutions votées." },
      { id: 65, section: "Français administratif", question: "Identifier le sujet, le verbe et les compléments dans une phrase administrative complexe.", answer: "Correction : Décomposer la structure syntaxique pour garantir la parfaite concordance des temps et le respect des accords du participe passé avec l'auxiliaire avoir." },
      { id: 84, section: "Rédaction administrative", question: "Rédiger une note de service relative au respect des horaires.", answer: "Correction : En-tête officiel, objet clair, rappel impersonnel des dispositions réglementaires, motifs de la note, instructions précises et formule de prise d'effet immédiate signée par la direction." },
      { id: 99, section: "Bureautique Word", question: "Utiliser correctement les styles de titre dans un rapport volumineux.", answer: "Correction : Appliquer les styles hiérarchiques Titre 1, Titre 2, Titre 3 pour uniformiser la typographie, faciliter la navigation dans le volet et générer automatiquement la table des matières." },
      { id: 126, section: "Publipostage", question: "Créer un publipostage à partir d’une liste de contacts Excel.", answer: "Correction : Lier le document principal Word à la base de données Excel, insérer les champs de fusion (« Civilité », « Nom », « Adresse »), prévisualiser les fusions et exécuter vers un nouveau document." },
      { id: 133, section: "Bureautique Excel", question: "Calculer une somme et une moyenne avec formules.", answer: "Correction : Utiliser les syntaxes =SOMME(B2:B30) et =MOYENNE(B2:B30) avec verrouillage des plages par des références absolues ($) si nécessaire pour le recopiage." },
      { id: 145, section: "Bureautique Excel", question: "Utiliser la fonction conditionnelle SI dans une situation administrative.", answer: "Correction : Syntaxe : =SI(test_logique; valeur_si_vrai; valeur_si_faux). Exemple : =SI(C2>=10; \"Admis\"; \"Ajourné\") pour le traitement automatique des résultats." },
      { id: 161, section: "Présentations PowerPoint", question: "Créer une présentation de cinq diapositives percutante.", answer: "Correction : Règle des 6×6 (maximum 6 lignes par slide et 6 mots par ligne), contraste visuel élevé, hiérarchie claire et utilisation d'illustrations représentatives sans surcharge textuelle." },
      { id: 195, section: "Gestion documentaire", question: "Différencier classement alphabétique, numérique et thématique.", answer: "Correction : Alphabétique (selon le mot d'ordre/nom), numérique (selon un numéro d'ordre chronologique ou matricule), thématique (selon l'objet ou la matière du dossier)." },
      { id: 201, section: "Gestion documentaire", question: "Définir une règle de nommage normalisée des fichiers administratifs.", answer: "Correction : Structure type : AAAA-MM-JJ_[TypeDoc]_[NomClient/Dossier]_[Version] sans accents ni espaces pour assurer la compatibilité multi-plateformes et l'ordre chronologique." },
      { id: 225, section: "Gestion commerciale", question: "Définir les mentions obligatoires d’une facture commerciale.", answer: "Correction : Nom et adresse des parties, NINEA, numéro de facture chronologique, date d'émission, désignation précise des biens/services, prix unitaires HT, taux de TVA, total TTC et modalités de règlement." },
      { id: 257, section: "Anglais professionnel", question: "Traduire en français : appointment, meeting, deadline, invoice, purchase order.", answer: "Correction : Appointment = rendez-vous ; Meeting = réunion ; Deadline = date limite/échéance ; Invoice = facture ; Purchase order = bon de commande." },
      { id: 291, section: "Déontologie & Confidentialité", question: "Définir la discrétion professionnelle et le secret de fonction de l'assistant.", answer: "Correction : Obligation légale et déontologique de ne divulguer aucune information, document ou fait dont on a connaissance dans l'exercice de ses fonctions sous peine de sanctions disciplinaires et pénales." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 111,
    created_at: new Date().toISOString(),
  },

  // 3. BTS GESTION DE LA CHAÎNE D’APPROVISIONNEMENT ET LOGISTIQUE — SÉNÉGAL : TOME 1
  {
    id: 'annale-bts-logistique-sn',
    slug: 'concours-bts-gestion-chaine-approvisionnement-logistique-senegal-tome-1',
    title: "BTS Gestion de la Chaîne d'Approvisionnement et Logistique — Sénégal : Tome 1",
    ministry: "Ministère de la Formation Professionnelle, de l'Apprentissage et de l'Artisanat",
    category: 'BTS Gestion Chaine Approvisionnement Logistique',
    target_corps: 'Responsables Approvisionnement, Chefs d’entrepôt, Coordinateurs Logistiques',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Officielle BTS GCA 2026',
    total_exercises: 320,
    total_pages: 38,
    rating: 4.97,
    reviews_count: 265,
    cover_gradient: 'from-amber-950 via-orange-900 to-slate-950',
    cover_image: '/covers/bts_logistique.jpg',
    accent_color: '#f59e0b',
    badge: 'GCA & Logistique',
    description: "320 exercices corrigés complets : fondamentaux de la supply chain et gestion des flux, achats et évaluation fournisseurs, gestion des stocks et inventaires (FIFO, stock de sécurité, point de commande), entreposage (picking, cross-docking, adressage), transport et distribution (multimodal, dernier kilomètre), planification de la demande, calculs logistiques et KPI, douane et Incoterms, ERP/WMS/TMS, anglais logistique et études de cas + 4 concours blancs.",
    official_reference: "Brevet de Technicien Supérieur (BTS) Gestion de la Chaîne d'Approvisionnement et Logistique — Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Fondamentaux de la supply chain", count: 35, description: "Flux physiques, financiers et d'information, chaîne amont et aval, coordination des acteurs et taux de satisfaction client." },
      { title: "2. Achats, fournisseurs et approvisionnement", count: 35, description: "Cahier des charges, sélection de fournisseurs, bons de commande, contrôle de conformité à réception et partenariats." },
      { title: "3. Gestion des stocks et inventaires", count: 40, description: "Stock de sécurité, stock d'alerte, rotation des stocks, méthode FIFO, inventaires permanents et coût de rupture." },
      { title: "4. Entrepôt, magasinage et manutention", count: 35, description: "Organisation des zones de stockage, techniques de picking, cross-docking, optimisation des parcours et règles de sécurité." },
      { title: "5. Transport et distribution", count: 35, description: "Transport multimodal, plan de transport, bons de livraison, optimisation des tournées et logistique du dernier kilomètre." },
      { title: "6. Prévision de la demande et planification", count: 25, description: "Variations saisonnières, rupture de capacité, synchronisation achats/production et planification opérationnelle." },
      { title: "7. Calculs logistiques, coûts et indicateurs KPI", count: 35, description: "Taux de service, taux d'avarie, débit horaire d'entrepôt, coût par tonne/km, rotation des stocks et réduction des coûts." },
      { title: "8. Douane, commerce international et Incoterms", count: 20, description: "Incoterms EXW, FOB, CIF, DDP, déclarations douanières, certificats d'origine et classement tarifaire." },
      { title: "9. Informatique, systèmes d’information et digitalisation", count: 20, description: "Progiciels ERP, progiciels d'entrepôt WMS, gestion de transport TMS, codes-barres et traçabilité RFID." },
      { title: "10. Anglais logistique & Études de cas management", count: 40, description: "Anglais technique de la chaîne d'approvisionnement, plans d'action d'urgence, méthode 5S et amélioration continue." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Approvisionnement complet", duration: "4h00", questions_count: 5 },
      { title: "Concours blanc 2 — Entrepôt et productivité", duration: "4h00", questions_count: 5 },
      { title: "Concours blanc 3 — Transport international", duration: "4h00", questions_count: 5 },
      { title: "Concours blanc 4 — Cas supply chain intégral", duration: "4h00", questions_count: 5 }
    ],
    sample_exercises: [
      { id: 1, section: "Fondamentaux Supply Chain", question: "Définissez la chaîne d’approvisionnement et ses composantes.", answer_preview: "Correction attendue : Ensemble des organisations, activités, technologies et ressources impliquées dans la transformation des matières premières jusqu'à la livraison au client final." },
      { id: 75, section: "Gestion des stocks", question: "Expliquez la formule et le rôle du point de commande (seuil de réapprovisionnement).", answer_preview: "Correction attendue : Point de commande = (Consommation journalière × Délai de livraison) + Stock de sécurité. Il déclenche automatiquement la passation d'une nouvelle commande." },
      { id: 213, section: "Indicateurs KPI", question: "Un fournisseur livre 47 commandes à l'heure sur 50. Calculez le taux de service.", answer_preview: "Correction : Taux de service = (47 / 50) × 100 = 94 %." }
    ],
    protected_exercises: [
      { id: 1, section: "Supply Chain", question: "Définissez la chaîne d’approvisionnement (Supply Chain).", answer: "Correction : Réseau coordonné reliant fournisseurs, producteurs, entrepôts, transporteurs et distributeurs pour approvisionner, fabriquer et distribuer des produits aux clients finaux au bon moment, au bon endroit et au coût optimal." },
      { id: 4, section: "Gestion des flux", question: "Distinguez flux physique, flux d’information et flux financier.", answer: "Correction : Le flux physique est la circulation matérielle des marchandises ; le flux d'information pilote et trace les opérations (commandes, expéditions) ; le flux financier correspond aux règlements monétaires." },
      { id: 36, section: "Achats professionnels", question: "Définissez un achat professionnel et ses enjeux.", answer: "Correction : Acquisition de biens ou services répondant aux besoins de l'entreprise avec recherche du meilleur rapport qualité-coût-délai pour maximiser la marge opérationnelle." },
      { id: 41, section: "Approvisionnement", question: "Définissez le délai d’approvisionnement (Lead Time).", answer: "Correction : Temps écoulé entre l'émission du besoin d'achat (ou passation de commande) et la mise à disposition effective de la marchandise contrôlée dans l'entrepôt." },
      { id: 72, section: "Gestion des stocks", question: "Qu’est-ce qu’un stock de sécurité et pourquoi est-il indispensable ?", answer: "Correction : Niveau de stock tampon conservé en permanence pour absorber les aléas de la demande client (pics imprévus) ou les retards de livraison des fournisseurs." },
      { id: 75, section: "Gestion des stocks", question: "Expliquez le calcul du point de commande.", answer: "Correction : Niveau de stock qui déclenche l'ordre d'approvisionnement. Formule : Point de commande = (Consommation moyenne par jour × Délai de livraison en jours) + Stock de sécurité." },
      { id: 79, section: "Valorisation des stocks", question: "Expliquez la méthode FIFO (First In, First Out).", answer: "Correction : Règle de gestion consistant à consommer ou expédier en priorité les articles entrés les premiers en stock afin d'éviter la péremption ou l'obsolescence." },
      { id: 113, section: "Entrepôt", question: "Qu’est-ce que le picking dans un entrepôt ?", answer: "Correction : Opération de prélèvement unitaire des articles stockés sur les étagères ou palettes pour constituer le colis commandé par un client." },
      { id: 114, section: "Entrepôt", question: "Qu’est-ce que le cross-docking ?", answer: "Correction : Technique logistique consistant à transférer les marchandises des quais de déchargement directement vers les quais d'expédition sans mise en stock intermédiaire." },
      { id: 146, section: "Transport", question: "Définissez le transport multimodal et citez un exemple sénégalais.", answer: "Correction : Acheminement d'une marchandise empruntant au moins deux modes de transport successifs sous un contrat unique (ex: navire conteneurisé jusqu'au port de Dakar puis train ou camion vers le Mali)." },
      { id: 154, section: "Distribution", question: "Qu’est-ce que la logistique du dernier kilomètre ?", answer: "Correction : Dernier segment de la livraison entre la plateforme de distribution locale et le destinataire final, représentant souvent plus de 25% du coût global de transport." },
      { id: 206, section: "Calculs logistiques", question: "Une entreprise consomme 120 unités par jour pendant 5 jours. Calculez la consommation hebdomadaire.", answer: "Correction : 120 × 5 = 600 unités par semaine." },
      { id: 209, section: "Calculs logistiques", question: "Un entrepôt traite 900 colis en 6 heures. Calculez le débit horaire moyen.", answer: "Correction : Débit = 900 / 6 = 150 colis par heure." },
      { id: 211, section: "Calculs logistiques", question: "Un transport coûte 750 000 FCFA pour 150 tonnes. Calculez le coût par tonne.", answer: "Correction : 750 000 / 150 = 5 000 FCFA par tonne transportée." },
      { id: 212, section: "Qualité logistique", question: "Une livraison compte 96 colis dont 4 sont endommagés. Calculez le taux d’avarie.", answer: "Correction : Taux d'avarie = (4 / 96) × 100 = 4,17 %." },
      { id: 214, section: "Rotation des stocks", question: "Le stock moyen est de 2 000 unités et la consommation annuelle de 12 000 unités. Calculez le taux de rotation.", answer: "Correction : Taux de rotation = Consommation annuelle / Stock moyen = 12 000 / 2 000 = 6 rotations par an." },
      { id: 262, section: "Systèmes d'information", question: "À quoi sert un logiciel WMS (Warehouse Management System) ?", answer: "Correction : Système informatisé qui gère et optimise l'ensemble des opérations d'un entrepôt : réception, adressage des emplacements, préparation des commandes, inventaires et expéditions." },
      { id: 263, section: "Systèmes d'information", question: "À quoi sert un logiciel TMS (Transport Management System) ?", answer: "Correction : Logiciel dédié à la planification des tournées, à la sélection des transporteurs, au suivi géolocalisé des véhicules et au contrôle des factures de transport." },
      { id: 309, section: "Amélioration continue", question: "Présenter les 5 étapes de la démarche 5S en atelier ou entrepôt.", answer: "Correction : Seiri (Débarrasser), Seiton (Ranger), Seiso (Nettoyer), Seiketsu (Standardiser) et Shitsuke (Pérenniser/Rigueur)." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 112,
    created_at: new Date().toISOString(),
  },

  // 4. CONCOURS MAGISTRATURE SÉNÉGAL (CFJ) — TOME 1
  {
    id: 'annale-magistrature-sn',
    slug: 'concours-magistrature-senegal-cfj-tome-1',
    title: 'Concours Magistrature — Sénégal : Tome 1',
    ministry: 'Ministère de la Justice — Centre de Formation Judiciaire (CFJ)',
    category: 'Magistrature',
    target_corps: 'Auditeurs de Justice, Magistrats du Siège, Magistrats du Parquet',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale Haute Juridiction 2026',
    total_exercises: 320,
    total_pages: 35,
    rating: 4.99,
    reviews_count: 412,
    cover_gradient: 'from-rose-950 via-red-950 to-slate-950',
    cover_image: '/covers/magistrature.jpg',
    accent_color: '#b91c1c',
    badge: 'Justice & Magistrature',
    description: "320 exercices juridiques approfondis avec cas pratiques résolus et corrigés méthodologiques (faits → problème de droit → règle applicable → application d'espèce → conclusion) : droit constitutionnel et institutions de la République, droit civil des obligations et des personnes, droit pénal général et spécial, procédure pénale et libertés, procédure civile et voies de recours, droit administratif et contentieux, droit des affaires OHADA, organisation judiciaire, déontologie et méthodologie + 4 concours blancs.",
    official_reference: "Concours direct d'accès à la Section Magistrature du Centre de Formation Judiciaire (CFJ Dakar) — Ministère de la Justice du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Droit constitutionnel et institutions", count: 32, description: "État de droit, séparation des pouvoirs, hiérarchie des normes, contrôle de constitutionnalité et libertés fondamentales." },
      { title: "2. Droit civil, personnes, famille et obligations", count: 32, description: "Personnalité juridique, validité contractuelle, vices du consentement, responsabilité civile délictuelle/contractuelle et régimes matrimoniaux." },
      { title: "3. Droit pénal général et spécial", count: 32, description: "Légalité criminelle, élément moral/matériel, tentative, complicité, légitime défense, infractions contre les biens (vol, escroquerie) et contre l'État." },
      { title: "4. Procédure pénale et police judiciaire", count: 32, description: "Action publique et civile, opportunité des poursuites, garde à vue, flagrance, information judiciaire, détention provisoire et procès équitable." },
      { title: "5. Procédure civile, commerciale et voies de recours", count: 32, description: "Acte introductif d'instance, compétence matérielle/territoriale, contradictoire, incidents d'instance, appel, pourvoi en cassation et opposition." },
      { title: "6. Droit administratif et contentieux administratif", count: 32, description: "Actes administratifs unilatéraux, service public, responsabilité pour faute de service, recours pour excès de pouvoir et plein contentieux." },
      { title: "7. Droit OHADA, commercial et affaires", count: 32, description: "Actes de commerce, immatriculation au RCCM, sociétés commerciales (SARL, SA), procédures collectives et cessation des paiements." },
      { title: "8. Organisation judiciaire, magistrature et déontologie", count: 32, description: "Dualité siège/parquet, indépendance du juge, secret délibéré, impartialité, récusation, discipline et prévention des conflits d'intérêts." },
      { title: "9. Droit international, droits humains et libertés", count: 32, description: "Traités internationaux, CADHP, garanties du procès pénal, interdiction de la torture et extradition." },
      { title: "10. Méthodologie juridique, dissertation, cas pratique et culture générale", count: 32, description: "Technique du syllogisme juridique, fiche d'arrêt, plan binaire de dissertation et argumentation doctrinale." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Droit constitutionnel et civil", duration: "4h00", questions_count: 8 },
      { title: "Concours blanc 2 — Droit pénal et procédure", duration: "4h00", questions_count: 8 },
      { title: "Concours blanc 3 — Droit administratif et affaires", duration: "4h00", questions_count: 8 },
      { title: "Concours blanc 4 — Épreuve intégrée magistrature", duration: "4h00", questions_count: 8 }
    ],
    sample_exercises: [
      { id: 1, section: "Droit constitutionnel", question: "Définir l’État de droit et expliquer ses principales caractéristiques.", answer_preview: "Correction attendue : Système institutionnel dans lequel la puissance publique est soumise au respect des règles de droit, avec hiérarchie des normes et tribunaux indépendants." },
      { id: 65, section: "Droit pénal", question: "Définir l’infraction et expliciter la distinction tripartite (crime, délit, contravention).", answer_preview: "Correction attendue : Action ou omission violant la loi pénale et sanctionnée par une peine. La distinction repose sur la gravité de la peine encourue." },
      { id: 292, section: "Méthodologie juridique", question: "Construire un syllogisme juridique complet appliqué à une hypothèse de vol.", answer_preview: "Correction attendue : Majeure (règle de droit : art. 364 CP), Mineure (faits qualifiés juridiquement), Conclusion (conséquence juridique applicable)." }
    ],
    protected_exercises: [
      { id: 1, section: "Droit constitutionnel", question: "Définir l’État de droit et expliquer ses principales caractéristiques.", answer: "Correction : Modèle d'organisation étatique où l'autorité publique est strictement assujettie à l'ordre juridique établi. Piliers : primauté de la Constitution, respect des droits fondamentaux, séparation effective des pouvoirs et existence de recours juridictionnels effectifs." },
      { id: 2, section: "Droit constitutionnel", question: "Présenter le principe de séparation des pouvoirs.", answer: "Correction : Théorie classique (Montesquieu) selon laquelle les trois fonctions étatiques (législative, exécutive, juridictionnelle) doivent être attribuées à des organes distincts et équilibrés pour préserver la liberté des citoyens." },
      { id: 9, section: "Contrôle de constitutionnalité", question: "Définir le contrôle de constitutionnalité et ses modalités au Sénégal.", answer: "Correction : Mécanisme juridictionnel confié au Conseil constitutionnel garantissant la conformité des lois et engagements internationaux à la Constitution, par voie d'action a priori ou par exception d'inconstitutionnalité transmise par la Cour suprême." },
      { id: 33, section: "Droit civil", question: "Définir la personnalité juridique et distinguer personne physique et morale.", answer: "Correction : Aptitude juridique à être titulaire de droits et assujetti à des obligations. La personne physique l'acquiert à la naissance viable ; la personne morale par son immatriculation ou déclaration légale." },
      { id: 48, section: "Droit des contrats", question: "Présenter les conditions de validité d’un contrat selon le Code des Obligations Civiles et Commerciales (COCC).", answer: "Correction : 1. Le consentement éclairé et exempt de vices ; 2. La capacité juridique de contracter ; 3. Un objet déterminé et licite ; 4. Une cause licite et morale." },
      { id: 49, section: "Vices du consentement", question: "Identifier les trois principaux vices du consentement en droit civil.", answer: "Correction : L'erreur (méprise sur la substance ou la personne), le dol (manœuvres frauduleuses déterminantes) et la violence (contrainte physique ou morale illégitime)." },
      { id: 54, section: "Responsabilité civile", question: "Présenter les fondements de la responsabilité civile délictuelle.", answer: "Correction : Tout fait quelconque de l'homme qui cause à autrui un dommage oblige celui par la faute duquel il est arrivé à le réparer (faute prouvée, dommage certain et lien de causalité direct)." },
      { id: 65, section: "Droit pénal général", question: "Définir l’infraction et expliciter la distinction tripartite (crime, délit, contravention).", answer: "Correction : Comportement prohibé par la loi pénale sous peine de sanction. La classification tripartite détermine la juridiction compétente (tribunal d'instance, tribunal de grande instance, chambre criminelle), la tentative et la prescription." },
      { id: 68, section: "Principes pénaux", question: "Expliquer le principe de légalité des délits et des peines (Nullum crimen, nulla poena sine lege).", answer: "Correction : Nul ne peut être poursuivi ni condamné pour une action ou omission qui ne constituait pas une infraction d'après la loi en vigueur au moment où elle a été commise." },
      { id: 74, section: "Responsabilité pénale", question: "Différencier auteur, coauteur et complice en droit pénal sénégalais.", answer: "Correction : L'auteur accomplit personnellement les actes matériels constitutifs ; le coauteur agit de concert en réalisant une partie de l'infraction ; le complice facilite ou provoque l'infraction par aide, assistance ou instructions." },
      { id: 98, section: "Procédure pénale", question: "Définir l’action publique et ses modes d'extinction.", answer: "Correction : Action menée au nom de la société par le ministère public pour faire constater une infraction, en établir la culpabilité et appliquer les sanctions. S'éteint par décès, amnistie, prescription ou transaction légale." },
      { id: 104, section: "Enquêtes pénales", question: "Différencier enquête de flagrance et enquête préliminaire.", answer: "Correction : La flagrance (infraction en train de se commettre ou venant de se commettre) confère des pouvoirs de contrainte étendus aux OPJ sous le contrôle direct du Procureur. L'enquête préliminaire requiert en principe l'assentiment des parties." },
      { id: 139, section: "Procédure civile", question: "Expliquer le principe du contradictoire dans le procès civil.", answer: "Correction : Règle fondamentale imposant que chaque partie soit informée de l'instance, mise à même de présenter ses prétentions et de discuter contradictoirement les pièces et arguments de son adversaire." },
      { id: 153, section: "Voies de recours", question: "Différencier juge du fond et juge de cassation.", answer: "Correction : Les juges du fond (tribunaux, cours d'appel) apprécient souverainement les faits et le droit du litige ; la Cour suprême ne réexamine pas les faits mais contrôle uniquement la stricte et exacte application de la loi." },
      { id: 172, section: "Droit administratif", question: "Définir le recours pour excès de pouvoir (REP).", answer: "Correction : Recours contentieux objectif formé devant la Chambre administrative de la Cour suprême tendant à l'annulation d'un acte administratif unilatéral illégal pour incompétence, vice de forme, détournement de pouvoir ou violation de la loi." },
      { id: 195, section: "Droit des affaires", question: "Définir la qualité de commerçant selon l'Acte Uniforme OHADA.", answer: "Correction : Est commerçant celui qui accomplit des actes de commerce par nature et en fait sa profession habituelle à titre indépendant." },
      { id: 228, section: "Organisation judiciaire", question: "Différencier magistrats du siège et magistrats du parquet.", answer: "Correction : Les magistrats du siège (juges) tranchent les litiges, sont inamovibles et indépendants. Les magistrats du parquet (procureurs) représentent le ministère public, défendent l'intérêt général et sont subordonnés hiérarchiquement." },
      { id: 231, section: "Déontologie du magistrat", question: "Expliquer le devoir de réserve et l’obligation d'impartialité du magistrat.", answer: "Correction : Obligation d'adopter une attitude de neutralité stricte, de s'abstenir de toute manifestation politique publique susceptible d'altérer la confiance des justiciables en la justice républicaine." },
      { id: 292, section: "Méthodologie juridique", question: "Construire un syllogisme juridique.", answer: "Correction : Raisonnement déductif en 3 temps : 1. La majeure (énoncé de la règle de droit applicable) ; 2. La mineure (constatation et qualification juridique des faits d'espèce) ; 3. La conclusion (application de la règle aux faits constatés pour déterminer la solution)." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 113,
    created_at: new Date().toISOString(),
  },

  // 5. CONCOURS GREFFE SÉNÉGAL (CFJ) — TOME 1
  {
    id: 'annale-greffe-sn',
    slug: 'concours-greffe-senegal-cfj-tome-1',
    title: 'Concours Greffe — Sénégal : Tome 1',
    ministry: 'Ministère de la Justice — Centre de Formation Judiciaire (CFJ)',
    category: 'Greffe',
    target_corps: 'Greffiers en Chef, Greffiers des Cours et Tribunaux',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Officielle Greffe & Procédures 2026',
    total_exercises: 320,
    total_pages: 35,
    rating: 4.97,
    reviews_count: 318,
    cover_gradient: 'from-indigo-950 via-slate-900 to-slate-950',
    cover_image: '/covers/greffe.jpg',
    accent_color: '#6366f1',
    badge: 'Justice & Greffe',
    description: "320 exercices distincts avec méthodologie judiciaire : droit civil et personnes, procédure civile et voies de recours, droit pénal et procédure pénale, organisation judiciaire et institutions, techniques du greffe et actes judiciaires (plumitif, PV d'audience, cotation de pièces, minutes, expéditions), droit administratif, droit OHADA et RCCM, français juridique, déontologie et logique mathématique + 4 concours blancs.",
    official_reference: "Concours direct d'accès à la Section Greffe du Centre de Formation Judiciaire (CFJ Dakar) — Ministère de la Justice du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Droit civil et personnes", count: 32, description: "État civil, capacité juridique, mariage, filiation, tutelle, validité des actes civils et prescription." },
      { title: "2. Procédure civile et voies de recours", count: 32, description: "Enrôlement, assignation, signification, rôle du greffier dans l'instance, mise en état, jugement par défaut et appel." },
      { title: "3. Droit pénal et procédure pénale", count: 32, description: "Enregistrement des plaintes, dossier pénal, pièces à conviction, répertoires des jugements correctionnels et voies de recours." },
      { title: "4. Organisation judiciaire et institutions", count: 32, description: "Structure des juridictions sénégalaises, Cour suprême, rôle du chef de greffe et circulation administrative des dossiers." },
      { title: "5. Techniques du greffe et actes judiciaires", count: 32, description: "Tenue du plumitif, procès-verbal d'audience, cotation, conservation des minutes, délivrance des expéditions et copies certifiées." },
      { title: "6. Droit administratif et service public", count: 32, description: "Actes administratifs, neutralité du service public de la justice, recours gracieux et conservation des archives." },
      { title: "7. Droit OHADA, commercial et entreprises", count: 32, description: "Tenue du Registre du Commerce et du Crédit Mobilier (RCCM), formalités de constitution de société et sûretés." },
      { title: "8. Procédure, rédaction administrative et français juridique", count: 32, description: "Formulation des actes de greffe, requêtes, bordereaux de transmission, convocations et correspondances officielles." },
      { title: "9. Déontologie, éthique et situations professionnelles", count: 32, description: "Secret professionnel du greffier, probité républicaine, impartialité de l'accueil et gestion des dossiers sensibles." },
      { title: "10. Mathématiques, logique, informatique et organisation", count: 32, description: "Calcul des délais procéduraux, statistiques judiciaires, sécurisation des bases de données et gestion d'audience." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Droit et procédure", duration: "3h30", questions_count: 8 },
      { title: "Concours blanc 2 — Techniques du greffe", duration: "3h30", questions_count: 8 },
      { title: "Concours blanc 3 — Déontologie et rédaction", duration: "3h00", questions_count: 8 },
      { title: "Concours blanc 4 — Épreuve intégrée de greffe", duration: "4h00", questions_count: 8 }
    ],
    sample_exercises: [
      { id: 41, section: "Procédure civile", question: "Décrire le rôle du greffe lors de l’enrôlement d’une affaire.", answer_preview: "Correction attendue : Réception de l'acte introductif, vérification du paiement des droits de consignation, attribution d'un numéro d'ordre au Répertoire Général et inscription sur la feuille d'audience." },
      { id: 129, section: "Techniques du greffe", question: "Définir la mission générale d’un greffier et son rôle d'authentificateur.", answer_preview: "Correction attendue : Le greffier est le garant de la régularité des actes de procédure, consigne les déclarations à l'audience et authentifie les jugements aux côtés du magistrat." },
      { id: 143, section: "Actes judiciaires", question: "Différencier copie simple, copie certifiée conforme et expédition (grosse).", answer_preview: "Correction attendue : Copie simple (information sans sceau) ; Copie certifiée (attestation d'exactitude avec sceau du greffe) ; Expédition revêtue de la formule exécutoire pour signification par huissier." }
    ],
    protected_exercises: [
      { id: 1, section: "Droit civil", question: "Définir la personnalité juridique et distinguer personne physique et personne morale.", answer: "Correction : Aptitude à être sujet de droits et d'obligations. Les personnes physiques sont les êtres humains vivants et viables ; les personnes morales sont des groupements dotés d'une existence juridique propre." },
      { id: 41, section: "Techniques de greffe", question: "Décrire le rôle du greffe lors de l’enrôlement d’une affaire.", answer: "Correction : Enregistrement de la citation ou de l'assignation au Répertoire Général civil ou correctionnel, contrôle de recevabilité matérielle, perception de la consignation légale et constitution de la cote de dossier." },
      { id: 108, section: "Relations judiciaires", question: "Décrire les relations fonctionnelles entre le magistrat et le greffier.", answer: "Correction : Collaboration étroite au prétoire : le greffier assiste obligatoirement le magistrat sous peine de nullité de la décision, tient les notes d'audience et cosigne les minutes des jugements." },
      { id: 129, section: "Statut du greffe", question: "Définir la mission générale d’un greffier.", answer: "Correction : Officier ministériel et fonctionnaire de justice investi du pouvoir d'authentification, responsable de la garde des minutes, des scellés, des registres légaux et de la traçabilité des procédures." },
      { id: 133, section: "Actes judiciaires", question: "Expliquer le rôle du procès-verbal d’audience (ou plumitif).", answer: "Correction : Registre manuscrit ou électronique tenu à l'audience consignant chronologiquement les comparutions, déclarations des parties, plaidoiries des avocats, réquisitions du ministère public et délibérés." },
      { id: 144, section: "Actes judiciaires", question: "Expliquer la différence entre minute et expédition.", answer: "Correction : La minute est l'acte original signé conservé perpétuellement au greffe de la juridiction ; l'expédition est la copie authentifiée délivrée aux parties munie de la formule exécutoire." },
      { id: 148, section: "Tenue des registres", question: "Expliquer le rôle du registre des décisions (Répertoire).", answer: "Correction : Registre légal officiel coté et paraphé retraçant chronologiquement toutes les décisions rendues par la juridiction pour garantir leur conservation et leur consultation publique." },
      { id: 153, section: "Procédures de greffe", question: "Élaborer une checklist de réception d’un dossier judiciaire.", answer: "Correction : 1. Contrôle des pièces obligatoires ; 2. Vérification des identités et adresses ; 3. Constat de la consignation payée ; 4. Numérotation chronologique ; 5. Délivrance du récépissé." },
      { id: 196, section: "Droit commercial", question: "Expliquer le rôle du greffier dans la tenue du RCCM (OHADA).", answer: "Correction : Le greffe reçoit les dossiers de création et modification d'entreprises, vérifie la conformité des statuts, attribue le numéro d'immatriculation RCCM et délivre les extraits K-bis." },
      { id: 257, section: "Déontologie du greffe", question: "Définir le secret professionnel du greffier.", answer: "Correction : Interdiction absolue de divulguer à des tiers le contenu des dossiers en cours, les débats de chambre du conseil et les décisions avant leur prononcé public solennel." },
      { id: 289, section: "Calcul des délais", question: "Calculer un délai franc de 15 jours pour interjeter appel.", answer: "Correction : Le dies a quo (jour de la notification) et le dies ad quem (jour de l'échéance) ne sont pas comptés. Si le dernier jour est férié ou chômé, le délai est prorogé jusqu'au premier jour ouvrable suivant." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 114,
    created_at: new Date().toISOString(),
  },

  // 6. CONCOURS ESP SÉNÉGAL (École Supérieure Polytechnique de Dakar)
  {
    id: 'annale-esp-sn',
    slug: 'concours-esp-dakar-polytechnique-senegal-fascicule-complet',
    title: 'Concours ESP Dakar — Sénégal : École Supérieure Polytechnique (UCAD)',
    ministry: "Ministère de l'Enseignement Supérieur, de la Recherche et de l'Innovation — UCAD",
    category: 'Ingénierie & Polytechnique',
    target_corps: 'Élèves Ingénieurs de Conception, Techniciens Supérieurs et Cadres Scientifiques',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Grandes Écoles d’Ingénieurs',
    total_exercises: 320,
    total_pages: 24,
    rating: 4.98,
    reviews_count: 350,
    cover_gradient: 'from-blue-950 via-indigo-900 to-slate-950',
    cover_image: '/covers/esp.jpg',
    accent_color: '#3b82f6',
    badge: 'Polytechnique Dakar',
    description: "320 exercices distincts sans répétition pour réussir le concours d’entrée à l'École Supérieure Polytechnique de Dakar (ESP - UCAD). Mathématiques approfondies, analyse, probabilités, physique mécanique, électricité, chimie, algorithmique, réseaux et sciences de l’ingénieur + 4 concours blancs complets avec corrigés certifiés.",
    official_reference: "Université Cheikh Anta Diop de Dakar (UCAD) — École Supérieure Polytechnique (ESP Dakar).",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Droit pénal général et spécial", count: 32, description: "Infractions, éléments constitutifs, peines, légitime défense et responsabilité pénale." },
      { title: "2. Procédure pénale et enquêtes", count: 32, description: "Flagrance, enquête préliminaire, garde à vue, perquisition et rédaction de procès-verbaux." },
      { title: "3. Droit constitutionnel et libertés publiques", count: 32, description: "Institutions républicaines, séparation des pouvoirs, maintien de l'ordre et protection des libertés fondamentales." },
      { title: "4. Rédaction et correspondance administrative", count: 32, description: "Rapports de police, fiches de renseignement, synthèses opérationnelles et comptes rendus hiérarchiques." },
      { title: "5. Déontologie et éthique policière", count: 32, description: "Code de déontologie de la Police nationale, usage proportionné de la force, probité et secret professionnel." },
      { title: "6. Culture générale et géopolitique sahélienne", count: 32, description: "Histoire du Sénégal, menaces sécuritaires contemporaines, cybercriminalité et coopération transfrontalière." },
      { title: "7. Psychotechnique et prise de décision rapide", count: 32, description: "Matrices logiques, analyse de données complexes, gestion de l'urgence et raisonnement déductif." },
      { title: "8. Gestion de crise et sécurité publique", count: 32, description: "Maintien de la paix civile, dialogue communautaire, gestion des rassemblements et périmètres de sécurité." },
      { title: "9. Condition physique, rusticité et self-défense", count: 32, description: "Endurance cardio-vasculaire, résistance musculaire, gestes de secours d'urgence et techniques de maîtrise sans arme." },
      { title: "10. Grand oral et mises en situation d'officier", count: 32, description: "Présentation devant le grand jury d'officiers supérieurs, gestion du stress, posture de commandement et cas pratiques d'autorité." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Mathématiques & physique", duration: "3h00", questions_count: 5 },
      { title: "Concours blanc 2 — Chimie & électricité", duration: "3h00", questions_count: 5 },
      { title: "Concours blanc 3 — Informatique & réseaux", duration: "3h00", questions_count: 5 },
      { title: "Concours blanc 4 — Épreuve intégrée ESP", duration: "4h00", questions_count: 5 }
    ],
    sample_exercises: [
      { id: 1, section: "Mathématiques", question: "Résoudre 3x − 7 = 11.", answer_preview: "Correction : 3x = 18 d'où x = 6." },
      { id: 65, section: "Physique", question: "Calculer la vitesse moyenne d'un mobile parcourant 150 m en 12 s.", answer_preview: "Correction : Vitesse v = d / t = 150 / 12 = 12,5 m/s (soit 45 km/h)." },
      { id: 161, section: "Informatique", question: "Écrire l'algorithme calculant le maximum de trois nombres A, B, C.", answer_preview: "Correction : Comparer A et B pour trouver le plus grand Max, puis comparer Max avec C pour déterminer le maximum final." }
    ],
    protected_exercises: [
      { id: 1, section: "Mathématiques", question: "Résoudre 3x − 7 = 11.", answer: "Correction : 3x = 11 + 7 = 18 => x = 18 / 3 = 6." },
      { id: 3, section: "Mathématiques", question: "Résoudre l'équation du second degré x² − 7x + 12 = 0.", answer: "Correction : Discriminant Δ = (−7)² − 4(1)(12) = 49 − 48 = 1. Racines : x1 = (7 − 1)/2 = 3 et x2 = (7 + 1)/2 = 4. S = {3 ; 4}." },
      { id: 26, section: "Mathématiques", question: "Calculer la limite : lim(x→2) (x² − 4) / (x − 2).", answer: "Correction : Forme indéterminée 0/0. On factorise le numérateur : (x − 2)(x + 2) / (x − 2) = x + 2. lim(x→2) (x + 2) = 4." },
      { id: 33, section: "Probabilités & Stats", question: "Calculer la moyenne de la série : 8, 10, 12, 15, 20.", answer: "Correction : Somme = 8 + 10 + 12 + 15 + 20 = 65. Moyenne = 65 / 5 = 13." },
      { id: 65, section: "Physique", question: "Calculer la vitesse moyenne d'un mobile parcourant 150 m en 12 s.", answer: "Correction : v = d / t = 150 / 12 = 12,5 m/s." },
      { id: 66, section: "Physique", question: "Convertir 72 km/h en m/s.", answer: "Correction : 72 / 3,6 = 20 m/s." },
      { id: 74, section: "Énergie mécanique", question: "Calculer l'énergie cinétique d'une masse de 1 000 kg se déplaçant à 20 m/s.", answer: "Correction : Ec = 1/2 m v² = 0,5 × 1 000 × (20)² = 500 × 400 = 200 000 Joules (soit 200 kJ)." },
      { id: 97, section: "Électricité", question: "Calculer le courant traversant une résistance de 12 Ω soumise à 24 V.", answer: "Correction : Loi d'Ohm I = U / R = 24 / 12 = 2 A." },
      { id: 101, section: "Électricité", question: "Calculer la résistance équivalente de deux résistances 10 Ω et 20 Ω en parallèle.", answer: "Correction : 1/Req = 1/10 + 1/20 = 3/20 => Req = 20 / 3 ≈ 6,67 Ω." },
      { id: 129, section: "Chimie", question: "Calculer la masse molaire de l'eau H2O (M(H)=1 g/mol, M(O)=16 g/mol).", answer: "Correction : M(H2O) = 2(1) + 16 = 18 g/mol." },
      { id: 139, section: "Chimie des solutions", question: "Calculer le pH d'une solution d'acide chlorhydrique HCl de concentration C = 10^-3 mol/L.", answer: "Correction : Acide fort, donc pH = −log[H3O+] = −log(10^-3) = 3." },
      { id: 161, section: "Algorithmique", question: "Écrire en pseudo-code l'algorithme d'addition de deux entiers.", answer: "Correction :\nAlgorithme Somme\nVariables a, b, s : Entiers\nDébut\n  Lire(a, b)\n  s ← a + b\n  Afficher(s)\nFin" },
      { id: 181, section: "Bases de données SQL", question: "Écrire une requête SQL sélectionnant tous les étudiants ayant une note supérieure à 12.", answer: "Correction : SELECT * FROM etudiants WHERE note > 12 ORDER BY note DESC;" },
      { id: 196, section: "Réseaux informatiques", question: "Calculer le nombre d'adresses IP utilisables pour des hôtes dans un sous-réseau /24.", answer: "Correction : Un masque /24 laisse 8 bits pour les hôtes. 2^8 = 256 adresses. En excluant l'adresse réseau et l'adresse de diffusion (broadcast), il reste 254 adresses hôtes exploitables." },
      { id: 228, section: "Génie civil", question: "Calculer le volume de béton d'un poteau carré de 0,3 m de côté et 3 m de hauteur.", answer: "Correction : Volume = 0,3 × 0,3 × 3 = 0,27 m³." },
      { id: 258, section: "Automatique", question: "Expliquer le principe d’un système asservi en boucle fermée.", answer: "Correction : Système mesurant en continu la grandeur de sortie pour la comparer à la consigne d'entrée. L'erreur constatée est traitée par un régulateur (ex: PID) pour corriger l'actionneur et maintenir la stabilité." },
      { id: 274, section: "Électrotechnique", question: "Expliquer le principe de fonctionnement d'un moteur asynchrone triphasé.", answer: "Correction : Les courants statoriques triphasés créent un champ magnétique tournant qui induit des courants dans le rotor. La force de Laplace résultante entraîne le rotor en rotation à une vitesse légèrement inférieure à la vitesse de synchronisme (glissement)." },
      { id: 306, section: "Anglais technique", question: "Traduire en français les termes : circuit breaker, pressure sensor, power supply.", answer: "Correction : Circuit breaker = disjoncteur ; Pressure sensor = capteur de pression ; Power supply = alimentation électrique." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 115,
    created_at: new Date().toISOString(),
  }
];
