import { Annale } from './db.js';
import { additionalAnnales } from './newAnnalesData.js';
import { additionalAnnales2 } from './moreAnnalesData.js';
import { police320Exercises, police4Simulations } from './policeExercisesData.js';

const baseAnnales: Annale[] = [
  {
    id: 'annale-police-sn',
    slug: 'concours-police-senegal-fascicule-renforce-tome-1',
    title: 'Concours Police — Sénégal : Fascicule Renforcé Tome 1',
    ministry: "Ministère de l'Intérieur — DGPN",
    category: 'Police',
    target_corps: "Élèves Agents de Police, Sous-Officiers et Officiers de Police",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale Concours 2026',
    total_exercises: 320,
    total_pages: 30,
    rating: 4.95,
    reviews_count: 342,
    cover_gradient: 'from-blue-900 via-sky-800 to-indigo-950',
    cover_image: '/covers/police.jpg',
    accent_color: '#1d4ed8',
    badge: 'Best-Seller National',
    description: "320 exercices originaux corrigés sans répétition, 4 concours blancs complets avec barèmes officiels, préparation physique (Luc-Léger, 100m) et plan d'action intensif sur 30 jours pour intégrer la Police Nationale du Sénégal.",
    official_reference: "DGPN — Épreuves écrites d'admission directe : Français, Mathématiques, Histoire & Géographie du Sénégal, Institutions, Droit public et Déontologie policière.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Français & Rédaction administrative", count: 40, description: "Grammaire, accord, style administratif, syntaxe et vocabulaire." },
      { title: "2. Mathématiques & Raisonnement quantitatif", count: 35, description: "Pourcentages, proportions, vitesse moyenne et calculs pratiques." },
      { title: "3. Histoire du Sénégal et de l'Afrique", count: 30, description: "Repères, décolonisation, 1960, royaumes précoloniaux et Cheikh Anta Diop." },
      { title: "4. Géographie du Sénégal et de l'Afrique", count: 25, description: "Territoire, fleuves, mangroves, Sahel et dynamiques urbaines." },
      { title: "5. Culture générale, citoyenneté et déontologie", count: 25, description: "Valeurs républicaines, intérêt général, probité et service public." },
      { title: "6. Institutions, droit public et organisation administrative", count: 35, description: "Constitution, séparation des pouvoirs, police administrative et judiciaire." },
      { title: "7. Logique et tests psychotechniques", count: 30, description: "Suites numériques, déductions logiques, dominos et classements." },
      { title: "8. Police nationale, sécurité, déontologie et missions", count: 45, description: "Protection des biens et des personnes, discrétion professionnelle, légalité." },
      { title: "9. Mises en situation professionnelles", count: 20, description: "Gestion des conflits, accueil d'usagers, transmission d'ordres." },
      { title: "10. Anglais professionnel", count: 10, description: "Vocabulaire, traduction et compréhension pour agents de sécurité." },
      { title: "11. Préparation physique", count: 10, description: "Gestion de l'endurance, vitesse, récupération et hydratation." },
      { title: "12. Oral et entretien avec le jury", count: 15, description: "Motivation en 60 secondes, gestion du stress, posture et éthique." }
    ],
    exam_simulations: police4Simulations as any,
    sample_exercises: police320Exercises.slice(0, 5).map(e => ({
      id: e.id,
      section: e.section,
      question: e.question,
      answer_preview: e.answer,
    })),
    protected_exercises: police320Exercises,
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-gendarmerie-sn',
    slug: 'concours-gendarmerie-senegal-fascicule-renforce-tome-1',
    title: 'Concours Gendarmerie — Sénégal : Fascicule Renforcé Tome 1',
    ministry: "Ministère des Forces Armées — Haut Commandement",
    category: 'Gendarmerie',
    target_corps: "Élèves Gendarmes, Gendarmes Adjoints et Sous-Officiers",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Officielle 2026',
    total_exercises: 320,
    total_pages: 26,
    rating: 4.98,
    reviews_count: 289,
    cover_gradient: 'from-emerald-900 via-teal-900 to-slate-950',
    cover_image: '/covers/gendarmerie.jpg',
    accent_color: '#059669',
    badge: 'Honneur & Patrie',
    description: "Fascicule officiel renforcé avec 320 exercices distincts, 4 concours blancs complets, préparation aux épreuves physiques (1000m, 100m, corde) et programme d'entraînement militaire sur 30 jours.",
    official_reference: "Ministère des Forces Armées — Concours d'Élève Gendarme : Rédaction, Dictée-questions, Arithmétique, Psychotechnique et Épreuves physiques.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Français, expression & rédaction professionnelle", count: 40, description: "Grammaire, style militaire concis, rapports et syntaxe." },
      { title: "2. Mathématiques & arithmétique de terrain", count: 35, description: "Proportions, vitesses, calculs de remises et consommation." },
      { title: "3. Histoire du Sénégal et des armées africaines", count: 30, description: "Tirailleurs, résistances, frontières et souveraineté nationale." },
      { title: "4. Géographie du Sénégal, frontières et mobilité", count: 25, description: "Axes routiers, corridors régionaux, fleuves et sécurité territoriale." },
      { title: "5. Culture générale, citoyenneté et déontologie", count: 25, description: "Civisme, intégrité, probité et secret professionnel." },
      { title: "6. Institutions, droit public et Gendarmerie nationale", count: 35, description: "Statut militaire, brigades de proximité, tutelles et chaîne de commandement." },
      { title: "7. Logique et tests psychotechniques", count: 30, description: "Raisonnement déductif, analogies, spatial et codage." },
      { title: "8. Gendarmerie nationale, sécurité et discipline", count: 45, description: "Ordre public, proportionnalité de la force, police judiciaire et secours." },
      { title: "9. Mises en situation opérationnelles", count: 20, description: "Contrôles routiers, accueil des victimes, gestion des refus d'obtempérer." },
      { title: "10. Anglais de base pour forces de sécurité", count: 10, description: "Public safety, border control, phrases clés pour patrouilles." },
      { title: "11. Préparation physique militaire", count: 10, description: "Course 1 000 m, 100 m, étirements, récupération active." },
      { title: "12. Oral et motivation devant le jury", count: 15, description: "Devise Honneur et Patrie, sens du sacrifice et esprit de corps." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Équilibré", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 2 — Gendarmerie et droit", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 3 — Logique et situations", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 4 — Simulation finale militaire", duration: "3h00", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 1, section: "Français", question: "Corrigez : « Les candidats doit présenter leurs pièces à temps. »", answer_preview: "Correction : « Les candidats doivent présenter leurs pièces à temps. » Accord sujet-verbe." },
      { id: 156, section: "Institutions Gendarmerie", question: "Quel est le statut général des gendarmes au Sénégal ?", answer_preview: "Correction : Les gendarmes ont le statut militaire (Ministère des Forces Armées)." },
      { id: 307, section: "Oral & Valeurs", question: "Que signifie pour vous la devise « Honneur - Patrie » ?", answer_preview: "Correction : Dévouement suprême envers la Nation, intégrité morale sans faille et respect scrupuleux des institutions républicaines." }
    ],
    protected_exercises: [
      { id: 1, section: "Français", question: "Corrigez : « Les candidats doit présenter leurs pièces à temps. »", answer: "Correction : « Les candidats doivent présenter leurs pièces à temps. » Le sujet pluriel commande « doivent »." },
      { id: 2, section: "Français", question: "Corrigez : « La gendarmerie veille à la sécurité des citoyens et protège les biens. »", answer: "Correction : La phrase est parfaitement correcte." },
      { id: 41, section: "Mathématiques", question: "Un candidat obtient 17 points sur 20. Calculez son pourcentage de réussite.", answer: "Correction : 17/20 × 100 = 85.0 %." },
      { id: 59, section: "Mathématiques", question: "Un trajet mesure 120 km et la vitesse moyenne est 60 km/h. Combien de temps dure le trajet ?", answer: "Correction : Temps = 120 / 60 h = 2 heures (120 minutes)." },
      { id: 76, section: "Histoire", question: "En quelle année le Sénégal accède-t-il à l’indépendance ?", answer: "Correction : 1960 (le 4 avril marquant la fête nationale officielle)." },
      { id: 108, section: "Géographie", question: "Quel fleuve porte le nom du pays et constitue une frontière au nord ?", answer: "Correction : Le fleuve Sénégal." },
      { id: 134, section: "Déontologie", question: "Qu’est-ce que la probité ?", answer: "Correction : L’intégrité et l’honnêteté scrupuleuse dans la conduite personnelle et l'exercice des fonctions publiques." },
      { id: 156, section: "Institutions", question: "Quel est le statut général des gendarmes au Sénégal ?", answer: "Correction : Les personnels de la Gendarmerie nationale ont le statut de militaires des forces armées." },
      { id: 157, section: "Institutions", question: "De quel ministère relève directement le Haut Commandement de la Gendarmerie nationale ?", answer: "Correction : Du Ministère des Forces armées pour l'administration et l'emploi militaire." },
      { id: 158, section: "Institutions", question: "Sous quelle autorité la Gendarmerie exerce-t-elle ses missions de police ?", answer: "Correction : Elle est placée sous l’autorité du Ministère de l’Intérieur et du Ministère de la Justice selon qu'il s'agit de police administrative ou judiciaire." },
      { id: 159, section: "Institutions", question: "Quelles sont deux missions générales de la Gendarmerie nationale ?", answer: "Correction : Veiller à la sûreté publique, maintenir l’ordre et assurer l’exécution des lois et règlements sur toute l'étendue du territoire." },
      { id: 191, section: "Logique", question: "Trouvez le terme manquant : 2, 5, 8, 11, ?", answer: "Correction : 14. La suite progresse par addition constante de 3." },
      { id: 221, section: "Missions & Déontologie", question: "Pourquoi la Gendarmerie est-elle dite force de police à statut militaire au Sénégal ?", answer: "Correction : Parce qu’elle exerce des missions de police de droit commun tout en conservant son organisation, sa discipline et son statut militaire." },
      { id: 246, section: "Opérations", question: "Que signifie la proportionnalité dans une action de sécurité ?", answer: "Correction : L'intensité des moyens et de la force employés doit être strictement nécessaire et proportionnée à la menace ou à la résistance rencontrée." },
      { id: 270, section: "Mise en situation", question: "Deux personnes se disputent violemment dans un espace d’accueil de brigade. Priorité ?", answer: "Correction : Préserver immédiatement la sécurité physique des personnes, séparer sans brutalité, apaiser les tensions et entendre les parties séparément." },
      { id: 307, section: "Oral", question: "Que signifie pour vous « Honneur-Patrie » ?", answer: "Correction : Réponse attendue : sens élevé du sacrifice pour la défense du peuple sénégalais, fidélité aux institutions et exemplarité sous le drapeau national." }
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-douane-sn',
    slug: 'concours-douane-senegal-preparation-intensive-tome-1',
    title: 'Concours Douane — Sénégal : Préparation Intensive Tome 1',
    ministry: "Ministère des Finances et du Budget — DGD",
    category: 'Douane',
    target_corps: "Préposés des Douanes, Contrôleurs et Inspecteurs des Douanes",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition 2026 Conforme Code des Douanes UEMOA/Sénégal',
    total_exercises: 320,
    total_pages: 32,
    rating: 4.96,
    reviews_count: 412,
    cover_gradient: 'from-amber-900 via-stone-800 to-emerald-950',
    cover_image: '/covers/douane.jpg',
    accent_color: '#d97706',
    badge: 'Élite Fiscale',
    description: "320 exercices concrets et corrigés couvrant la fiscalité de porte, le classement tarifaire SH, la valeur en douane, les Incoterms 2020, les procédures de dédouanement et le contrôle a posteriori.",
    official_reference: "Direction Générale des Douanes du Sénégal & Décret n°70-1172 modifié portant statut des personnels des douanes.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Missions, organisation et éthique douanières", count: 32, description: "Fiscalité, protection du tissu économique, facilitation et intégrité." },
      { title: "2. Procédures de dédouanement et contrôle documentaire", count: 32, description: "Déclaration préalable, manifeste, visite et mainlevée." },
      { title: "3. Classement tarifaire, origine et valeur en douane", count: 32, description: "Nomenclature du Système Harmonisé (SH), règles d'origine UEMOA/CEDEAO." },
      { title: "4. Calculs, pourcentages et arithmétique douanière", count: 32, description: "Droits de douane, TVA, prélèvements communautaires et conversions FCFA." },
      { title: "5. Commerce international, logistique et Incoterms", count: 32, description: "FOB, CIF/CAF, connaissements maritimes et gestion portuaire." },
      { title: "6. Institutions, finances publiques et culture générale", count: 32, description: "Recettes de l'État, budget national et intégration sous-régionale." },
      { title: "7. Français, dictée et rédaction administrative", count: 32, description: "Procès-verbal de constat, rapports d'inspection et rigueur lexicale." },
      { title: "8. Logique et psychotechnique douanier", count: 32, description: "Détection des anomalies de flux, suites et analyse de risque." },
      { title: "9. Anglais professionnel maritime et douanier", count: 32, description: "Customs declaration, invoice, bill of lading, clearance." },
      { title: "10. Études de cas, situations de guichet et oral", count: 32, description: "Gestion des fausses déclarations, propositions illicites et entretien." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Fondamentaux douaniers", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 2 — Technique tarifaire et valeur", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 3 — Calculs et logique", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 4 — Mises en situation & cas réels", duration: "3h00", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 1, section: "Missions Douanières", question: "Expliquez la différence entre la mission fiscale et la mission économique de la Douane.", answer_preview: "Correction : La mission fiscale perçoit les droits et taxes pour le budget de l’État ; la mission économique protège et facilite les entreprises locales et le commerce extérieur licite." },
      { id: 67, section: "Valeur en Douane", question: "Qu’est-ce que la valeur en douane ?", answer_preview: "Correction : La valeur déterminée selon les règles de l'OMC (généralement la valeur transactionnelle CAF/CIF) servant d'assiette aux droits de porte." },
      { id: 97, section: "Calculs Douaniers", question: "Une marchandise vaut 2 400 000 FCFA. Un droit de 10 % est appliqué. Calculez le montant du droit.", answer_preview: "Correction : 2 400 000 × 0,10 = 240 000 FCFA." }
    ],
    protected_exercises: [
      { id: 1, section: "Missions Douanières", question: "Expliquez la différence entre la mission fiscale et la mission économique de la Douane.", answer: "Correction : La mission fiscale consiste à recouvrer les taxes et droits de porte pour le Trésor public. La mission économique régule les flux commerciaux, protège les industries naissantes et encourage la fluidité des échanges licites." },
      { id: 6, section: "Procédures", question: "Qu’est-ce qu’un contrôle a posteriori ?", answer: "Correction : Un contrôle réalisé après la délivrance de la mainlevée, en entreprise ou sur pièces comptables, pour vérifier l'exactitude des déclarations passées." },
      { id: 65, section: "Tarif", question: "Pourquoi le classement tarifaire est-il important ?", answer: "Correction : Il attribue le code à 10 chiffres (SH) qui détermine précisément le taux des droits et taxes applicables ainsi que les éventuelles restrictions sanitaires ou phytosanitaires." },
      { id: 111, section: "Conversions & Devises", question: "Une facture est de 7 200 EUR et le taux officiel de conversion est 655 FCFA/EUR. Calculez la valeur en FCFA.", answer: "Correction : 7 200 × 655 = 4 716 000 FCFA." },
      { id: 129, section: "Commerce & Logistique", question: "Définissez un Incoterm.", answer: "Correction : Un terme commercial international normalisé par la Chambre de Commerce Internationale (CCI) fixant la répartition des frais, risques et obligations documentaires entre vendeur et acheteur." },
      { id: 257, section: "Anglais Douanier", question: "Translate: « customs officer » and « customs declaration ».", answer: "Correction : « agent des douanes » et « déclaration en douane »." },
      { id: 290, section: "Étude de Cas", question: "Un opérateur vous propose un avantage financier personnel pour débloquer un conteneur au Port Autonome de Dakar. Que faire ?", answer: "Correction : Rejet catégorique et immédiat de la tentative de corruption, maintien de la marchandise sous contrôle douanier et rédaction d'un rapport circonstancié à l'inspecteur chef de visite." }
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-ena-sn',
    slug: 'concours-ena-senegal-cycle-a-et-b-tome-1',
    title: 'Concours ENA — Sénégal : Cycles A & B Tome 1',
    ministry: "École Nationale d’Administration du Sénégal",
    category: 'ENA',
    target_corps: "Administrateurs Civils, Diplomates, Inspecteurs du Trésor et des Impôts",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale Grands Corps de l’État 2026',
    total_exercises: 320,
    total_pages: 26,
    rating: 4.97,
    reviews_count: 520,
    cover_gradient: 'from-purple-950 via-slate-900 to-indigo-950',
    cover_image: '/covers/ena.jpg',
    accent_color: '#7c3aed',
    badge: 'Haut Commandement Civil',
    description: "Le fascicule de référence pour le concours d'entrée à l'ENA de Dakar. 320 exercices corrigés sur le droit administratif, l'économie du développement, la gestion axée sur les résultats (GAR), la synthèse de documents et l'épreuve orale.",
    official_reference: "Arrêté interministériel fixant les programmes des concours directs et professionnels cycles A et B de l'ENA Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Psychotechnique et raisonnement logique", count: 32, description: "Test éliminatoire de 2h : suites, matrices, logique verbale et temporelle." },
      { title: "2. Culture générale et enjeux contemporains", count: 32, description: "État, Constitution, souveraineté alimentaire, CEDEAO et transitions." },
      { title: "3. Droit public et droit administratif sénégalais", count: 32, description: "Actes unilatéraux, hiérarchie des normes, juge administratif et tutelle." },
      { title: "4. Économie politique et finances publiques", count: 32, description: "PIB, inflation, politique budgétaire, balance commerciale et dette." },
      { title: "5. Gestion publique axée sur les résultats (GAR)", count: 32, description: "Budget-programme, indicateurs SMART, contrôle interne et audit public." },
      { title: "6. Méthodologie du résumé et de la note de synthèse", count: 32, description: "Plans en deux parties, problématisation, transitions et condensation." },
      { title: "7. Français soutenu et rédaction administrative", count: 32, description: "Style officiel républicain, figures d'argumentation et précision terminologique." },
      { title: "8. Connaissance des corps et sections ENA", count: 32, description: "Administration générale, Diplomatie, Impôts & Domaines, Trésor, Travail." },
      { title: "9. Entretien avec le jury et épreuve orale", count: 32, description: "Présentation en 90 secondes, questions pièges, neutralité et déontologie." },
      { title: "10. Études de cas et prise de décision publique", count: 32, description: "Arbitrages budgétaires, gestion de crise et modernisation des services." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Direct Cycle B (Résumé & Dissertation)", duration: "3h00", questions_count: 10 },
      { title: "Concours blanc 2 — Direct Cycle A (Droit & Économie)", duration: "4h00", questions_count: 10 },
      { title: "Concours blanc 3 — Gestion publique & Indicateurs", duration: "3h00", questions_count: 10 },
      { title: "Concours blanc 4 — Grand Oral de Synthèse", duration: "45min", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 33, section: "Culture Générale", question: "Définissez brièvement l’État en droit public.", answer_preview: "Correction : Une organisation politique et juridique souveraine exerçant son autorité sur une population et un territoire délimité." },
      { id: 65, section: "Droit Administratif", question: "Définissez le principe de légalité administrative.", answer_preview: "Correction : L’obligation stricte pour l’administration d'agir conformément aux normes juridiques supérieures en vigueur." },
      { id: 134, section: "Gestion Publique", question: "Qu’est-ce qu’un budget-programme ?", answer_preview: "Correction : Une approche budgétaire moderne (LOLF) reliant les allocations de crédits à des objectifs de performance quantifiés et mesurables." }
    ],
    protected_exercises: [
      { id: 33, section: "Culture Générale", question: "Définissez brièvement l’État.", answer: "Correction : Une organisation politique et juridique exerçant une autorité souveraine sur une population déterminée et à l'intérieur d'un territoire délimité." },
      { id: 35, section: "Institutions", question: "Qu’est-ce que la séparation des pouvoirs ?", answer: "Correction : Un principe fondamental distinguant le pouvoir législatif (voter la loi), exécutif (exécuter la loi) et judiciaire (sanctionner le non-respect du droit)." },
      { id: 65, section: "Droit Administratif", question: "Définissez le principe de légalité administrative.", answer: "Correction : L’administration doit obligatoirement agir dans le respect absolu de la hiérarchie des normes (Constitution, traités, lois, décrets, arrêtés)." },
      { id: 78, section: "Organisation Territoriale", question: "Différence entre déconcentration et décentralisation ?", answer: "Correction : La déconcentration transfère des pouvoirs décisionnels aux représentants locaux de l'État (Gouverneurs, Préfets) ; la décentralisation transfère des compétences à des collectivités locales élues dotées de la personnalité morale (Mairies, Conseils Départementaux)." },
      { id: 97, section: "Économie", question: "Définissez le Produit Intérieur Brut (PIB).", answer: "Correction : La valeur monétaire totale des biens et services finals produits à l'intérieur d'un territoire national donné au cours d'une période donnée (généralement un an)." },
      { id: 132, section: "Management Public", question: "Qu’est-ce qu’un objectif SMART ?", answer: "Correction : Un objectif Spécifique, Mesurable, Atteignable, Réaliste/Pertinent et Temporellement défini." },
      { id: 257, section: "Grand Oral", question: "Comment répondre à la question classique du jury : « Pourquoi voulez-vous intégrer l’ENA ? »", answer: "Correction : Éviter les réponses génériques sur le salaire ou le statut. Articuler sa vocation autour de la participation aux politiques publiques majeures du Sénégal, la modernisation du service aux usagers et le sens de l'État républicain." }
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-ensoa-sn',
    slug: 'concours-ensoa-senegal-fascicule-reconstruit',
    title: 'Concours ENSOA — Sénégal : Fascicule Reconstruit',
    ministry: "Ministère des Forces Armées — Koutal (Kaolack)",
    category: 'ENSOA',
    target_corps: "Sous-Officiers d'Active de l'Armée de Terre, de l'Air et de la Marine",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition 2026 — Devise : Qui Ose Gagne',
    total_exercises: 320,
    total_pages: 26,
    rating: 4.94,
    reviews_count: 275,
    cover_gradient: 'from-amber-950 via-red-950 to-neutral-900',
    cover_image: '/covers/ensoa.jpg',
    accent_color: '#b91c1c',
    badge: 'Qui Ose Gagne',
    description: "Préparation complète au concours direct (niveau BFEM) et professionnel de l'École Nationale des Sous-Officiers d'Active de Koutal. Mathématiques, culture militaire, leadership, secourisme et épreuves physiques.",
    official_reference: "Ministère des Forces Armées du Sénégal — Concours ENSOA Koutal (Kaolack).",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Français, expression et rédaction", count: 32, description: "Grammaire, style clair, compte rendu d'incident et notes de service." },
      { title: "2. Mathématiques et calcul numérique", count: 32, description: "Fractions, équations, calculs d'échelle et moyennes pondérées." },
      { title: "3. Histoire du Sénégal et repères militaires", count: 32, description: "Lat Dior, batailles historiques, 1960 et opérations de maintien de la paix." },
      { title: "4. Géographie, environnement et territoire", count: 32, description: "Régions naturelles, zones frontalières et cartographie militaire de base." },
      { title: "5. Institutions, citoyenneté et culture civique", count: 32, description: "Lois de la République, obéissance légitime et symbole national." },
      { title: "6. Logique, raisonnement et psychotechnique", count: 32, description: "Suites de figures, repérage spatial nord/sud et tests d'attention." },
      { title: "7. Sciences, santé, secourisme et préparation physique", count: 32, description: "Système respiratoire, premiers secours, hydratation et endurance." },
      { title: "8. Culture militaire, ENSOA, discipline et leadership", count: 32, description: "Subordination, commandement direct et esprit d'abnégation." },
      { title: "9. Anglais de base et vocabulaire professionnel", count: 32, description: "Terminologie bilingue pour missions internationales et casques bleus." },
      { title: "10. Situations professionnelles et commandement", count: 32, description: "Gestion des erreurs en patrouille, cohésion et exemplarité." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Écrit général (Français & Logique)", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 2 — Mathématiques et Histoire-Géo", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 3 — Raisonnement & Sciences", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 4 — Leadership & Situations de terrain", duration: "2h00", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 35, section: "Mathématiques", question: "Résolvez l'équation : 3x + 7 = 25.", answer_preview: "Correction : 3x = 25 - 7 = 18, donc x = 6." },
      { id: 225, section: "Culture Militaire", question: "Que signifie le sigle ENSOA et où est implantée l'école au Sénégal ?", answer_preview: "Correction : École Nationale des Sous-Officiers d'Active, implantée à Koutal, dans la région de Kaolack." },
      { id: 256, section: "Tradition Militaire", question: "Quelle est la devise historique de l'ENSOA ?", answer_preview: "Correction : « Qui Ose Gagne », symbole de bravoure et de détermination opérationnelle." }
    ],
    protected_exercises: [
      { id: 35, section: "Mathématiques", question: "Résolvez : 3x + 7 = 25.", answer: "Correction : 3x = 18, d'où x = 6." },
      { id: 36, section: "Mathématiques", question: "Un convoi parcourt 180 km en 3 heures. Quelle est sa vitesse moyenne ?", answer: "Correction : V = d/t = 180 / 3 = 60 km/h." },
      { id: 65, section: "Histoire", question: "Quelle date marque l'indépendance de la République du Sénégal ?", answer: "Correction : Le 4 avril 1960." },
      { id: 76, section: "Histoire", question: "Citez une figure historique emblématique de la résistance à la conquête coloniale au Sénégal.", answer: "Correction : Le Damel du Cayor Lat Dior Ngoné Latyr Diop." },
      { id: 161, section: "Logique", question: "Suite : 2, 4, 8, 16, ?", answer: "Correction : 32 (multiplication par 2 à chaque étape)." },
      { id: 225, section: "Culture Militaire", question: "Que signifie ENSOA ?", answer: "Correction : École Nationale des Sous-Officiers d'Active." },
      { id: 226, section: "Culture Militaire", question: "Où se trouve l'ENSOA sénégalaise ?", answer: "Correction : À Koutal, dans le département et la région de Kaolack." },
      { id: 244, section: "Leadership", question: "Que signifie « donner l'exemple » pour un sous-officier d'active ?", answer: "Correction : Incarner soi-même avec rigueur la discipline, la ponctualité, le respect des consignes et le courage attendus des soldats sous ses ordres." },
      { id: 256, section: "Tradition Militaire", question: "Que rappelle l'expression « Qui Ose Gagne », associée à l'ENSOA ?", answer: "Correction : Elle exprime une idée d'audace, de combativité et de dépassement de soi propre aux sous-officiers sénégalais." }
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-eaux-forets-sn',
    slug: 'concours-eaux-et-forets-senegal-fascicule-reconstruit',
    title: 'Concours Eaux & Forêts — Sénégal : Fascicule Reconstruit',
    ministry: "Ministère de l'Environnement et de la Transition Écologique",
    category: 'Eaux & Forêts',
    target_corps: "Agents Techniques, Contrôleurs et Inspecteurs des Eaux et Forêts",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale Préservation Environnementale 2026',
    total_exercises: 320,
    total_pages: 26,
    rating: 4.93,
    reviews_count: 198,
    cover_gradient: 'from-emerald-950 via-green-900 to-teal-950',
    cover_image: '/covers/eaux_forets.jpg',
    accent_color: '#15803d',
    badge: 'Protection Naturelle',
    description: "320 exercices distincts et corrigés pour le concours des Eaux et Forêts : écologie forestière, sylviculture, feux de brousse, lutte contre la désertification, législation du Code Forestier sénégalais et SIG.",
    official_reference: "Direction des Eaux, Forêts, Chasses et de la Conservation des Sols (DEFCCS) du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Écologie forestière et écosystèmes", count: 32, description: "Habitats, puits de carbone, chaînes trophiques et mangroves." },
      { title: "2. Sylviculture, reboisement et pépinières", count: 32, description: "Semences locales, éclaircies, densité et taux de reprise." },
      { title: "3. Botanique et agroforesterie sahélienne", count: 32, description: "Arbres fertiliaires (Faidherbia albida), haies vives et brise-vents." },
      { title: "4. Faune sauvage et aires protégées", count: 32, description: "Parcs nationaux (Niokolo-Koba, Djoudj), braconnage et inventaires." },
      { title: "5. Sols, eau et lutte contre la désertification", count: 32, description: "Grande Muraille Verte, érosion éolienne et cordons pierreux." },
      { title: "6. Feux de brousse, prévention et pare-feu", count: 32, description: "Triangle du feu, feux précoces vs tardifs, sensibilisation rurale." },
      { title: "7. Législation forestière et Code de l'Environnement", count: 32, description: "Délits forestiers, coupes illicites, droit d'usage et procès-verbaux." },
      { title: "8. Techniques de terrain, cartographie et SIG", count: 32, description: "Boussole, GPS, transects d'inventaire et cubage des peuplements." },
      { title: "9. Français et culture générale environnementale", count: 32, description: "Rédaction de rapports de mission et vocabulaire écologique." },
      { title: "10. Mathématiques appliquées et situations de terrain", count: 32, description: "Surfaces de parcelles en hectares, calculs de densité et constats." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Écologie et gestion forestière", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 2 — Faune, feux et environnement", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 3 — Terrain, droit et données SIG", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 4 — Épreuve générale et professionnelle", duration: "3h00", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 1, section: "Écologie Forestière", question: "Définissez un écosystème forestier.", answer_preview: "Correction : Ensemble dynamique formé par les êtres vivants d'une forêt (biocénose), leur milieu physique (biotope) et les interactions complexes entre eux." },
      { id: 161, section: "Feux de Brousse", question: "Quels sont les trois éléments constituant le triangle du feu ?", answer_preview: "Correction : Un combustible (végétation sèche), un comburant (l’oxygène de l'air) et une source d'énergie ou de chaleur." },
      { id: 228, section: "Cartographie", question: "À l’échelle 1:50 000, 1 cm sur la carte représente quelle distance sur le terrain ?", answer_preview: "Correction : 50 000 cm, soit exactement 500 mètres (0,5 km)." }
    ],
    protected_exercises: [
      { id: 1, section: "Écologie Forestière", question: "Définissez un écosystème forestier.", answer: "Correction : Ensemble formé par les êtres vivants d'une forêt, leur milieu physique (sol, eau, climat) et les interactions symbiotiques entre eux." },
      { id: 5, section: "Écologie", question: "Pourquoi les arbres participent-ils au cycle du carbone ?", answer: "Correction : Ils absorbent le CO2 atmosphérique par photosynthèse et stockent durablement le carbone dans leur biomasse ligneuse et dans l'humus du sol." },
      { id: 44, section: "Sylviculture", question: "Comment calcule-t-on le taux de survie d'une plantation forestière ?", answer: "Correction : Taux de survie = (Nombre de plants vivants / Nombre initial de plants mis en terre) × 100." },
      { id: 161, section: "Feux de Brousse", question: "Qu'est-ce qu'un feu de brousse ?", answer: "Correction : Un incendie non maîtrisé se propageant dans les formations végétales naturelles, savanes ou forêts." },
      { id: 164, section: "Prévention Feux", question: "Qu'est-ce qu'une bande pare-feu ?", answer: "Correction : Une bande de terrain débroussaillée et nettoyée de tout combustible sur une largeur déterminée, destinée à stopper ou ralentir l'avancée des flammes." },
      { id: 200, section: "Législation", question: "Qu'est-ce qu'un procès-verbal dressé par un agent des Eaux et Forêts ?", answer: "Correction : Un acte juridique solennel constatant matériellement une infraction forestière ou environnementale, faisant foi jusqu'à preuve du contraire devant les juridictions répressives." },
      { id: 229, section: "SIG & Terrain", question: "À l'échelle 1:50 000, 1 cm sur la carte représente combien sur le terrain ?", answer: "Correction : 50 000 cm = 500 mètres." }
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-inseps-sn',
    slug: 'concours-inseps-senegal-tome-1-exercices-corriges',
    title: 'Concours INSEPS — Sénégal : Tome 1 Exercices Corrigés',
    ministry: "Université Cheikh Anta Diop de Dakar (UCAD) — INSEPS",
    category: 'INSEPS',
    target_corps: "Professeurs d'EPS, Managers du Sport et Éducateurs Sportifs",
    price: 2000,
    currency: 'XOF',
    edition: 'Édition 2026 Conforme aux Tests d’Admission UCAD',
    total_exercises: 320,
    total_pages: 45,
    rating: 4.91,
    reviews_count: 215,
    cover_gradient: 'from-orange-950 via-amber-900 to-stone-900',
    cover_image: '/covers/inseps.jpg',
    accent_color: '#ea580c',
    badge: 'Sport & Didactique',
    description: "Guide complet pour réussir les épreuves d'admission de l'INSEPS (STAPS-JL EPS) : biologie humaine, physiologie de l'effort, entraînement, test Luc-Léger / navette, quintuple saut et pédagogie sportive.",
    official_reference: "Institut National Supérieur de l'Éducation Populaire et du Sport (INSEPS) — UCAD Dakar.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Français : compréhension, grammaire et expression", count: 45, description: "Textes d'actualité sportive, syntaxe et dissertation." },
      { title: "2. Biologie humaine générale", count: 55, description: "Cellule, systèmes cardiovasculaire et respiratoire, homéostasie." },
      { title: "3. Anatomie et physiologie de l'effort", count: 40, description: "Muscles, articulations, filières énergétiques (aérobie, anaérobie)." },
      { title: "4. Sciences du sport et entraînement", count: 35, description: "Volume, intensité, surcharge progressive et planification." },
      { title: "5. EPS : pédagogie et didactique", count: 25, description: "Objectifs opérationnels, critères d'évaluation et consignes de sécurité." },
      { title: "6. Culture générale, Sénégal, jeunesse et sport", count: 25, description: "Place du sport au Sénégal, fair-play et citoyenneté active." },
      { title: "7. Logique et psychotechnique", count: 25, description: "Suites mathématiques, proportions et calcul mental rapide." },
      { title: "8. Anglais appliqué aux sciences du sport", count: 15, description: "Vocabulaire athlétique, traductions médicales simples." },
      { title: "9. Tests physiques et préparation pratique", count: 30, description: "Test de Luc-Léger, 100m, quintuple saut, gainage et souplesse." },
      { title: "10. Oral, entretien et mises en situation", count: 25, description: "Motivation, projet d'études STAPS et réaction aux litiges d'élèves." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — EPS & Biologie de l'effort", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 2 — Sciences anatomiques et entraînement", duration: "2h30", questions_count: 10 },
      { title: "Concours blanc 3 — Pédagogie de terrain", duration: "2h00", questions_count: 10 },
      { title: "Concours blanc 4 — Simulation finale & Grand Entretien", duration: "3h00", questions_count: 10 }
    ],
    sample_exercises: [
      { id: 1, section: "Biologie Humaine", question: "Expliquez le rôle du noyau, de la membrane plasmique et des mitochondries.", answer_preview: "Correction : Le noyau stocke l’information génétique (ADN) ; la membrane contrôle les échanges cellulaires ; les mitochondries sont les centrales énergétiques produisant l’ATP." },
      { id: 4, section: "Physiologie", question: "Décrivez le trajet de l'oxygène depuis l'air inspiré jusqu'à la cellule musculaire.", answer_preview: "Correction : Alvéoles pulmonaires -> diffusion dans le sang -> liaison à l'hémoglobine -> pompage cardiaque ventricule gauche -> artérioles -> diffusion dans le myocyte." },
      { id: 297, section: "Tests Physiques", question: "Un candidat court 1 000 m en 5 minutes. Quelle est sa vitesse moyenne en km/h ?", answer_preview: "Correction : 5 min = 1/12 d'heure ; 1 km / (1/12 h) = 12 km/h." }
    ],
    protected_exercises: [
      { id: 1, section: "Biologie Humaine", question: "Expliquez le rôle du noyau, de la membrane plasmique et des mitochondries.", answer: "Correction : Le noyau renferme l’ADN régissant les synthèses cellulaires ; la membrane plasmique régule sélectivement les flux ioniques et moléculaires ; les mitochondries synthétisent l’ATP par phosphorylation oxydative." },
      { id: 3, section: "Anatomie de l'Effort", question: "Distinguez contraction concentrique et contraction excentrique.", answer: "Correction : Contraction concentrique : les fibres musculaires se raccourcissent en développant de la force (ex: montée en développé couché). Contraction excentrique : le muscle développe une tension tout en s'allongeant pour freiner une charge (ex: descente contrôlée)." },
      { id: 5, section: "Physiologie", question: "Pourquoi la fréquence cardiaque augmente-t-elle brutalement pendant un sprint ?", answer: "Correction : Pour augmenter le débit cardiaque (DC = FC × VES) et acheminer massivement l'oxygène et le glucose vers les fibres musculaires actives tout en éliminant les protons et métabolites." },
      { id: 296, section: "Entraînement", question: "Pourquoi un échauffement progressif est-il impératif avant un test de vitesse ?", answer: "Correction : Il élève la température centrale et musculaire, diminue la viscosité articulaire, améliore la vitesse de conduction nerveuse et prévient les déchirures musculo-tendineuses." },
      { id: 297, section: "Calcul Sportif", question: "Un candidat court 1 000 m en 5 min. Quelle est sa vitesse moyenne en km/h ?", answer: "Correction : 5 min = 300 secondes = 1/12 h. Vitesse = 1 / (1/12) = 12 km/h." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 106,
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-fastef-sn',
    slug: 'concours-fastef-senegal-fascicule-complet',
    title: 'Concours FASTEF — Sénégal : Fascicule Complet',
    ministry: "Ministère de l'Enseignement supérieur — UCAD FASTEF",
    category: 'FASTEF',
    target_corps: 'Professeurs de Collège et Lycée (CAES, CAPES, PES)',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Spéciale Concours 2026',
    total_exercises: 320,
    total_pages: 23,
    rating: 4.96,
    reviews_count: 278,
    cover_gradient: 'from-amber-950 via-yellow-900 to-slate-950',
    cover_image: '/covers/fastef.jpg',
    accent_color: '#d97706',
    badge: 'Enseignement Secondaire',
    description: "320 exercices distincts corrigés sans doublons répartis en 10 domaines d'expertise, 4 concours blancs complets et plan intensif sur 30 jours pour réussir le concours de la Faculté des Sciences et Technologies de l’Éducation et de la Formation (FASTEF).",
    official_reference: "FASTEF — UCAD Dakar : Modalités officielles d'admission aux formations pédagogiques (CAES, CAPES, PES).",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Pédagogie et didactique", count: 32, description: "Objectifs opérationnels, évaluation diagnostique/formative, remédiation, étayage et différenciation." },
      { title: "2. Français et expression", count: 32, description: "Syntaxe, accords COD, transitions argumentatives, résumé, méthode de dissertation et connecteurs." },
      { title: "3. Histoire, géographie et Sénégal", count: 32, description: "Sahel, aménagement de Dakar, littoral, désertification, transition démographique et gestion de l'eau." },
      { title: "4. Mathématiques et sciences physiques", count: 32, description: "Équations, pourcentages, géométrie, vitesse moyenne, électricité, énergie et chimie." },
      { title: "5. SVT, santé et environnement", count: 32, description: "Photosynthèse, respiration cellulaire, immunité innée/adaptative, écosystèmes et écologie sahélienne." },
      { title: "6. Anglais et communication", count: 32, description: "Grammaire, vocabulaire professionnel, traduction, gestion de classe et formulations orales." },
      { title: "7. Psychologie, inclusion et sociologie", count: 32, description: "Motivation intrinsèque, charge cognitive, estime de soi, inclusion scolaire et gestion de classe." },
      { title: "8. Culture générale, institutions et éducation", count: 32, description: "Institutions républicaines, décentralisation, éthique enseignante et politiques éducatives du Sénégal." },
      { title: "9. Numérique, informatique et méthodologie", count: 32, description: "Outils TICE, plateformes LMS, sécurité des données, algorithmique et recherche documentaire." },
      { title: "10. Concours, oral et situations professionnelles", count: 32, description: "Gestion du temps d'épreuve, oral devant le jury, résolution de conflits et déontologie." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Pédagogie et français", duration: "3h00", questions_count: 5 },
      { title: "Concours blanc 2 — Sciences et géographie", duration: "2h30", questions_count: 5 },
      { title: "Concours blanc 3 — Éducation et numérique", duration: "2h00", questions_count: 5 },
      { title: "Concours blanc 4 — Oral et situations professionnelles", duration: "2h00", questions_count: 5 }
    ],
    sample_exercises: [
      { id: 1, section: "Pédagogie et didactique", question: "Définissez l’objectif pédagogique.", answer_preview: "Correction : Résultat observable attendu." },
      { id: 33, section: "Français et expression", question: "Corrigez : « Les candidats que j’ai vu ».", answer_preview: "Correction : « Les candidats que j’ai vus ». Le COD « que » (mis pour les candidats) placé avant le verbe impose l'accord." },
      { id: 65, section: "Histoire & Géographie", question: "Définissez le Sahel.", answer_preview: "Correction : Zone de transition semi-aride au sud du Sahara." }
    ],
    protected_exercises: [
      { id: 1, section: "Pédagogie et didactique", question: "Définissez l’objectif pédagogique.", answer: "Correction : Résultat observable attendu." },
      { id: 2, section: "Pédagogie et didactique", question: "Distinguez objectif et activité.", answer: "Correction : L’objectif décrit le résultat; l’activité est la tâche." },
      { id: 3, section: "Pédagogie et didactique", question: "Définissez l’évaluation diagnostique.", answer: "Correction : Évaluation avant apprentissage pour repérer les acquis." },
      { id: 4, section: "Pédagogie et didactique", question: "Définissez l’évaluation formative.", answer: "Correction : Évaluation pendant l’apprentissage pour réguler." },
      { id: 6, section: "Pédagogie et didactique", question: "Expliquez l’étayage.", answer: "Correction : Aide temporaire retirée progressivement." },
      { id: 7, section: "Pédagogie et didactique", question: "Définissez la différenciation pédagogique.", answer: "Correction : Adaptation aux différences entre apprenants." },
      { id: 10, section: "Pédagogie et didactique", question: "Définissez compétence.", answer: "Correction : Mobilisation de ressources pour agir efficacement." },
      { id: 12, section: "Pédagogie et didactique", question: "Qu’est-ce qu’une situation-problème?", answer: "Correction : Situation nécessitant recherche et mobilisation de ressources." },
      { id: 33, section: "Français et expression", question: "Corrigez : « Les candidats que j’ai vu ».", answer: "Correction : Les candidats que j’ai vus." },
      { id: 38, section: "Français et expression", question: "Voix passive : « Le jury corrige les copies ».", answer: "Correction : Les copies sont corrigées par le jury." },
      { id: 47, section: "Français et expression", question: "Corrigez « malgré qu’il soit absent ».", answer: "Correction : Bien qu’il soit absent / malgré son absence." },
      { id: 53, section: "Français et expression", question: "Contenu d’une introduction de dissertation?", answer: "Correction : Amorce, définitions, problématique, plan." },
      { id: 65, section: "Histoire et géographie", question: "Définissez le Sahel.", answer: "Correction : Zone de transition semi-aride au sud du Sahara." },
      { id: 66, section: "Histoire et géographie", question: "Pourquoi Dakar est-elle un pôle majeur?", answer: "Correction : Concentration administrative, économique, portuaire et universitaire." },
      { id: 72, section: "Histoire et géographie", question: "Pourquoi protéger les mangroves?", answer: "Correction : Protection côtière, biodiversité et ressources." },
      { id: 87, section: "Histoire et géographie", question: "Définissez développement durable.", answer: "Correction : Répondre aux besoins présents sans compromettre l’avenir." },
      { id: 97, section: "Mathématiques", question: "Résolvez 3x+7=25.", answer: "Correction : x=6." },
      { id: 98, section: "Mathématiques", question: "21 filles sur 36 : pourcentage?", answer: "Correction : 58,33 %." },
      { id: 102, section: "Physique", question: "180 km en 3 h : vitesse?", answer: "Correction : 60 km/h." },
      { id: 113, section: "Physique", question: "U=12V et R=4Ω : I?", answer: "Correction : 3A (Loi d'Ohm : I = U / R = 12 / 4 = 3 A)." },
      { id: 129, section: "SVT", question: "Rôle des globules rouges?", answer: "Correction : Transport de l’oxygène grâce à l'hémoglobine." },
      { id: 130, section: "SVT", question: "Lieu de la photosynthèse?", answer: "Correction : Chloroplastes." },
      { id: 161, section: "Anglais", question: "Translate: The teacher checks the homework every morning.", answer: "Correction : Le professeur vérifie les devoirs chaque matin." },
      { id: 194, section: "Psychologie", question: "Définissez motivation intrinsèque.", answer: "Correction : Engagement lié à l’intérêt de l’activité elle-même." },
      { id: 227, section: "Culture générale", question: "Définissez Constitution.", answer: "Correction : Texte fondamental des institutions et des droits républicains." },
      { id: 260, section: "Numérique", question: "Définissez authentification à deux facteurs.", answer: "Correction : Deux preuves d’identité distinctes pour sécuriser l'accès." },
      { id: 294, section: "Oral & Concours", question: "Comment répondre à « présentez-vous »?", answer: "Correction : Présenter parcours, compétences, motivation et projet professionnel." },
      { id: 320, section: "Oral & Concours", question: "Attitude le jour du concours?", answer: "Correction : Respecter les consignes, gérer son temps et rester concentré." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 107,
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-crem-sn',
    slug: 'concours-crem-senegal-fascicule-complet',
    title: 'Concours CREM — Sénégal : Fascicule Complet de Préparation',
    ministry: "Ministère de l'Éducation nationale — CRFPE",
    category: 'CREM',
    target_corps: 'Élèves-Maîtres (Options Français et Arabe) — Enseignement élémentaire',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition 2026 CRFPE — Conforme Arrêté Ministériel',
    total_exercises: 320,
    total_pages: 23,
    rating: 4.97,
    reviews_count: 312,
    cover_gradient: 'from-teal-950 via-emerald-900 to-slate-950',
    cover_image: '/covers/crem.jpg',
    accent_color: '#0d9488',
    badge: 'Élèves-Maîtres CRFPE',
    description: "320 exercices distincts et corrigés pour le CREM : pédagogie, psychologie de l'enfant, didactique du français et mathématiques, sciences, inclusion scolaire, gestion de l'école primaire et 4 concours blancs complets.",
    official_reference: "Ministère de l’Éducation nationale — Concours de Recrutement des Élèves-Maîtres (CREM) dans les Centres Régionaux de Formation des Personnels de l’Éducation.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Pédagogie, psychologie de l’apprentissage et didactique", count: 32, description: "Compétence professionnelle, progression annuelle, situation-problème, remédiation et différenciation." },
      { title: "2. Français, expression et communication", count: 32, description: "Accords participes passés, tournures actives/passives, connecteurs logiques, dissertation et registres." },
      { title: "3. Mathématiques et raisonnement", count: 32, description: "Arithmétique, fractions, pourcentages, géométrie (aires/périmètres), probabilités et statistiques." },
      { title: "4. Sciences, environnement et santé de l’enfant", count: 32, description: "Organes vitaux, photosynthèse, nutrition équilibrée, hygiène, cycle de l'eau et premiers secours." },
      { title: "5. Histoire, géographie et culture générale", count: 32, description: "Sénégal, Dakar, Sahel, ressources en eau, citoyenneté, développement durable et esprit critique." },
      { title: "6. Psychologie de l’enfant et développement", count: 32, description: "Développement cognitif, mémoire de travail, motivation, socialisation, estime de soi et gestion des conflits." },
      { title: "7. Sciences de l’éducation, inclusion et vie scolaire", count: 32, description: "Climat scolaire, règles de classe, prévention du harcèlement, projet d'école et partenariat avec les parents." },
      { title: "8. Culture générale, citoyenneté et santé scolaire", count: 32, description: "Service public, égalité des chances, vérification de l'information, secourisme et santé mentale." },
      { title: "9. Méthodologie du concours, français pratique et situations professionnelles", count: 32, description: "Gestion du temps de l'épreuve, oral de motivation, analyse des consignes et entretien avec le jury." },
      { title: "10. Organisation de l’école, administration et profession enseignante", count: 32, description: "Réunions pédagogiques, éthique professionnelle, suivi des élèves, sorties scolaires et développement continu." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Pédagogie et français", duration: "3h00", questions_count: 5 },
      { title: "Concours blanc 2 — Sciences et géographie", duration: "2h30", questions_count: 5 },
      { title: "Concours blanc 3 — Éducation et numérique", duration: "2h00", questions_count: 5 },
      { title: "Concours blanc 4 — Oral et situations professionnelles", duration: "2h00", questions_count: 5 }
    ],
    sample_exercises: [
      { id: 1, section: "Pédagogie & Didactique", question: "Définissez une compétence professionnelle de l’enseignant.", answer_preview: "Correction : Capacité à mobiliser des savoirs, savoir-faire et attitudes pour agir efficacement en situation." },
      { id: 33, section: "Français & Expression", question: "Corrigez : « Les élèves que j’ai rencontré ».", answer_preview: "Correction : « Les élèves que j’ai rencontrés ». Le COD « que » (antécédent : les élèves) précède le verbe, imposant l'accord." },
      { id: 65, section: "Mathématiques", question: "Résolvez 4x+5=29.", answer_preview: "Correction : 4x = 24 => x = 6." }
    ],
    protected_exercises: [
      { id: 1, section: "Pédagogie & Didactique", question: "Définissez une compétence professionnelle de l’enseignant.", answer: "Correction : Capacité à mobiliser des savoirs, savoir-faire et attitudes pour agir efficacement en situation." },
      { id: 2, section: "Pédagogie & Didactique", question: "Distinguez pédagogie et didactique.", answer: "Correction : La pédagogie concerne la relation et les conditions d’apprentissage; la didactique porte sur l’enseignement des savoirs spécifiques." },
      { id: 3, section: "Pédagogie & Didactique", question: "Qu’est-ce qu’un objectif opérationnel?", answer: "Correction : Un résultat formulé de manière observable et vérifiable." },
      { id: 8, section: "Pédagogie & Didactique", question: "Quel est le rôle d’une évaluation formative?", answer: "Correction : Fournir des informations pendant l’apprentissage afin d’ajuster l’enseignement." },
      { id: 14, section: "Pédagogie & Didactique", question: "Définissez différenciation pédagogique.", answer: "Correction : Adaptation des démarches, supports, aides ou niveaux de guidage selon les besoins." },
      { id: 17, section: "Pédagogie & Didactique", question: "Définissez métacognition.", answer: "Correction : Capacité à réfléchir sur ses connaissances, stratégies et processus d’apprentissage." },
      { id: 33, section: "Français", question: "Corrigez : « Les élèves que j’ai rencontré ».", answer: "Correction : Les élèves que j’ai rencontrés." },
      { id: 38, section: "Français", question: "Mettez à la voix passive : « Le maître explique la règle ».", answer: "Correction : La règle est expliquée par le maître." },
      { id: 41, section: "Français", question: "Qu’est-ce qu’une problématique?", answer: "Correction : Question directrice précise qui organise une réflexion." },
      { id: 56, section: "Français", question: "Corrigez : « Malgré qu’il soit absent ».", answer: "Correction : On peut écrire « bien qu’il soit absent » ou « malgré son absence »." },
      { id: 65, section: "Mathématiques", question: "Résolvez 4x+5=29.", answer: "Correction : x=6." },
      { id: 66, section: "Mathématiques", question: "Calculez 18 % de 250.", answer: "Correction : 45." },
      { id: 67, section: "Mathématiques", question: "Une classe compte 32 élèves dont 20 filles. Quel pourcentage de filles?", answer: "Correction : (20 / 32) × 100 = 62,5 %." },
      { id: 76, section: "Mathématiques", question: "Aire d’un rectangle de 12 m sur 7 m?", answer: "Correction : 12 × 7 = 84 m²." },
      { id: 95, section: "Mathématiques", question: "Un triangle rectangle a des côtés 6 et 8. Hypoténuse?", answer: "Correction : √(6² + 8²) = √(36 + 64) = √100 = 10." },
      { id: 97, section: "Sciences", question: "Rôle principal du cœur?", answer: "Correction : Propulser le sang dans la circulation sanguine générale et pulmonaire." },
      { id: 110, section: "Sciences", question: "Pourquoi le sommeil est-il important chez l’enfant?", answer: "Correction : Il contribue à la croissance, récupération et consolidation des apprentissages." },
      { id: 120, section: "Sciences", question: "Définissez photosynthèse.", answer: "Correction : Processus par lequel les végétaux chlorophylliens produisent de la matière organique grâce à la lumière." },
      { id: 129, section: "Histoire-Géo", question: "Définissez le Sahel.", answer: "Correction : Bande de transition semi-aride au sud du Sahara." },
      { id: 161, section: "Psychologie", question: "Définissez développement cognitif.", answer: "Correction : Évolution des capacités de perception, mémoire, raisonnement et résolution de problèmes." },
      { id: 199, section: "Vie scolaire", question: "Qu’est-ce que le harcèlement scolaire?", answer: "Correction : Répétition de comportements hostiles ou humiliants créant un déséquilibre et une souffrance." },
      { id: 226, section: "Citoyenneté", question: "Pourquoi l’école joue-t-elle un rôle civique?", answer: "Correction : Elle transmet connaissances, règles communes et capacités de participation citoyenne." },
      { id: 257, section: "Méthodologie", question: "Comment lire un sujet de concours efficacement?", answer: "Correction : Identifier consigne, verbes d’action, limites du sujet et critères implicites." },
      { id: 282, section: "Méthodologie", question: "Comment répondre « pourquoi le CREM? »?", answer: "Correction : Relier motivation pour l’enseignement, service éducatif républicain et projet professionnel." },
      { id: 320, section: "Profession", question: "Comment fixer un objectif de développement professionnel?", answer: "Correction : Le rendre précis, mesurable, réaliste et associé à une échéance." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 108,
    created_at: new Date().toISOString(),
  },
  {
    id: 'annale-endss-sn',
    slug: 'concours-endss-senegal-fascicule-complet',
    title: 'Concours ENDSS — Sénégal : Fascicule Complet de Préparation',
    ministry: "Ministère de la Santé et de l'Action Sociale — ENDSS",
    category: 'ENDSS',
    target_corps: 'Infirmiers d’État, Sages-Femmes d’État, Techniciens de Santé',
    price: 2000,
    currency: 'XOF',
    edition: 'Édition Officielle Santé & Paramédical 2026',
    total_exercises: 320,
    total_pages: 21,
    rating: 4.98,
    reviews_count: 364,
    cover_gradient: 'from-rose-950 via-red-900 to-slate-950',
    cover_image: '/covers/endss.jpg',
    accent_color: '#e11d48',
    badge: 'Santé & Paramédical',
    description: "320 exercices originaux et corrigés couvrant tout le programme du concours d'entrée à l'ENDSS : anatomie, physiologie, biologie, sémiologie, hygiène/asepsie, pharmacologie et calculs de doses, santé publique et 4 concours blancs.",
    official_reference: "École Nationale de Développement Sanitaire et Social (ENDSS Dakar) — Ministère de la Santé et de l'Action Sociale du Sénégal.",
    study_plan_days: 30,
    summary_sections: [
      { title: "1. Anatomie et physiologie", count: 32, description: "Appareil digestif, hémodynamique, reins/ADH, régulation cardiaque, système nerveux et endocrinien." },
      { title: "2. Biologie, microbiologie et immunologie", count: 31, description: "Bactéries Gram, paludisme/anophèle, réaction inflammatoire, immunité innée/adaptative et antibiogramme." },
      { title: "3. Pathologies, sémiologie et soins", count: 31, description: "Détresse respiratoire, état de choc, AVC, pneumonie, appendicite et surveillance des paramètres vitaux." },
      { title: "4. Hygiène, asepsie, prévention des infections", count: 31, description: "Cinq moments de l'hygiène des mains, déchets biomédicaux, stérilisation, désinfection et infections nosocomiales." },
      { title: "5. Pharmacologie et calculs de doses", count: 31, description: "Calculs de débit de perfusion, conversion de milligrammes, 5 vérifications et tolérance médicamenteuse." },
      { title: "6. Santé publique, épidémiologie et prévention", count: 32, description: "Incidence/prévalence, prévention primaire/secondaire, choléra, santé maternelle et vaccination." },
      { title: "7. Mathématiques, statistiques et raisonnement", count: 31, description: "Moyennes, proportions, pourcentages, taux d'attaque, fréquences et échantillonnage." },
      { title: "8. Français, communication et rédaction professionnelle", count: 32, description: "Transmissions écrites ciblées, relation d'aide avec patient anxieux, secret professionnel et synthèse." },
      { title: "9. Situations professionnelles, éthique et organisation des soins", count: 32, description: "Consentement éclairé, prévention des chutes et escarres, gestion des urgences et travail d'équipe." },
      { title: "10. Urgences, pédiatrie, santé maternelle et informatique de santé", count: 37, description: "Déshydratation infantile, surveillance post-partum, allaitement maternel et traçabilité des données de santé." }
    ],
    exam_simulations: [
      { title: "Concours blanc 1 — Pédagogie et français", duration: "3h00", questions_count: 5 },
      { title: "Concours blanc 2 — Sciences et géographie", duration: "2h30", questions_count: 5 },
      { title: "Concours blanc 3 — Éducation et numérique", duration: "2h00", questions_count: 5 },
      { title: "Concours blanc 4 — Oral et situations professionnelles", duration: "2h00", questions_count: 5 }
    ],
    sample_exercises: [
      { id: 1, section: "Anatomie et physiologie", question: "Décrire les principaux segments de l’appareil digestif et préciser le rôle fonctionnel de chacun.", answer_preview: "Correction attendue : Bouche, pharynx, œsophage, estomac, intestin grêle, côlon et rectum : ingestion, digestion mécanique/chimique, absorption des nutriments et excrétion." },
      { id: 33, section: "Microbiologie & Immunologie", question: "Différencier bactéries, virus, champignons et parasites sur le plan biologique.", answer_preview: "Correction attendue : Bactéries (procaryotes autonomes), virus (parasites intracellulaires stricts sans métabolisme propre), champignons (eucaryotes unicellulaires ou filamenteux), parasites (protozoaires ou helminthes)." },
      { id: 132, section: "Pharmacologie & Doses", question: "Calculer le volume à administrer si 500 mg sont disponibles dans 5 mL et que la prescription est de 250 mg.", answer_preview: "Correction : 250 mg × (5 mL / 500 mg) = 2,5 mL." }
    ],
    protected_exercises: [
      { id: 1, section: "Anatomie et physiologie", question: "Décrire les principaux segments de l’appareil digestif et préciser le rôle fonctionnel de chacun.", answer: "Correction attendue : Bouche, pharynx, œsophage, estomac, intestin grêle, côlon et rectum : ingestion, digestion mécanique/chimique, absorption des nutriments et excrétion." },
      { id: 3, section: "Anatomie et physiologie", question: "Expliquer le rôle du foie dans le métabolisme des glucides, lipides et protéines.", answer: "Correction attendue : Rôle de stockage sous forme de glycogène, néoglucogenèse, synthèse des protéines plasmatiques (albumine) et production de la bile pour l'émulsion des lipides." },
      { id: 4, section: "Anatomie et physiologie", question: "Décrire la circulation sanguine pulmonaire et la circulation systémique.", answer: "Correction attendue : La petite circulation (pulmonaire) assure l'oxygénation du sang via l'artère pulmonaire et les poumons ; la grande circulation (systémique) distribue l'oxygène aux organes via l'aorte." },
      { id: 10, section: "Anatomie et physiologie", question: "Décrire le rôle de l’ADH dans la régulation hydrique.", answer: "Correction attendue : L'hormone antidiurétique (ADH) augmente la réabsorption d'eau au niveau des tubules collecteurs rénaux, réduisant le volume urinaire pour maintenir la volémie." },
      { id: 19, section: "Physiologie", question: "Comparer les actions de l’insuline et du glucagon sur la glycémie.", answer: "Correction attendue : L'insuline est une hormone hypoglycémiante facilitant l'entrée du glucose cellulaire ; le glucagon est une hormone hyperglycémiante stimulant la glycogénolyse hépatique." },
      { id: 33, section: "Biologie et immunologie", question: "Différencier bactéries, virus, champignons et parasites sur le plan biologique.", answer: "Correction attendue : Bactéries (procaryotes cellulaires), virus (acellulaires obligatoirement intracellulaires), champignons (eucaryotes), parasites (êtres vivants dépendant d'un hôte)." },
      { id: 45, section: "Immunologie", question: "Décrire la fonction des anticorps.", answer: "Correction attendue : Immunoglobulines produites par les plasmocytes neutralisant spécifiquement les antigènes, facilitant la phagocytose et activant le complément." },
      { id: 52, section: "Maladies infectieuses", question: "Décrire les modes de transmission du paludisme.", answer: "Correction attendue : Transmission vectorielle par la piqûre de l'anophèle femelle infestée par le parasite Plasmodium (falciparum au Sénégal)." },
      { id: 65, section: "Sémiologie & Soins", question: "Décrire les signes d’alerte d’une détresse respiratoire.", answer: "Correction attendue : Polypnée superficielle, tirage intercostal, battement des ailes du nez, cyanose péribuccale et saturation en oxygène (SpO2) < 90%." },
      { id: 73, section: "Sémiologie & Soins", question: "Expliquer les signes évocateurs d’un accident vasculaire cérébral (AVC).", answer: "Correction attendue : Asymétrie faciale subite, faiblesse ou paralysie d'un membre (hémiplégie), troubles de la parole (aphasie) et céphalées brutales." },
      { id: 95, section: "Hygiène et asepsie", question: "Décrire les cinq moments essentiels de l’hygiène des mains selon les pratiques de soins.", answer: "Correction attendue : 1. Avant le contact patient ; 2. Avant geste aseptique ; 3. Après risque d'exposition à un liquide biologique ; 4. Après contact patient ; 5. Après contact avec l'environnement du patient." },
      { id: 105, section: "Hygiène et asepsie", question: "Expliquer la différence entre nettoyage, désinfection et stérilisation.", answer: "Correction attendue : Nettoyage (élimination des souillures visibles) ; Désinfection (destruction des micro-organismes pathogènes sur surfaces inertes) ; Stérilisation (destruction irréversible de tout micro-organisme y compris les spores)." },
      { id: 126, section: "Pharmacologie", question: "Définir médicament, principe actif, excipient et forme pharmaceutique.", answer: "Correction attendue : Médicament (substance à visée thérapeutique), principe actif (molécule active), excipient (véhicule inactif), forme pharmaceutique (galénique : injectable, per os, etc.)." },
      { id: 132, section: "Calculs de doses", question: "Calculer le volume à administrer si 500 mg sont disponibles dans 5 mL et que la prescription est de 250 mg.", answer: "Correction : 250 mg × (5 mL / 500 mg) = 2,5 mL à injecter." },
      { id: 136, section: "Calculs de doses", question: "Une perfusion de 500 mL doit passer en 5 heures. Calculer le débit en mL/h.", answer: "Correction : 500 mL / 5 h = 100 mL/h." },
      { id: 157, section: "Santé publique", question: "Définir incidence, prévalence et mortalité.", answer: "Correction attendue : Incidence (nombre de nouveaux cas sur une période) ; Prévalence (nombre total de cas à un instant donné) ; Mortalité (nombre de décès rapporté à la population totale)." },
      { id: 169, section: "Santé publique", question: "Expliquer la notion d’immunité collective.", answer: "Correction attendue : Protection indirecte de la population contre une maladie infectieuse lorsqu'un pourcentage seuil d'individus est immunisé (vaccination ou antécédent d'infection)." },
      { id: 191, section: "Statistiques & Raisonnement", question: "Calculer 15 % de 240.", answer: "Correction : 240 × 0,15 = 36." },
      { id: 226, section: "Communication médicale", question: "Rédiger une transmission professionnelle concernant un patient fébrile.", answer: "Correction attendue : Transmission structurée ciblée : Donnée (température mesurée à 39,2°C, sueurs, frissons) ; Action (administration du paracétamol prescrit, déshabillage partiel) ; Résultat (surveillance à H+1)." },
      { id: 253, section: "Éthique médicale", question: "Expliquer le principe du consentement aux soins.", answer: "Correction attendue : Droit fondamental du patient de recevoir une information claire et loyale avant d'accepter ou de refuser librement tout acte diagnostique ou thérapeutique." },
      { id: 284, section: "Pédiatrie & Maternité", question: "Décrire les priorités de surveillance d’un enfant présentant une détresse respiratoire.", answer: "Correction attendue : Libération des voies aériennes supérieures, oxygénothérapie adaptée, position demi-assise, surveillance de la fréquence respiratoire et de la SpO2." },
      { id: 320, section: "Informatique sanitaire", question: "Expliquer l’intérêt d’un archivage organisé des documents de soins.", answer: "Correction attendue : Garantir la traçabilité médico-légale, assurer la continuité de la prise en charge lors des réadmissions et faciliter les audits de qualité." }
    ],
    year: 2026,
    format: 'PDF',
    wc_product_id: 109,
    created_at: new Date().toISOString(),
  }
];

export const initialAnnales: Annale[] = [...baseAnnales, ...additionalAnnales, ...additionalAnnales2];
