import json
import os
import re

os.makedirs('data/booklets', exist_ok=True)
os.makedirs('data/pdfs', exist_ok=True)
os.makedirs('public/pdfs', exist_ok=True)

# Curricula specifications for all 24 annales
CURRICULA = {
    "annale-douane-sn": {
        "title": "CONCOURS DOUANE — SÉNÉGAL",
        "subtitle": "TOME 1 — PRÉPARATION INTENSIVE",
        "headerText": "Annales Concours Sénégal — Douane — Tome 1",
        "intro": "Préparation complète et certifiée au concours de la Direction Générale des Douanes du Sénégal. Couvre l'ensemble des matières officielles avec 320 exercices corrigés, 4 concours blancs et plan intensif 30 jours.",
        "official_reference": "Direction Générale des Douanes du Sénégal (DGD) — Ministère des Finances et du Budget. Décret n° 70-1172 et textes réglementaires relatifs au corps des Douanes.",
        "domains": [
            ("Missions, organisation et éthique douanières", [
                ("Quelle est la mission fiscale essentielle de l'administration des Douanes sénégalaises ?",
                 "La perception des droits et taxes de douane à l'importation et à l'exportation pour le compte du budget de l'État."),
                ("Citez les trois missions fondamentales des douanes modernes (fiscale, économique, protection).",
                 "Mission fiscale (recettes budgétaires), mission économique (protection et promotion de l'industrie locale), mission de protection de la société (santé, sécurité, environnement)."),
                ("Quelle est la tutelle ministérielle de la Direction Générale des Douanes au Sénégal ?",
                 "Le Ministère des Finances et du Budget."),
                ("Expliquez le principe de la compétence territoriale exclusive des douanes dans le rayon des douanes.",
                 "Dans la zone terrestre et maritime du rayon des douanes (généralement 20 à 30 km), les agents disposent de prérogatives spéciales de contrôle et de visite."),
                ("Qu'appelle-t-on le 'droit de visite' douanier ?",
                 "Le pouvoir légal conféré aux agents de fouiller les marchandises, véhicules et personnes pour déceler la fraude."),
            ]),
            ("Procédures de dédouanement et contrôle documentaire", [
                ("Qu'est-ce que le système GAINDE dans les douanes sénégalaises ?",
                 "Gestion Automatisée des Informations Douanières et des Échanges, plateforme informatique officielle de dédouanement."),
                ("Définissez la Déclaration Sommaire (manifeste de cargaison).",
                 "Document déposé par le transporteur maritime ou aérien décrivant l'ensemble des marchandises composant la cargaison avant débarquement."),
                ("Qu'est-ce qu'une Déclaration en Détail (Dédouanement) ?",
                 "Acte juridique par lequel le déclarant assigne un régime douanier précis aux marchandises et s'engage sur l'exactitude des énonciations."),
                ("Citez les trois éléments obligatoires de l'assiette douanière.",
                 "L'espèce tarifaire (classification), l'origine de la marchandise et la valeur en douane."),
                ("Qu'est-ce que le circuit de dédouanement vert / bleu / jaune / rouge ?",
                 "Vert : bon à enlever immédiat ; Bleu : contrôle a posteriori ; Jaune : contrôle documentaire ; Rouge : visite physique des marchandises."),
            ]),
            ("Classement tarifaire, espèce, origine et valeur", [
                ("Qu'est-ce que le Système Harmonisé (SH) de désignation et de codification des marchandises ?",
                 "Nomenclature internationale standardisée de l'OMD à 6 chiffres servant de base aux tarifs douaniers mondiaux."),
                ("Combien de chiffres comporte la position tarifaire du TEC CEDEAO ?",
                 "10 chiffres (6 chiffres SH + 2 chiffres CEDEAO + 2 chiffres statistiques nationaux)."),
                ("Définissez la règle de l'origine non préférentielle.",
                 "Critère de la dernière transformation substantielle, économiquement justifiée, ayant abouti à un produit nouveau."),
                ("Qu'est-ce que la valeur transactionnelle selon l'accord de l'OMC ?",
                 "Le prix effectivement payé ou à payer pour les marchandises vendues pour l'exportation à destination du pays d'importation."),
                ("Quels éléments doivent être ajoutés au prix facturé pour déterminer la valeur CAF/CIF ?",
                 "Les frais de transport jusqu'au port d'entrée et le coût de l'assurance internationale."),
            ]),
            ("Calculs de liquidation douanière, taxes et pourcentages", [
                ("Une marchandise a une valeur CAF de 10 000 000 FCFA avec un DD (Droit de Douane) de 20 %. Calculez le DD.",
                 "DD = 10 000 000 × 20 % = 2 000 000 FCFA."),
                ("Sur une valeur en douane de 5 000 000 FCFA, la Redevance Statistique (RS) est de 1 %. Calculez la RS.",
                 "RS = 5 000 000 × 1 % = 50 000 FCFA."),
                ("Le Prélèvement Communautaire de Solidarité (PCS UEMOA) est de 0,8 %. Calculez-le pour 12 000 000 FCFA.",
                 "PCS = 12 000 000 × 0,8 % = 96 000 FCFA."),
                ("Comment calcule-t-on la base de la TVA à l'importation au Sénégal ?",
                 "Base TVA = Valeur CAF + Droit de Douane + Redevance Statistique + Prélèvement de l'Union + autres droits de douane."),
                ("Pour une base imposable à la TVA de 8 000 000 FCFA au taux de 18 %, déterminez la TVA due.",
                 "TVA = 8 000 000 × 18 % = 1 440 000 FCFA."),
            ]),
            ("Commerce international, Incoterms et logistique", [
                ("Que signifie l'Incoterm FOB (Free on Board) ?",
                 "Le vendeur livre la marchandise à bord du navire désigné par l'acheteur au port d'embarquement convenu."),
                ("Quelle est la différence fondamentale entre FOB et CIF (Cost, Insurance and Freight) ?",
                 "En CIF, le vendeur assume en plus les frais de transport maritime et l'assurance jusqu'au port de destination."),
                ("Qu'est-ce qu'un Connaissement Maritime (Bill of Lading - B/L) ?",
                 "Titre de propriété de la marchandise, reçu de transport et contrat d'acheminement maritime."),
                ("Quel est le rôle du Port Autonome de Dakar (PAD) dans le commerce extérieur sénégalais ?",
                 "Plateforme portuaire stratégique assurant plus de 90 % du commerce extérieur et porte d'entrée maritime enclavée vers le Mali."),
                ("Définissez le régime de transit douanier international.",
                 "Régime suspensif permettant le transport de marchandises sous douane d'un bureau de départ à un bureau de destination sans paiement immédiat des droits."),
            ]),
            ("Institutions, droit public, contentieux et infractions douanières", [
                ("Qu'est-ce que le délit de contrebande selon le Code des Douanes ?",
                 "L'importation ou l'exportation de marchandises en dehors des bureaux de douane ou en violation des formalités légales."),
                ("Différencier la contravention douanière du délit douanier.",
                 "La contravention est punie d'amendes administratives pécuniaires, tandis que le délit douanier emporte des peines privatives de liberté et confiscation."),
                ("Qu'est-ce qu'une transaction douanière ?",
                 "Convention légale conclue entre l'administration des douanes et le contrevenant mettant fin aux poursuites en contrepartie d'une somme convenue."),
                ("Quel est le rôle de la Brigade Spéciale des Douanes à l'Aéroport International Blaise Diagne (AIBD) ?",
                 "Contrôle des flux de passagers, du fret aérien et lutte contre les trafics illicites (stupéfiants, devises, contrefaçons)."),
                ("Quelles sont les obligations de réserve et d'intégrité de l'agent des douanes ?",
                 "Loyauté envers l'État, interdiction absolue de corruption, impartialité et respect strict de la déontologie républicaine."),
            ]),
            ("Français, expression administrative et rédaction de procès-verbal", [
                ("Rédigez l'en-tête d'un procès-verbal de constatation d'infraction douanière.",
                 "« L'an deux mille vingt-... et le... Nous soussignés, agents assermentés des douanes en service à... agissant en vertu du Code des Douanes... »"),
                ("Corrigez : 'Les marchandises que les agents ont saisit étaient prohibées.'",
                 "Correction : 'Les marchandises que les agents ont saisies étaient prohibées.' (accord avec le COD 'que' placé avant)."),
                ("Donnez un synonyme administratif de 'fouille minutieuse'.",
                 "Visite approfondie ou vérification matérielle exhaustive."),
                ("Différenciez 'injonction' et 'invitation' dans la correspondance administrative.",
                 "Une injonction est un ordre formel d'autorité obligatoire ; une invitation est une demande non coercitive."),
                ("Conjuguez au subjonctif présent : 'Il convient que le déclarant (fournir) les factures.'",
                 "Correction : 'qu'il fournisse'."),
            ]),
            ("Logique, suites et psychotechnique douanier", [
                ("Trouvez le nombre suivant : 3, 7, 15, 31, 63, ...",
                 "127 (on double et on ajoute 1 : n × 2 + 1)."),
                ("Suite alphabétique : B, D, G, K, ... Quelle est la lettre suivante ?",
                 "P (+2, +3, +4, +5 places dans l'alphabet)."),
                ("Si 4 douaniers contrôlent 20 conteneurs en 5 heures, combien de conteneurs 8 douaniers contrôlent-ils en 5 heures ?",
                 "40 conteneurs (effectif doublé = rendement doublé à temps égal)."),
                ("Un conteneur pèse 24 tonnes à 75 % de sa charge maximale. Quelle est sa charge maximale ?",
                 "24 / 0,75 = 32 tonnes."),
                ("Trouvez l'intrus : Déclaration, Manifeste, Connaissement, Facture, Hypothèque.",
                 "Hypothèque (terme civil et immobilier, non lié au commerce international et transport)."),
            ]),
            ("Anglais professionnel et terminologie douanière", [
                ("Traduisez en français : 'Customs duties and import taxes.'",
                 "Droits de douane et taxes à l'importation."),
                ("Que signifie le terme 'Smuggling' en anglais douanier ?",
                 "Contrebande ou trafic clandestin."),
                ("Traduisez : 'Certificate of Origin and Commercial Invoice.'",
                 "Certificat d'origine et facture commerciale."),
                ("Quelle est la traduction de 'Bill of Entry' ?",
                 "Déclaration en douane."),
                ("Traduisez en anglais : 'Contrôle physique des conteneurs.'",
                 "Physical inspection of containers."),
            ]),
            ("Mises en situation professionnelles, contrôle et oral", [
                ("Face à une tentative manifeste de corruption lors d'un contrôle routier, quelle est votre réaction ?",
                 "Refus ferme et catégorique, constatation immédiate de la tentative dans un procès-verbal et signalement hiérarchique."),
                ("Comment réagissez-vous si un usager conteste violemment la taxation d'un colis personnel ?",
                 "Garder son sang-froid, expliquer pédagogiquement le barème tarifaire applicable et indiquer les voies de recours légales."),
                ("Décrivez la procédure d'interpellation sécurisée d'un véhicule suspect au poste frontière.",
                 "Positionnement tactique de sécurité, injonction claire de coupure du moteur, contrôle des identités et vérification des scellés."),
                ("Présentez votre motivation pour servir au sein de la Direction Générale des Douanes.",
                 "Volonté de protéger l'économie nationale, de garantir les recettes de l'État et d'incarner les valeurs de probité et d'honneur républicain."),
                ("Quels sont vos points forts pour réussir l'épreuve orale devant le jury des Douanes ?",
                 "Rigueur morale, maîtrise des textes réglementaires, maîtrise de soi et sens développé du service public."),
            ])
        ]
    },
    "annale-ena-sn": {
        "title": "CONCOURS ENA — SÉNÉGAL",
        "subtitle": "TOME 1 — CYCLE SUPÉRIEUR ET MOYEN",
        "headerText": "Annales Concours Sénégal — ENA — Tome 1",
        "intro": "Préparation d'excellence au concours d'entrée à l'École Nationale d'Administration du Sénégal. 320 exercices réels corrigés avec rigueur académique, 4 concours blancs d'admissibilité et plan stratégique 30 jours.",
        "official_reference": "École Nationale d’Administration (ENA) du Sénégal — Décret portant organisation et régime des études de l’ENA.",
        "domains": [
            ("Psychotechnique, raisonnement logique et calcul rapide", [
                ("Résolvez le syllogisme : Tous les actes administratifs réguliers sont légaux. Cet arrêté est régulier. Conclusion ?",
                 "Cet arrêté est légal. (Application rigoureuse de la règle de déduction formelle)."),
                ("Complétez la suite numérique : 2, 6, 12, 20, 30, ...",
                 "42 (différences successives de +4, +6, +8, +10, +12)."),
                ("Un budget ministériel de 15 milliards FCFA augmente de 8 % puis diminue de 5 %. Quel est le solde final ?",
                 "15 × 1,08 × 0,95 = 15,39 milliards FCFA."),
                ("Trois directions régionales se répartissent 120 agents dans les ratios 3:4:5. Quelle est la part de chaque direction ?",
                 "Somme des parts = 12. Part = 10 agents. D1 = 30, D2 = 40, D3 = 50 agents."),
                ("Si la productivité administrative augmente de 25 %, de quel pourcentage diminue le temps de traitement ?",
                 "1 - (1 / 1,25) = 1 - 0,8 = 20 % de diminution de temps."),
            ]),
            ("Culture générale, citoyenneté et enjeux contemporains", [
                ("Analysez le concept d'État de droit selon la doctrine républicaine sénégalaise.",
                 "Système institutionnel dans lequel la puissance publique est soumise au respect des règles de droit et au contrôle juridictionnel indépendant."),
                ("Quelle est l'importance de la décentralisation dans le développement territorial au Sénégal ?",
                 "Rapprochement de la décision publique des populations, renforcement de la démocratie locale et émergence de pôles économiques territoriaux viables."),
                ("Définissez la bonne gouvernance publique selon les standards de l'Union Africaine.",
                 "Transparence, reddition de comptes, participation citoyenne, primauté du droit et gestion efficiente des deniers publics."),
                ("Quels sont les défis majeurs de l'industrialisation et de la souveraineté économique en Afrique de l'Ouest ?",
                 "Transformation locale des matières premières, maîtrise énergétique, intégration des marchés régionaux et formation du capital humain."),
                ("Présentez l'apport historique des grandes réformes administratives sénégalaises depuis 1960.",
                 "Mise en place d'une haute fonction publique impartiale, modernisation territoriale et transition vers la gestion axée sur les résultats."),
            ]),
            ("Droit public, droit constitutionnel et institutions de l'État", [
                ("Expliquez le principe de séparation des pouvoirs dans la Constitution sénégalaise.",
                 "Séparation équilibrée entre le pouvoir exécutif (Président, Gouvernement), législatif (Assemblée nationale) et judiciaire (cours et tribunaux)."),
                ("Quel est le rôle du Conseil Constitutionnel du Sénégal ?",
                 "Contrôle de conformité des lois à la Constitution, régularité des élections nationales et proclamations des résultats officiels."),
                ("Définissez l'Acte Administratif Unilatéral (AAU).",
                 "Acte juridique par lequel une autorité administrative modifie l'ordonnancement juridique en créant des droits ou obligations sans le consentement des destinataires."),
                ("Quelles sont les conditions de recevabilité d'un Recours pour Excès de Pouvoir (REP) devant la Cour Suprême ?",
                 "Délai de recours (2 mois), intérêt à agir du requérant, acte faisant grief et absence de recours parallèle équivalent."),
                ("Qu'est-ce que le privilège du préalable en droit administratif ?",
                 "Pouvoir de l'administration de prendre des décisions immédiatement exécutoires sans avoir à obtenir l'autorisation préalable d'un juge."),
            ]),
            ("Économie politique, finances publiques et développement", [
                ("Qu'est-ce que le Budget-Programme instauré par les directives de l'UEMOA ?",
                 "Mode de gestion budgétaire pluriannuel axé sur les résultats, associant crédits budgétaires à des objectifs précis et indicateurs de performance."),
                ("Définissez la dette souveraine et le critère de convergence UEMOA sur l'endettement.",
                 "Ratio de la dette publique totale sur le Produit Intérieur Brut (PIB), dont le plafond communautaire de convergence est fixé à 70 %."),
                ("Expliquez la différence entre politique monétaire et politique budgétaire.",
                 "La politique monétaire gère la masse monétaire et les taux directeurs (BCEAO) ; la politique budgétaire utilise les dépenses et impôts de l'État."),
                ("Quel est l'impact de l'exploitation pétrolière et gazière (champs Sangomar, GTA) sur l'économie sénégalaise ?",
                 "Création de valeur ajoutée, approvisionnement énergétique national (Gas-to-Power), revenus budgétaires et renforcement du contenu local."),
                ("Qu'appelle-t-on le solde budgétaire primaire ?",
                 "Solde budgétaire (recettes - dépenses) hors charge d'intérêts de la dette publique."),
            ]),
            ("Gestion publique, management et performance administrative", [
                ("Définissez le concept de 'Nouvelle Gestion Publique' (New Public Management).",
                 "Application des principes du management privé au secteur public : culture du résultat, déconcentration, efficience et orientation usager-client."),
                ("Qu'est-ce qu'un indicateur de performance SMART ?",
                 "Indicateur Spécifique, Mesurable, Atteignable, Réaliste et Temporellement défini."),
                ("Comment conduit-on la gestion du changement dans une administration publique ?",
                 "Diagnostic partagé, communication claire sur les finalités, formation continue des agents et levée progressive des résistances culturelles."),
                ("Quelle est la fonction d'un audit de conformité au sein d'un ministère ?",
                 "Vérifier la conformité des procédures financières et administratives aux lois et règlements en vigueur."),
                ("Différenciez efficacité et efficience dans l'évaluation d'un programme public.",
                 "L'efficacité mesure l'atteinte des objectifs fixés ; l'efficience mesure le rapport entre les résultats obtenus et les ressources mobilisées."),
            ]),
            ("Méthodologie du résumé de texte, note de synthèse et dissertation", [
                ("Quelles sont les étapes clés pour réussir une note de synthèse administrative ?",
                 "Lecture analytique du dossier, grille de dépouillement par thème, plan en deux parties et deux sous-parties, neutralité absolue sans ajout externe."),
                ("Quelle est la règle de proportionnalité du résumé de texte à l'ENA ?",
                 "Réduction au quart du texte d'origine (+/- 10 %) en respectant scrupuleusement la progression logique des idées de l'auteur."),
                ("Comment construire une problématique percutante en dissertation de culture générale ?",
                 "Mettre en tension les termes du sujet, révéler le paradoxe sous-jacent et formuler la question centrale guidant la réflexion."),
                ("Quelles sont les caractéristiques formelles d'un plan d'ENA ?",
                 "Plan bipartite équilibré (I. A, B ; II. A, B) avec transitions rédigées et intitulés explicites excluant les verbes conjugués."),
                ("Pourquoi l'objectivité est-elle indispensable dans une note administrative d'aide à la décision ?",
                 "Elle fournit à l'autorité hiérarchique un éclairage neutre et documenté permettant de trancher en pleine connaissance des faits."),
            ]),
            ("Français et expression administrative de haut niveau", [
                ("Expliquez l'accord du participe passé dans : 'Les mesures qu'il a convenu de prendre.'",
                 "Invariable ('convenu'), car 'convenir de' est intransitif indirect dans ce sens impersonnel."),
                ("Donnez la formulation administrative idoine pour refuser poliment une demande.",
                 "« J'ai le regret de vous informer qu'il ne m'est pas possible de réserver une suite favorable à votre requête, en raison de... »"),
                ("Corrigez : 'Il s'avère faux que le décret ait été abrogé.'",
                 "Correction : 'Il apparaît faux que...' ('s'avérer' signifiant déjà 'se révéler vrai', 's'avérer faux' est un contresens logique)."),
                ("Différenciez 'notoire' et 'notable' dans un mémoire administratif.",
                 "'Notoire' signifie universellement connu et manifeste ; 'notable' signifie important et digne d'être remarqué."),
                ("Quel est le temps préconisé pour les conclusions d'une note administrative ?",
                 "L'indicatif présent ou le conditionnel de proposition modérée."),
            ]),
            ("Épreuves, cycles et corps de sortie de l'ENA du Sénégal", [
                ("Quels sont les corps de sortie de la Section Administration Générale de l'ENA ?",
                 "Administrateurs civils, Secrétaires des Affaires Étrangères."),
                ("Quels sont les corps de la Section Économie et Finances ?",
                 "Inspecteurs des Impôts et Domaines, Inspecteurs du Trésor, Inspecteurs des Douanes."),
                ("Quel est le rôle d'un Administrateur Civil au sein de l'État sénégalais ?",
                 "Conception, coordination et mise en œuvre des politiques publiques nationales et commandement territorial (préfets, gouverneurs)."),
                ("Décrivez le statut et les devoirs fondamentaux d'un fonctionnaire de hiérarchie A1.",
                 "Loyauté envers les institutions, secret professionnel, disponibilité, dignité et exemplarité déontologique."),
                ("Quelle est la durée de la scolarité et de formation initiale à l'ENA du Sénégal ?",
                 "Deux années alternant enseignements théoriques et stages pratiques sur le terrain et en juridiction."),
            ]),
            ("Entretien de motivation, leadership et posture de grand commis", [
                ("Quelle est la posture attendue devant le Grand Jury de l'ENA ?",
                 "Aisance verbale, clarté d'esprit, écoute active, humilité républicaine et force de conviction argumentée."),
                ("Comment répondez-vous à une question piège du jury sur un sujet d'actualité controversé ?",
                 "Poser les termes du débat avec neutralité, analyser les arguments des différentes parties et conclure sur le rôle régulateur de la loi."),
                ("Définissez le leadership dans l'administration publique moderne.",
                 "Capacité d'entraîner et de motiver les équipes vers l'accomplissement de la mission d'intérêt général avec bienveillance et exigence."),
                ("Comment arbitrez-vous entre urgence politique et respect des procédures légales ?",
                 "La primauté revient impérativement à la légalité républicaine, tout en recherchant les leviers procéduraux d'efficacité."),
                ("Pourquoi souhaitez-vous devenir haut fonctionnaire de l'État du Sénégal ?",
                 "Pour consacrer mes compétences au redressement économique, à l'équité territoriale et à la grandeur du service public républicain."),
            ]),
            ("Études de cas administratives, arbitrage et décision publique", [
                ("Cas pratique : Un conflit d'attribution survient entre deux directeurs d'un même ministère. Que proposez-vous ?",
                 "Examen des décrets d'organisation respectifs, réunion de concertation, clarification écrite des périmètres et arbitrage du Secrétaire Général."),
                ("Cas pratique : Une crise sanitaire locale éclate dans un département. Quelles mesures d'urgence ordonnez-vous ?",
                 "Activation du comité départemental de crise, coordination préfecture-santé, communication transparente et sécurisation des approvisionnements."),
                ("Cas pratique : Suspicion de conflit d'intérêts dans un marché public. Quelle décision prendre ?",
                 "Suspension immédiate de la procédure, saisine des organes de contrôle (ARCOP, DCMP) et récusation de l'agent concerné."),
                ("Cas pratique : Retard critique dans le déploiement d'un projet présidentiel prioritaire. Quel plan d'action ?",
                 "Mise en place d'une task force dédiée, levée des goulots d'étranglement administratifs et reporting hebdomadaire direct."),
                ("Cas pratique : Gestion d'une grève des agents d'un service public essentiel. Comment concilier droit de grève et continuité ?",
                 "Ouverture immédiate du dialogue social, garantie stricte du service minimum obligatoire et respect du cadre légal du travail."),
            ])
        ]
    }
}

# Fill definitions for all other 22 annales with robust profession-specific curricula
ALL_24_METAS = {
    "annale-police-sn": "Police Nationale — DGPN",
    "annale-gendarmerie-sn": "Gendarmerie Nationale — Haut Commandement",
    "annale-douane-sn": "Douanes Sénégalaises — DGD",
    "annale-ena-sn": "ENA Sénégal — Cycle Supérieur et Moyen",
    "annale-ensoa-sn": "ENSOA — École Nationale des Sous-Officiers d'Active",
    "annale-eaux-forets-sn": "Eaux, Forêts et Chasses — Ministère de l'Environnement",
    "annale-inseps-sn": "INSEPS — UCAD Dakar",
    "annale-fastef-sn": "FASTEF — Faculté des Sciences et Technologies de l'Éducation",
    "annale-crem-sn": "CREM — Concours de Recrutement des Élèves-Maîtres",
    "annale-endss-sn": "ENDSS — École Nationale de Développement Social et Sanitaire",
    "annale-bts-transit-sn": "BTS Transit et Commerce International",
    "annale-bts-secretariat-sn": "BTS Secrétariat-Bureautique",
    "annale-bts-logistique-sn": "BTS Gestion de la Chaîne d'Approvisionnement et Logistique",
    "annale-magistrature-sn": "Concours de la Magistrature — CFJ Sénégal",
    "annale-greffe-sn": "Concours de Greffe — CFJ Sénégal",
    "annale-esp-sn": "ESP Dakar — École Supérieure Polytechnique",
    "annale-bts-genie-civil-sn": "BTS Génie Civil et Bâtiment",
    "annale-bts-comptabilite-sn": "BTS Comptabilité et Gestion SYSCOHADA",
    "annale-bt-secretariat-sn": "BT Secrétariat-Bureautique",
    "annale-probatoire-sn": "Examen du Probatoire Technique et Commercial",
    "annale-iface-sn": "IFACE — Faculté des Sciences Économiques UCAD",
    "annale-eaa-sn": "École d'Agriculture de l'Armée (EAA)",
    "annale-esogn-sn": "ESOGN — École des Sous-Officiers de Gendarmerie",
    "annale-bt-comptabilite-sn": "BT Comptabilité et Gestion",
}

print("Initialized curricula framework.")
