# BTS TRANSIT — TOME 1 data
def get_bts_transit():
    correction_std = "Correction attendue : identifier les données, le document ou la règle concernés, effectuer les contrôles nécessaires, détailler le raisonnement et conclure avec une solution opérationnelle."
    
    sections = [
        {"title": "1. Douane et réglementation douanière — 32 exercices", "count": 32, "description": "Fonctions, territoire, déclaration, commissionnaire agréé, valeur en douane, origine et classement."},
        {"title": "2. Transit douanier et opérations de transport — 32 exercices", "count": 32, "description": "Régime du transit, bureaux départ/destination, garanties, délais, scellés et apurement."},
        {"title": "3. Commerce international et incoterms — 32 exercices", "count": 32, "description": "Contrat de vente, facture, packing list, Incoterms et lettre de crédit."},
        {"title": "4. Transport maritime, portuaire et conteneurs — 32 exercices", "count": 32, "description": "Armateur, consignataire, connaissement, conteneurs FCL/LCL, dépotage et surestaries."},
        {"title": "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "count": 32, "description": "Lettre de voiture, planning, coûts de transport, stocks et tournées."},
        {"title": "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "count": 32, "description": "Dossier import/export, pro forma, certificat d'origine, cohérence et archivage."},
        {"title": "7. Calculs douaniers, financiers et statistiques — 32 exercices", "count": 32, "description": "Pourcentages, TVA, devises, fret, marge, rotation et indicateurs de performance."},
        {"title": "8. Anglais professionnel et communication — 32 exercices", "count": 32, "description": "Terminologie anglaise du transit, courriels professionnels et vocabulaire maritime."},
        {"title": "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "count": 32, "description": "Systèmes logistiques, dématérialisation, bases de données, sécurité et Excel."},
        {"title": "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "count": 32, "description": "Gestion des litiges, anomalies, sous-évaluation, fraudes et tableaux de bord."}
    ]

    q_list = [
        # S1 (1-32)
        (1, "1. Douane et réglementation douanière — 32 exercices", "Définir la fonction économique et fiscale de la douane.", correction_std),
        (2, "1. Douane et réglementation douanière — 32 exercices", "Présenter les principales missions d’une administration douanière.", correction_std),
        (3, "1. Douane et réglementation douanière — 32 exercices", "Expliquer la notion de territoire douanier.", correction_std),
        (4, "1. Douane et réglementation douanière — 32 exercices", "Différencier importation, exportation et transit.", correction_std),
        (5, "1. Douane et réglementation douanière — 32 exercices", "Définir une marchandise au sens douanier.", correction_std),
        (6, "1. Douane et réglementation douanière — 32 exercices", "Expliquer le principe de la déclaration en douane.", correction_std),
        (7, "1. Douane et réglementation douanière — 32 exercices", "Présenter les informations essentielles d’une déclaration.", correction_std),
        (8, "1. Douane et réglementation douanière — 32 exercices", "Définir le déclarant en douane.", correction_std),
        (9, "1. Douane et réglementation douanière — 32 exercices", "Expliquer le rôle d’un commissionnaire en douane agréé.", correction_std),
        (10, "1. Douane et réglementation douanière — 32 exercices", "Présenter les responsabilités du déclarant.", correction_std),
        (11, "1. Douane et réglementation douanière — 32 exercices", "Définir la valeur en douane.", correction_std),
        (12, "1. Douane et réglementation douanière — 32 exercices", "Expliquer pourquoi la valeur en douane est importante.", correction_std),
        (13, "1. Douane et réglementation douanière — 32 exercices", "Présenter les principaux éléments pouvant entrer dans la valeur en douane.", correction_std),
        (14, "1. Douane et réglementation douanière — 32 exercices", "Définir l’origine d’une marchandise.", correction_std),
        (15, "1. Douane et réglementation douanière — 32 exercices", "Différencier origine préférentielle et origine non préférentielle.", correction_std),
        (16, "1. Douane et réglementation douanière — 32 exercices", "Expliquer l’importance du certificat d’origine.", correction_std),
        (17, "1. Douane et réglementation douanière — 32 exercices", "Définir le classement tarifaire.", correction_std),
        (18, "1. Douane et réglementation douanière — 32 exercices", "Expliquer le rôle du système harmonisé.", correction_std),
        (19, "1. Douane et réglementation douanière — 32 exercices", "Présenter l’utilité d’un code tarifaire.", correction_std),
        (20, "1. Douane et réglementation douanière — 32 exercices", "Expliquer les risques d’une mauvaise classification tarifaire.", correction_std),
        (21, "1. Douane et réglementation douanière — 32 exercices", "Définir les droits et taxes à l’importation.", correction_std),
        (22, "1. Douane et réglementation douanière — 32 exercices", "Différencier droit de douane, TVA et autres prélèvements.", correction_std),
        (23, "1. Douane et réglementation douanière — 32 exercices", "Expliquer la notion d’exonération douanière.", correction_std),
        (24, "1. Douane et réglementation douanière — 32 exercices", "Présenter le principe du contrôle documentaire.", correction_std),
        (25, "1. Douane et réglementation douanière — 32 exercices", "Présenter le principe du contrôle physique.", correction_std),
        (26, "1. Douane et réglementation douanière — 32 exercices", "Expliquer la sélectivité du contrôle douanier.", correction_std),
        (27, "1. Douane et réglementation douanière — 32 exercices", "Définir la mainlevée des marchandises.", correction_std),
        (28, "1. Douane et réglementation douanière — 32 exercices", "Présenter les conséquences d’une déclaration inexacte.", correction_std),
        (29, "1. Douane et réglementation douanière — 32 exercices", "Analyser un cas fictif de sous-évaluation d’une marchandise.", correction_std),
        (30, "1. Douane et réglementation douanière — 32 exercices", "Analyser un cas de mauvaise origine déclarée.", correction_std),
        (31, "1. Douane et réglementation douanière — 32 exercices", "Construire une checklist de conformité avant déclaration.", correction_std),
        (32, "1. Douane et réglementation douanière — 32 exercices", "Rédiger une note expliquant les risques d’une fausse déclaration.", correction_std),

        # S2 (33-64)
        (33, "2. Transit douanier et opérations de transport — 32 exercices", "Définir le régime du transit douanier.", correction_std),
        (34, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer l’objectif économique du transit.", correction_std),
        (35, "2. Transit douanier et opérations de transport — 32 exercices", "Différencier transit national et transit international.", correction_std),
        (36, "2. Transit douanier et opérations de transport — 32 exercices", "Présenter les principaux acteurs d’une opération de transit.", correction_std),
        (37, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer le rôle du transporteur dans le transit.", correction_std),
        (38, "2. Transit douanier et opérations de transport — 32 exercices", "Décrire le rôle du déclarant pendant une opération de transit.", correction_std),
        (39, "2. Transit douanier et opérations de transport — 32 exercices", "Présenter les éléments essentiels d’une déclaration de transit.", correction_std),
        (40, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer la notion de bureau de départ.", correction_std),
        (41, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer la notion de bureau de destination.", correction_std),
        (42, "2. Transit douanier et opérations de transport — 32 exercices", "Présenter le principe de la garantie en matière de transit.", correction_std),
        (43, "2. Transit douanier et opérations de transport — 32 exercices", "Définir la garantie douanière.", correction_std),
        (44, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer les risques liés à la rupture d’un régime de transit.", correction_std),
        (45, "2. Transit douanier et opérations de transport — 32 exercices", "Présenter les obligations générales du transporteur.", correction_std),
        (46, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer la notion de délai de transit.", correction_std),
        (47, "2. Transit douanier et opérations de transport — 32 exercices", "Analyser un retard fictif dans une opération de transit.", correction_std),
        (48, "2. Transit douanier et opérations de transport — 32 exercices", "Analyser un cas de rupture de scellé douanier.", correction_std),
        (49, "2. Transit douanier et opérations de transport — 32 exercices", "Décrire la procédure à suivre lorsqu’un scellé est endommagé.", correction_std),
        (50, "2. Transit douanier et opérations de transport — 32 exercices", "Présenter les contrôles effectués lors du passage d’un véhicule.", correction_std),
        (51, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer le rôle des documents accompagnant la marchandise.", correction_std),
        (52, "2. Transit douanier et opérations de transport — 32 exercices", "Construire le circuit complet d’une marchandise en transit.", correction_std),
        (53, "2. Transit douanier et opérations de transport — 32 exercices", "Comparer transport routier et transport maritime pour un transit régional.", correction_std),
        (54, "2. Transit douanier et opérations de transport — 32 exercices", "Présenter les risques de détournement de marchandises en transit.", correction_std),
        (55, "2. Transit douanier et opérations de transport — 32 exercices", "Analyser une différence entre marchandise déclarée et marchandise constatée.", correction_std),
        (56, "2. Transit douanier et opérations de transport — 32 exercices", "Construire une fiche de suivi d’un camion en transit.", correction_std),
        (57, "2. Transit douanier et opérations de transport — 32 exercices", "Rédiger une procédure interne de suivi des délais de transit.", correction_std),
        (58, "2. Transit douanier et opérations de transport — 32 exercices", "Présenter les éléments à vérifier avant clôture d’un transit.", correction_std),
        (59, "2. Transit douanier et opérations de transport — 32 exercices", "Expliquer la preuve de l’arrivée des marchandises.", correction_std),
        (60, "2. Transit douanier et opérations de transport — 32 exercices", "Analyser un dossier fictif de transit non apuré.", correction_std),
        (61, "2. Transit douanier et opérations de transport — 32 exercices", "Proposer des mesures pour réduire les retards de transit.", correction_std),
        (62, "2. Transit douanier et opérations de transport — 32 exercices", "Construire une checklist chauffeur-documentation-frontière.", correction_std),
        (63, "2. Transit douanier et opérations de transport — 32 exercices", "Rédiger une note sur la traçabilité d’un transport en transit.", correction_std),
        (64, "2. Transit douanier et opérations de transport — 32 exercices", "Analyser un incident de transit et proposer un plan correctif.", correction_std),

        # S3 (65-96)
        (65, "3. Commerce international et incoterms — 32 exercices", "Définir le commerce international.", correction_std),
        (66, "3. Commerce international et incoterms — 32 exercices", "Présenter les principales étapes d’une opération d’importation.", correction_std),
        (67, "3. Commerce international et incoterms — 32 exercices", "Présenter les principales étapes d’une opération d’exportation.", correction_std),
        (68, "3. Commerce international et incoterms — 32 exercices", "Différencier fournisseur, acheteur, importateur et exportateur.", correction_std),
        (69, "3. Commerce international et incoterms — 32 exercices", "Définir un contrat de vente internationale.", correction_std),
        (70, "3. Commerce international et incoterms — 32 exercices", "Identifier les clauses essentielles d’un contrat international.", correction_std),
        (71, "3. Commerce international et incoterms — 32 exercices", "Expliquer le rôle d’une facture commerciale.", correction_std),
        (72, "3. Commerce international et incoterms — 32 exercices", "Présenter les informations essentielles d’une facture commerciale.", correction_std),
        (73, "3. Commerce international et incoterms — 32 exercices", "Définir un bon de commande international.", correction_std),
        (74, "3. Commerce international et incoterms — 32 exercices", "Expliquer le rôle de la liste de colisage.", correction_std),
        (75, "3. Commerce international et incoterms — 32 exercices", "Présenter les informations essentielles d’une packing list.", correction_std),
        (76, "3. Commerce international et incoterms — 32 exercices", "Définir un Incoterm.", correction_std),
        (77, "3. Commerce international et incoterms — 32 exercices", "Expliquer l’intérêt des Incoterms dans une vente internationale.", correction_std),
        (78, "3. Commerce international et incoterms — 32 exercices", "Comparer EXW et FCA.", correction_std),
        (79, "3. Commerce international et incoterms — 32 exercices", "Comparer FOB et CIF.", correction_std),
        (80, "3. Commerce international et incoterms — 32 exercices", "Comparer CFR et CIF.", correction_std),
        (81, "3. Commerce international et incoterms — 32 exercices", "Comparer DAP et DDP.", correction_std),
        (82, "3. Commerce international et incoterms — 32 exercices", "Identifier le transfert des risques dans un Incoterm donné.", correction_std),
        (83, "3. Commerce international et incoterms — 32 exercices", "Différencier transfert des coûts et transfert des risques.", correction_std),
        (84, "3. Commerce international et incoterms — 32 exercices", "Analyser un choix d’Incoterm pour une entreprise sénégalaise.", correction_std),
        (85, "3. Commerce international et incoterms — 32 exercices", "Calculer le coût d’une importation à partir d’un prix FOB et de frais de transport.", correction_std),
        (86, "3. Commerce international et incoterms — 32 exercices", "Construire un prix rendu à partir de plusieurs coûts.", correction_std),
        (87, "3. Commerce international et incoterms — 32 exercices", "Analyser l’impact du fret sur le prix final d’une marchandise.", correction_std),
        (88, "3. Commerce international et incoterms — 32 exercices", "Présenter les risques commerciaux d’un mauvais choix d’Incoterm.", correction_std),
        (89, "3. Commerce international et incoterms — 32 exercices", "Définir une lettre de crédit.", correction_std),
        (90, "3. Commerce international et incoterms — 32 exercices", "Présenter les caractéristiques d’un paiement documentaire.", correction_std),
        (91, "3. Commerce international et incoterms — 32 exercices", "Différencier paiement anticipé et paiement à crédit.", correction_std),
        (92, "3. Commerce international et incoterms — 32 exercices", "Analyser un risque de non-paiement international.", correction_std),
        (93, "3. Commerce international et incoterms — 32 exercices", "Présenter les documents permettant de sécuriser une transaction.", correction_std),
        (94, "3. Commerce international et incoterms — 32 exercices", "Construire une checklist d’un dossier d’importation.", correction_std),
        (95, "3. Commerce international et incoterms — 32 exercices", "Rédiger une demande de cotation internationale.", correction_std),
        (96, "3. Commerce international et incoterms — 32 exercices", "Analyser une offre commerciale internationale et relever les incohérences.", correction_std),

        # S4 (97-128)
        (97, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les caractéristiques du transport maritime.", correction_std),
        (98, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Identifier les principaux acteurs d’une chaîne maritime.", correction_std),
        (99, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Définir un armateur.", correction_std),
        (100, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Définir un consignataire de navire.", correction_std),
        (101, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Définir un transitaire maritime.", correction_std),
        (102, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Expliquer le rôle d’un terminal portuaire.", correction_std),
        (103, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Définir un connaissement maritime.", correction_std),
        (104, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les principales informations d’un connaissement.", correction_std),
        (105, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Expliquer la fonction probatoire du connaissement.", correction_std),
        (106, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Différencier connaissement et lettre de transport.", correction_std),
        (107, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Définir un conteneur maritime.", correction_std),
        (108, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les principaux types de conteneurs.", correction_std),
        (109, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Différencier conteneur 20 pieds et 40 pieds.", correction_std),
        (110, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Expliquer la notion de conteneur plein.", correction_std),
        (111, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Expliquer la notion de groupage.", correction_std),
        (112, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Différencier FCL et LCL.", correction_std),
        (113, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les étapes d’une opération de dépotage.", correction_std),
        (114, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les étapes d’une opération d’empotage.", correction_std),
        (115, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Expliquer l’importance du poids vérifié d’un conteneur.", correction_std),
        (116, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Analyser un cas de différence entre poids déclaré et poids constaté.", correction_std),
        (117, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les risques de surcharge d’un conteneur.", correction_std),
        (118, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Expliquer la notion de surestaries.", correction_std),
        (119, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les conséquences d’un retard de restitution d’un conteneur.", correction_std),
        (120, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Construire le circuit d’un conteneur depuis le navire jusqu’au client.", correction_std),
        (121, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Analyser un retard portuaire fictif.", correction_std),
        (122, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Identifier les documents nécessaires à la sortie d’une marchandise.", correction_std),
        (123, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les contrôles avant enlèvement d’un conteneur.", correction_std),
        (124, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Analyser une avarie constatée à la livraison.", correction_std),
        (125, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Rédiger une réserve sur une marchandise endommagée.", correction_std),
        (126, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Construire une checklist de suivi d’un conteneur import.", correction_std),
        (127, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Présenter les mesures de sécurité lors de la manutention portuaire.", correction_std),
        (128, "4. Transport maritime, portuaire et conteneurs — 32 exercices", "Analyser un dossier maritime complet et identifier les pièces manquantes.", correction_std),

        # S5 (129-160)
        (129, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Définir la chaîne logistique.", correction_std),
        (130, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Présenter les fonctions principales de la logistique.", correction_std),
        (131, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Différencier transport, logistique et supply chain.", correction_std),
        (132, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Identifier les acteurs d’une chaîne d’approvisionnement.", correction_std),
        (133, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Définir un transporteur routier.", correction_std),
        (134, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Présenter les documents de transport routier.", correction_std),
        (135, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Expliquer le rôle d’une lettre de voiture.", correction_std),
        (136, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Présenter les informations essentielles d’un document de transport.", correction_std),
        (137, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Définir un ordre de transport.", correction_std),
        (138, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Expliquer le rôle d’un planning de livraison.", correction_std),
        (139, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Calculer un taux de livraison à temps.", correction_std),
        (140, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Calculer un coût moyen de transport par tonne.", correction_std),
        (141, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Calculer un coût de transport par kilomètre.", correction_std),
        (142, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Déterminer la capacité disponible d’un véhicule.", correction_std),
        (143, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Analyser un problème de surcharge d’un camion.", correction_std),
        (144, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Optimiser un itinéraire entre plusieurs points.", correction_std),
        (145, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Calculer la durée théorique d’un trajet.", correction_std),
        (146, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Analyser l’impact d’un retard de livraison.", correction_std),
        (147, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Définir le stock de sécurité.", correction_std),
        (148, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Expliquer le point de commande.", correction_std),
        (149, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Calculer une quantité de stock après entrées et sorties.", correction_std),
        (150, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Analyser une rupture de stock.", correction_std),
        (151, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Présenter les principes de l’inventaire.", correction_std),
        (152, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Différencier stock physique et stock informatique.", correction_std),
        (153, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Construire un tableau de suivi des expéditions.", correction_std),
        (154, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Proposer des indicateurs de performance logistique.", correction_std),
        (155, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Définir le taux de service.", correction_std),
        (156, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Définir le délai moyen de livraison.", correction_std),
        (157, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Analyser les causes d’un mauvais taux de service.", correction_std),
        (158, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Construire un plan d’amélioration logistique.", correction_std),
        (159, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Analyser une tournée de livraison et proposer une optimisation.", correction_std),
        (160, "5. Transport routier, logistique et chaîne d’approvisionnement — 32 exercices", "Rédiger une procédure de réception des marchandises.", correction_std),

        # S6 (161-192)
        (161, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Identifier les pièces fondamentales d’un dossier d’importation.", correction_std),
        (162, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Identifier les pièces fondamentales d’un dossier d’exportation.", correction_std),
        (163, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Présenter les informations d’une facture pro forma.", correction_std),
        (164, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Différencier facture pro forma et facture commerciale.", correction_std),
        (165, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Expliquer le rôle d’un certificat d’origine.", correction_std),
        (166, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Présenter le rôle d’un certificat sanitaire lorsque requis.", correction_std),
        (167, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Expliquer l’utilité d’une liste de colisage.", correction_std),
        (168, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Présenter le rôle d’un document de transport.", correction_std),
        (169, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Identifier les informations à vérifier sur une facture.", correction_std),
        (170, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Contrôler la cohérence entre facture et packing list.", correction_std),
        (171, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Contrôler la cohérence entre facture et document de transport.", correction_std),
        (172, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Analyser une différence de quantité entre deux documents.", correction_std),
        (173, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Analyser une différence de poids entre facture et packing list.", correction_std),
        (174, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Analyser une différence de valeur entre facture et déclaration.", correction_std),
        (175, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Construire une fiche de contrôle documentaire.", correction_std),
        (176, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Rédiger une demande de document manquant.", correction_std),
        (177, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Rédiger un accusé de réception d’un dossier de transit.", correction_std),
        (178, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Rédiger une demande de correction d’une facture.", correction_std),
        (179, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Rédiger une note de transmission d’un dossier douanier.", correction_std),
        (180, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Construire un bordereau de suivi documentaire.", correction_std),
        (181, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Classer chronologiquement les documents d’une opération.", correction_std),
        (182, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Créer une procédure de validation avant transmission au déclarant.", correction_std),
        (183, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Définir la traçabilité documentaire.", correction_std),
        (184, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Expliquer les risques d’un document falsifié.", correction_std),
        (185, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Identifier des incohérences dans un dossier fictif.", correction_std),
        (186, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Analyser une facture comportant une erreur de devise.", correction_std),
        (187, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Analyser une packing list comportant une erreur de quantité.", correction_std),
        (188, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Analyser un connaissement comportant une différence de poids.", correction_std),
        (189, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Proposer une procédure de correction d’une anomalie documentaire.", correction_std),
        (190, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Construire une checklist de clôture d’un dossier import.", correction_std),
        (191, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Construire une checklist de clôture d’un dossier export.", correction_std),
        (192, "6. Documents commerciaux, administratifs et opérations de transit — 32 exercices", "Présenter les bonnes pratiques d’archivage des dossiers.", correction_std),

        # S7 (193-224)
        (193, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un pourcentage d’augmentation du prix d’une marchandise.", correction_std),
        (194, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer une remise commerciale sur une facture.", correction_std),
        (195, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un prix net après remise.", correction_std),
        (196, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer la TVA à partir d’une base taxable donnée.", correction_std),
        (197, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un total facture à partir de plusieurs lignes.", correction_std),
        (198, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Convertir une valeur en devise selon un taux de change donné.", correction_std),
        (199, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer la valeur d’une marchandise en monnaie locale.", correction_std),
        (200, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un coût de transport par kilogramme.", correction_std),
        (201, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un coût de fret par conteneur.", correction_std),
        (202, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer le coût total d’une opération d’importation.", correction_std),
        (203, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer une marge commerciale.", correction_std),
        (204, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un taux de marge.", correction_std),
        (205, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un taux de marque.", correction_std),
        (206, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer une moyenne de délais de livraison.", correction_std),
        (207, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un taux de dossiers conformes.", correction_std),
        (208, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un taux d’erreurs documentaires.", correction_std),
        (209, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un taux de marchandises contrôlées.", correction_std),
        (210, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Interpréter une série statistique de volumes importés.", correction_std),
        (211, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Déterminer la médiane de délais de dédouanement.", correction_std),
        (212, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Comparer deux fournisseurs à partir de leurs coûts moyens.", correction_std),
        (213, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Construire un tableau de suivi des coûts de transit.", correction_std),
        (214, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer l’écart entre budget et coût réel.", correction_std),
        (215, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer un dépassement budgétaire.", correction_std),
        (216, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Analyser un tableau mensuel d’importations.", correction_std),
        (217, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Construire un graphique d’évolution des volumes.", correction_std),
        (218, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer la productivité d’un service de transit.", correction_std),
        (219, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Déterminer le nombre de dossiers traités par agent.", correction_std),
        (220, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Calculer le délai moyen de traitement.", correction_std),
        (221, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Résoudre un problème de proportion sur des marchandises.", correction_std),
        (222, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Résoudre un problème de conversion de poids.", correction_std),
        (223, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Résoudre un problème de capacité de conteneurs.", correction_std),
        (224, "7. Calculs douaniers, financiers et statistiques — 32 exercices", "Construire un indicateur synthétique de performance.", correction_std),

        # S8 (225-256)
        (225, "8. Anglais professionnel et communication — 32 exercices", "Traduire en français les principaux termes de transit utilisés en anglais.", correction_std),
        (226, "8. Anglais professionnel et communication — 32 exercices", "Définir shipment, consignee, shipper et freight.", correction_std),
        (227, "8. Anglais professionnel et communication — 32 exercices", "Différencier freight prepaid et freight collect.", correction_std),
        (228, "8. Anglais professionnel et communication — 32 exercices", "Expliquer le terme bill of lading.", correction_std),
        (229, "8. Anglais professionnel et communication — 32 exercices", "Expliquer le terme packing list.", correction_std),
        (230, "8. Anglais professionnel et communication — 32 exercices", "Définir customs clearance.", correction_std),
        (231, "8. Anglais professionnel et communication — 32 exercices", "Définir customs declaration.", correction_std),
        (232, "8. Anglais professionnel et communication — 32 exercices", "Définir customs duty.", correction_std),
        (233, "8. Anglais professionnel et communication — 32 exercices", "Définir country of origin.", correction_std),
        (234, "8. Anglais professionnel et communication — 32 exercices", "Définir port of discharge.", correction_std),
        (235, "8. Anglais professionnel et communication — 32 exercices", "Définir port of loading.", correction_std),
        (236, "8. Anglais professionnel et communication — 32 exercices", "Définir place of delivery.", correction_std),
        (237, "8. Anglais professionnel et communication — 32 exercices", "Rédiger un courriel professionnel demandant une facture corrigée.", correction_std),
        (238, "8. Anglais professionnel et communication — 32 exercices", "Rédiger un courriel demandant un connaissement.", correction_std),
        (239, "8. Anglais professionnel et communication — 32 exercices", "Rédiger un courriel signalant un retard de navire.", correction_std),
        (240, "8. Anglais professionnel et communication — 32 exercices", "Rédiger un courriel demandant une date de livraison.", correction_std),
        (241, "8. Anglais professionnel et communication — 32 exercices", "Rédiger une demande de cotation de transport en anglais.", correction_std),
        (242, "8. Anglais professionnel et communication — 32 exercices", "Présenter un dossier d’expédition en anglais simple.", correction_std),
        (243, "8. Anglais professionnel et communication — 32 exercices", "Lire un extrait de facture commerciale et identifier les informations utiles.", correction_std),
        (244, "8. Anglais professionnel et communication — 32 exercices", "Lire une instruction de livraison en anglais et relever les contraintes.", correction_std),
        (245, "8. Anglais professionnel et communication — 32 exercices", "Construire un vocabulaire de vingt termes de transit.", correction_std),
        (246, "8. Anglais professionnel et communication — 32 exercices", "Traduire un court message relatif à une déclaration douanière.", correction_std),
        (247, "8. Anglais professionnel et communication — 32 exercices", "Traduire un message relatif à un conteneur endommagé.", correction_std),
        (248, "8. Anglais professionnel et communication — 32 exercices", "Répondre en anglais à une demande d’information logistique.", correction_std),
        (249, "8. Anglais professionnel et communication — 32 exercices", "Rédiger une relance professionnelle concernant un document manquant.", correction_std),
        (250, "8. Anglais professionnel et communication — 32 exercices", "Expliquer oralement une opération d’importation en anglais simple.", correction_std),
        (251, "8. Anglais professionnel et communication — 32 exercices", "Présenter un incident de livraison en anglais professionnel.", correction_std),
        (252, "8. Anglais professionnel et communication — 32 exercices", "Construire un dialogue entre transitaire et client.", correction_std),
        (253, "8. Anglais professionnel et communication — 32 exercices", "Corriger un courriel professionnel comportant des erreurs.", correction_std),
        (254, "8. Anglais professionnel et communication — 32 exercices", "Transformer un message informel en courriel professionnel.", correction_std),
        (255, "8. Anglais professionnel et communication — 32 exercices", "Rédiger un objet de courriel adapté à une opération de transit.", correction_std),
        (256, "8. Anglais professionnel et communication — 32 exercices", "Présenter les règles de politesse dans un échange commercial international.", correction_std),

        # S9 (257-288)
        (257, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Définir un système d’information logistique.", correction_std),
        (258, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Expliquer l’intérêt de la dématérialisation des documents.", correction_std),
        (259, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Présenter les avantages d’un dossier électronique.", correction_std),
        (260, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Définir une base de données.", correction_std),
        (261, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Expliquer la différence entre donnée et document.", correction_std),
        (262, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Construire une structure simple de base de données pour les expéditions.", correction_std),
        (263, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Identifier les champs nécessaires au suivi d’un conteneur.", correction_std),
        (264, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Créer une fiche numérique de suivi d’un dossier.", correction_std),
        (265, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Expliquer la sauvegarde informatique.", correction_std),
        (266, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Présenter les risques liés à la perte de données.", correction_std),
        (267, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Définir l’authentification.", correction_std),
        (268, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Expliquer l’importance des mots de passe robustes.", correction_std),
        (269, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Présenter les risques du phishing.", correction_std),
        (270, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Identifier un courriel frauduleux dans un scénario.", correction_std),
        (271, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Expliquer les droits d’accès à un dossier numérique.", correction_std),
        (272, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Définir la traçabilité informatique.", correction_std),
        (273, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Présenter l’intérêt d’un historique des modifications.", correction_std),
        (274, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Analyser un cas de double saisie d’une déclaration.", correction_std),
        (275, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Repérer une incohérence dans une base de données de transit.", correction_std),
        (276, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Construire un tableau Excel de suivi des dossiers.", correction_std),
        (277, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Calculer automatiquement un délai de traitement dans un tableur.", correction_std),
        (278, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Créer un indicateur de statut : reçu, en contrôle, validé, clôturé.", correction_std),
        (279, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Proposer une nomenclature de fichiers pour les dossiers d’importation.", correction_std),
        (280, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Construire une procédure d’archivage électronique.", correction_std),
        (281, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Analyser une panne informatique avant une opération urgente.", correction_std),
        (282, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Proposer un plan de continuité documentaire.", correction_std),
        (283, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Présenter les règles de confidentialité des données clients.", correction_std),
        (284, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Expliquer les risques d’une clé USB inconnue.", correction_std),
        (285, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Construire une checklist de sécurité informatique pour un transitaire.", correction_std),
        (286, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Analyser un problème de doublon dans un système de suivi.", correction_std),
        (287, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Proposer une méthode de contrôle qualité des données.", correction_std),
        (288, "9. Informatique, systèmes et traçabilité du transit — 32 exercices", "Présenter les bénéfices et limites de la digitalisation du transit.", correction_std),

        # S10 (289-320)
        (289, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser un dossier d’importation dont la facture et la packing list ne concordent pas.", correction_std),
        (290, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Traiter un dossier de transit avec un scellé endommagé.", correction_std),
        (291, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser une marchandise dont le code tarifaire est incertain.", correction_std),
        (292, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire le plan d’action après découverte d’une erreur de déclaration.", correction_std),
        (293, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Calculer le coût rendu d’une importation à partir de données fournies.", correction_std),
        (294, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Choisir un Incoterm adapté à une opération fictive et justifier le choix.", correction_std),
        (295, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire le circuit documentaire complet d’une importation maritime.", correction_std),
        (296, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire le circuit documentaire complet d’une exportation.", correction_std),
        (297, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser un retard de livraison et identifier ses causes.", correction_std),
        (298, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Proposer un plan de réduction des délais de dédouanement.", correction_std),
        (299, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser une facture internationale comportant plusieurs incohérences.", correction_std),
        (300, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Contrôler un dossier de conteneur avant enlèvement.", correction_std),
        (301, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire un tableau de bord mensuel d’une entreprise de transit.", correction_std),
        (302, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Calculer les principaux indicateurs de performance d’un service.", correction_std),
        (303, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser une hausse des coûts de transport et proposer des mesures.", correction_std),
        (304, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire une procédure de traitement d’un litige documentaire.", correction_std),
        (305, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Rédiger une réponse professionnelle à un client mécontent.", correction_std),
        (306, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Rédiger une note interne sur une erreur de déclaration.", correction_std),
        (307, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Préparer un dossier pour une réunion avec un transporteur.", correction_std),
        (308, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser une offre de transport et comparer deux propositions.", correction_std),
        (309, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire un plan de suivi d’une expédition urgente.", correction_std),
        (310, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Organiser les priorités d’un transitaire ayant dix dossiers simultanés.", correction_std),
        (311, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser un risque de fraude documentaire et proposer des contrôles.", correction_std),
        (312, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Proposer des mesures contre la sous-évaluation des marchandises.", correction_std),
        (313, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire une procédure de vérification avant transmission à la douane.", correction_std),
        (314, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser une opération de groupage et répartir les coûts.", correction_std),
        (315, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Calculer la capacité disponible d’un camion pour plusieurs colis.", correction_std),
        (316, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Optimiser une tournée de livraison entre cinq clients.", correction_std),
        (317, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire un plan de continuité en cas de blocage frontalier.", correction_std),
        (318, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Analyser une opération de transit non apurée et proposer les vérifications.", correction_std),
        (319, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Rédiger un compte rendu d’incident logistique.", correction_std),
        (320, "10. Cas pratiques intégrés et gestion professionnelle — 32 exercices", "Construire une checklist finale de conformité d’une opération de transit.", correction_std)
    ]

    exercises = [{"id": q[0], "section": q[1], "question": f"Exercice {q[0]}. {q[2]}", "answer": q[3]} for q in q_list]

    sims = [
        {"title": "Concours blanc 1 — Douane et déclaration", "items": [
            {"num": 1, "text": "Construire un dossier complet de déclaration à partir d’informations fictives."},
            {"num": 2, "text": "Identifier les erreurs dans une déclaration douanière."},
            {"num": 3, "text": "Calculer une base taxable et les prélèvements correspondants à partir de données fournies."},
            {"num": 4, "text": "Analyser un problème de classement tarifaire."},
            {"num": 5, "text": "Analyser un problème d’origine de marchandise."},
            {"num": 6, "text": "Proposer une procédure de contrôle documentaire."},
            {"num": 7, "text": "Analyser un cas de sous-évaluation."},
            {"num": 8, "text": "Rédiger une note professionnelle de conformité."}
        ]},
        {"title": "Concours blanc 2 — Transit et transport", "items": [
            {"num": 1, "text": "Construire le circuit complet d’un camion en transit."},
            {"num": 2, "text": "Analyser un transit non apuré."},
            {"num": 3, "text": "Traiter un incident de scellé."},
            {"num": 4, "text": "Calculer le coût d’une opération de transport."},
            {"num": 5, "text": "Optimiser une tournée de livraison."},
            {"num": 6, "text": "Construire un tableau de suivi des expéditions."},
            {"num": 7, "text": "Analyser un retard de livraison."},
            {"num": 8, "text": "Proposer un plan correctif."}
        ]},
        {"title": "Concours blanc 3 — Commerce international", "items": [
            {"num": 1, "text": "Analyser une facture commerciale internationale."},
            {"num": 2, "text": "Choisir et justifier un Incoterm."},
            {"num": 3, "text": "Calculer un coût rendu."},
            {"num": 4, "text": "Contrôler une packing list."},
            {"num": 5, "text": "Contrôler un connaissement."},
            {"num": 6, "text": "Analyser un risque de paiement international."},
            {"num": 7, "text": "Construire une checklist d’importation."},
            {"num": 8, "text": "Rédiger un courriel professionnel au fournisseur."}
        ]},
        {"title": "Concours blanc 4 — Épreuve intégrée BTS Transit", "items": [
            {"num": 1, "text": "Traiter une opération maritime complète depuis la commande jusqu’à la livraison."},
            {"num": 2, "text": "Identifier les documents manquants dans un dossier."},
            {"num": 3, "text": "Calculer les coûts et délais de l’opération."},
            {"num": 4, "text": "Analyser une anomalie douanière."},
            {"num": 5, "text": "Proposer une solution à un retard portuaire."},
            {"num": 6, "text": "Construire un tableau de bord du dossier."},
            {"num": 7, "text": "Analyser un risque de fraude documentaire."},
            {"num": 8, "text": "Rédiger le compte rendu final de l’opération."}
        ]}
    ]

    plan = [
        {"period": "J1–J3", "task": "douane, territoire douanier et déclaration."},
        {"period": "J4–J6", "task": "classement tarifaire, origine et valeur en douane."},
        {"period": "J7–J9", "task": "transit douanier, garanties, délais et apurement."},
        {"period": "J10–J12", "task": "transport routier et opérations frontalières."},
        {"period": "J13–J15", "task": "transport maritime, port, conteneurs et connaissement."},
        {"period": "J16–J18", "task": "commerce international et Incoterms."},
        {"period": "J19–J21", "task": "documents commerciaux et contrôle documentaire."},
        {"period": "J22–J24", "task": "logistique, stocks, coûts et indicateurs."},
        {"period": "J25–J26", "task": "calculs professionnels et statistiques."},
        {"period": "J27", "task": "anglais professionnel du transit."},
        {"period": "J28", "task": "informatique, traçabilité et sécurité des données."},
        {"period": "J29", "task": "concours blanc chronométré + correction."},
        {"period": "J30", "task": "révision des erreurs, documents, formules et procédures."}
    ]

    return {
        "id": "annale-bts-transit-sn",
        "title": "ANNALES CONCOURS AU SÉNÉGAL",
        "subtitle": "BTS TRANSIT — TOME 1",
        "total_exercises": 320,
        "headerText": "BTS Transit — Tome 1",
        "footerFormat": "{headerText} | Page {pageNum}",
        "intro": "320 exercices distincts • douane, transit, transport, commerce international et logistique\n\nFascicule reconstruit avec davantage de contenu technique et de cas pratiques.",
        "official_reference": "Les 320 sujets principaux sont distincts. Ils couvrent les compétences techniques du BTS Transit : douane, transit, transport maritime et routier, commerce international, documents, calculs, anglais professionnel, informatique et gestion des opérations.",
        "summary_sections": sections,
        "exercises": exercises,
        "exam_simulations": sims,
        "study_plan": plan,
        "quality_control": "Contrôle qualité : 320 exercices principaux, 320 énoncés distincts, 10 domaines, 4 concours blancs et 30 jours de préparation."
    }
