# CREM — FASCICULE COMPLET DE PRÉPARATION data
def get_crem():
    sections = [
        {"title": "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "count": 32, "description": "Compétences, objectifs, progressions, évaluations, remédiation, différenciation et métacognition."},
        {"title": "2. Français, expression et communication — 32 exercices", "count": 32, "description": "Grammaire, accords, synthèse, dissertation, registre de langue et communication."},
        {"title": "3. Mathématiques et raisonnement — 32 exercices", "count": 32, "description": "Équations, pourcentages, géométrie, statistiques, probabilités et calculs appliqués."},
        {"title": "4. Sciences, environnement et santé de l’enfant — 32 exercices", "count": 32, "description": "Physiologie, écosystèmes, nutrition, hygiène, secourisme et santé scolaire."},
        {"title": "5. Histoire, géographie et culture générale — 32 exercices", "count": 32, "description": "Sahel, Dakar, urbanisation, développement durable, citoyenneté et patrimoine."},
        {"title": "6. Psychologie de l’enfant et développement — 32 exercices", "count": 32, "description": "Développement cognitif, attention, motivation, inclusion, relations pairs et autonomie."},
        {"title": "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "count": 32, "description": "Climat scolaire, règles, harcèlement, aménagement, projet d'école et médiation."},
        {"title": "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "count": 32, "description": "Service public, valeurs républicaines, prévention sanitaire et éducation aux médias."},
        {"title": "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "count": 32, "description": "Gestion du temps, oral, gestion des conflits, déontologie et révision ciblée."},
        {"title": "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "count": 32, "description": "Réunions, partenariats, posture professionnelle, sorties scolaires et formation continue."}
    ]

    q_data = [
        (1, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Définissez une compétence professionnelle de l’enseignant.", "Capacité à mobiliser des savoirs, savoir-faire et attitudes pour agir efficacement en situation."),
        (2, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Distinguez pédagogie et didactique.", "La pédagogie concerne notamment la relation et les conditions d’apprentissage; la didactique porte sur l’enseignement des savoirs."),
        (3, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Qu’est-ce qu’un objectif opérationnel?", "Un résultat formulé de manière observable et vérifiable."),
        (4, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "À quoi sert une progression annuelle?", "À organiser les apprentissages sur l’ensemble de l’année selon une logique et des priorités."),
        (5, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Définissez une séquence d’enseignement.", "Ensemble cohérent de séances visant des apprentissages déterminés."),
        (6, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi analyser les prérequis?", "Pour identifier les acquis nécessaires et anticiper les difficultés."),
        (7, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Qu’est-ce qu’une évaluation diagnostique?", "Une évaluation réalisée avant ou au début d’un apprentissage pour connaître le niveau initial."),
        (8, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Quel est le rôle d’une évaluation formative?", "Fournir des informations pendant l’apprentissage afin d’ajuster l’enseignement."),
        (9, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Qu’est-ce qu’une évaluation sommative?", "Une évaluation réalisée à un moment donné pour établir un bilan des acquis."),
        (10, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Définissez la remédiation pédagogique.", "Ensemble d’actions ciblées destinées à traiter une difficulté identifiée."),
        (11, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi varier les supports?", "Pour mobiliser différentes formes de représentation et répondre à la diversité des élèves."),
        (12, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Comment formuler une consigne efficace?", "Indiquer clairement l’action attendue, la production et les contraintes essentielles."),
        (13, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi faire verbaliser une procédure?", "Pour rendre le raisonnement visible et permettre sa régulation."),
        (14, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Définissez différenciation pédagogique.", "Adaptation des démarches, supports, aides ou niveaux de guidage selon les besoins."),
        (15, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Qu’est-ce qu’une situation-problème?", "Une situation qui place l’élève devant un problème nécessitant recherche et mobilisation de ressources."),
        (16, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi l’erreur peut-elle être formatrice?", "Elle permet d’identifier les conceptions et stratégies à corriger."),
        (17, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Définissez métacognition.", "Capacité à réfléchir sur ses connaissances, stratégies et processus d’apprentissage."),
        (18, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Comment favoriser l’autonomie?", "Donner des outils de planification, des critères et progressivement moins d’aide."),
        (19, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi alterner activités individuelles et collectives?", "Pour développer à la fois autonomie, coopération et verbalisation."),
        (20, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Comment construire une grille d’évaluation?", "Définir critères, indicateurs et niveaux de réussite."),
        (21, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi annoncer les critères de réussite?", "Pour rendre les attentes transparentes et faciliter l’autoévaluation."),
        (22, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Qu’est-ce qu’un prérequis?", "Connaissance ou compétence nécessaire avant un nouvel apprentissage."),
        (23, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Comment traiter une difficulté persistante?", "Observer, diagnostiquer la cause, proposer une remédiation puis réévaluer."),
        (24, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi utiliser le questionnement?", "Pour faire émerger connaissances, raisonnements et incompréhensions."),
        (25, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Définissez apprentissage coopératif.", "Organisation dans laquelle les élèves travaillent ensemble avec des responsabilités partagées."),
        (26, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Quel risque existe dans un travail de groupe?", "Une participation inégale; il faut attribuer des rôles et vérifier les productions."),
        (27, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi utiliser des exemples et contre-exemples?", "Pour préciser les caractéristiques d’un concept et ses limites."),
        (28, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Comment favoriser le transfert?", "Faire réutiliser une notion ou compétence dans des situations nouvelles."),
        (29, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Qu’est-ce qu’une progression spiralaire?", "Retour progressif sur une notion avec approfondissement et complexification."),
        (30, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Pourquoi prévoir une synthèse de séance?", "Pour sélectionner, organiser et stabiliser les acquis essentiels."),
        (31, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Comment gérer une classe hétérogène?", "Maintenir des objectifs communs tout en adaptant supports, aides et tâches."),
        (32, "1. Pédagogie, psychologie de l’apprentissage et didactique — 32 exercices", "Quel est le rôle du feedback?", "Indiquer les acquis, les écarts et les pistes concrètes de progression."),

        (33, "2. Français, expression et communication — 32 exercices", "Corrigez : « Les élèves que j’ai rencontré ».", "Les élèves que j’ai rencontrés."),
        (34, "2. Français, expression et communication — 32 exercices", "Expliquez l’accord dans « les leçons qu’elle a préparées ».", "Le COD « les leçons », placé avant le verbe, commande l’accord du participe passé."),
        (35, "2. Français, expression et communication — 32 exercices", "Nature de « puisque »?", "Conjonction de subordination exprimant généralement la cause."),
        (36, "2. Français, expression et communication — 32 exercices", "Fonction de « aux candidats » dans « parler aux candidats »?", "Complément d’objet indirect."),
        (37, "2. Français, expression et communication — 32 exercices", "Transformez au discours indirect : Il dit : « Je réussis ».", "Il dit qu’il réussit."),
        (38, "2. Français, expression et communication — 32 exercices", "Mettez à la voix passive : « Le maître explique la règle ».", "La règle est expliquée par le maître."),
        (39, "2. Français, expression et communication — 32 exercices", "Définissez une thèse.", "Position ou idée principale défendue dans un raisonnement."),
        (40, "2. Français, expression et communication — 32 exercices", "Distinguez argument et exemple.", "L’argument justifie une idée; l’exemple l’illustre."),
        (41, "2. Français, expression et communication — 32 exercices", "Qu’est-ce qu’une problématique?", "Question directrice précise qui organise une réflexion."),
        (42, "2. Français, expression et communication — 32 exercices", "Que doit contenir une introduction de dissertation?", "Amorce, cadrage des termes, problématique et annonce du plan."),
        (43, "2. Français, expression et communication — 32 exercices", "Distinguez résumé et compte rendu.", "Le résumé condense un texte; le compte rendu présente le contenu et peut en organiser les principaux aspects."),
        (44, "2. Français, expression et communication — 32 exercices", "Définissez champ lexical.", "Ensemble de mots associés à un même domaine de sens."),
        (45, "2. Français, expression et communication — 32 exercices", "Identifiez la figure dans « la classe est un laboratoire ».", "Métaphore."),
        (46, "2. Français, expression et communication — 32 exercices", "Quel est le rôle d’une transition?", "Relier logiquement deux étapes du raisonnement."),
        (47, "2. Français, expression et communication — 32 exercices", "Définissez connecteur logique.", "Mot ou groupe de mots indiquant une relation entre idées."),
        (48, "2. Français, expression et communication — 32 exercices", "Donnez un connecteur de concession.", "Cependant, pourtant, bien que, quoique."),
        (49, "2. Français, expression et communication — 32 exercices", "Donnez un connecteur de conséquence.", "Donc, ainsi, par conséquent."),
        (50, "2. Français, expression et communication — 32 exercices", "Pourquoi éviter les phrases trop longues?", "Elles peuvent nuire à la clarté et à la lisibilité."),
        (51, "2. Français, expression et communication — 32 exercices", "Comment réussir une synthèse?", "Sélectionner les idées communes, les organiser et les reformuler sans copier."),
        (52, "2. Français, expression et communication — 32 exercices", "Qu’est-ce qu’un registre de langue?", "Manière de s’exprimer adaptée à une situation et à un niveau de formalité."),
        (53, "2. Français, expression et communication — 32 exercices", "Définissez communication non verbale.", "Transmission d’informations par posture, gestes, regard, expression ou distance."),
        (54, "2. Français, expression et communication — 32 exercices", "Pourquoi reformuler une réponse d’élève?", "Pour vérifier la compréhension et clarifier le sens."),
        (55, "2. Français, expression et communication — 32 exercices", "Comment poser une question ouverte?", "En sollicitant une explication, justification, comparaison ou proposition plutôt qu’une réponse oui/non."),
        (56, "2. Français, expression et communication — 32 exercices", "Corrigez : « Malgré qu’il soit absent ».", "On peut écrire « bien qu’il soit absent » ou « malgré son absence »."),
        (57, "2. Français, expression et communication — 32 exercices", "Transformez « Il faut que les élèves travaillent » en tournure infinitive.", "Il faut que les élèves travaillent peut devenir « Les élèves doivent travailler »."),
        (58, "2. Français, expression et communication — 32 exercices", "Définissez l’ironie.", "Procédé fondé sur un décalage entre le sens apparent et l’intention."),
        (59, "2. Français, expression et communication — 32 exercices", "Qu’est-ce qu’une paraphrase?", "Reformulation d’une idée avec d’autres mots."),
        (60, "2. Français, expression et communication — 32 exercices", "Pourquoi citer une source?", "Pour identifier l’origine de l’information et permettre sa vérification."),
        (61, "2. Français, expression et communication — 32 exercices", "Définissez plagiat.", "Présenter une production ou une idée d’autrui comme son propre travail."),
        (62, "2. Français, expression et communication — 32 exercices", "Comment améliorer un paragraphe argumentatif?", "Une idée directrice, une justification, un exemple et une phrase de liaison."),
        (63, "2. Français, expression et communication — 32 exercices", "Quel est le rôle d’une conclusion?", "Répondre à la problématique et dégager l’essentiel du raisonnement."),
        (64, "2. Français, expression et communication — 32 exercices", "Pourquoi adapter son vocabulaire au public?", "Pour rendre le message compréhensible et approprié à la situation."),

        (65, "3. Mathématiques et raisonnement — 32 exercices", "Résolvez 4x+5=29.", "x=6."),
        (66, "3. Mathématiques et raisonnement — 32 exercices", "Calculez 18 % de 250.", "45."),
        (67, "3. Mathématiques et raisonnement — 32 exercices", "Une classe compte 32 élèves dont 20 filles. Quel pourcentage de filles?", "62,5 %."),
        (68, "3. Mathématiques et raisonnement — 32 exercices", "Résolvez 2x−7=15.", "x=11."),
        (69, "3. Mathématiques et raisonnement — 32 exercices", "Factorisez x²−16.", "(x−4)(x+4)."),
        (70, "3. Mathématiques et raisonnement — 32 exercices", "Résolvez x²−7x+12=0.", "x=3 ou x=4."),
        (71, "3. Mathématiques et raisonnement — 32 exercices", "Calculez la moyenne de 10, 12, 15, 17 et 21.", "15."),
        (72, "3. Mathématiques et raisonnement — 32 exercices", "Une note passe de 12 à 15. Quel est le taux d’augmentation?", "25 %."),
        (73, "3. Mathématiques et raisonnement — 32 exercices", "Un article de 20 000 F bénéficie d’une remise de 15 %. Prix final?", "17 000 F."),
        (74, "3. Mathématiques et raisonnement — 32 exercices", "Convertissez 3,5 km en mètres.", "3 500 m."),
        (75, "3. Mathématiques et raisonnement — 32 exercices", "Convertissez 2,4 L en mL.", "2 400 mL."),
        (76, "3. Mathématiques et raisonnement — 32 exercices", "Aire d’un rectangle de 12 m sur 7 m?", "84 m²."),
        (77, "3. Mathématiques et raisonnement — 32 exercices", "Périmètre du même rectangle?", "38 m."),
        (78, "3. Mathématiques et raisonnement — 32 exercices", "Aire d’un triangle de base 10 cm et hauteur 8 cm?", "40 cm²."),
        (79, "3. Mathématiques et raisonnement — 32 exercices", "Un véhicule parcourt 180 km en 4 h. Vitesse moyenne?", "45 km/h."),
        (80, "3. Mathématiques et raisonnement — 32 exercices", "Convertissez 90 km/h en m/s.", "25 m/s."),
        (81, "3. Mathématiques et raisonnement — 32 exercices", "Probabilité d’obtenir un nombre supérieur à 4 avec un dé équilibré?", "2/6 = 1/3."),
        (82, "3. Mathématiques et raisonnement — 32 exercices", "Une urne contient 5 boules rouges et 3 bleues. Probabilité d’une rouge?", "5/8."),
        (83, "3. Mathématiques et raisonnement — 32 exercices", "Résolvez 3(x+2)=21.", "x=5."),
        (84, "3. Mathématiques et raisonnement — 32 exercices", "Si f(x)=3x−2, calculez f(8).", "22."),
        (85, "3. Mathématiques et raisonnement — 32 exercices", "Suite u_n=2n+5. Calculez u_12.", "29."),
        (86, "3. Mathématiques et raisonnement — 32 exercices", "Quelle est la médiane de 4, 7, 8, 12, 15?", "8."),
        (87, "3. Mathématiques et raisonnement — 32 exercices", "Quel est le mode de 2, 4, 4, 5, 7, 4?", "4."),
        (88, "3. Mathématiques et raisonnement — 32 exercices", "Une classe passe de 25 à 30 élèves. Variation absolue?", "5 élèves."),
        (89, "3. Mathématiques et raisonnement — 32 exercices", "Même situation : variation relative?", "20 %."),
        (90, "3. Mathématiques et raisonnement — 32 exercices", "Calculez 3/4 + 5/8.", "11/8."),
        (91, "3. Mathématiques et raisonnement — 32 exercices", "Calculez 2/3 × 9/4.", "3/2."),
        (92, "3. Mathématiques et raisonnement — 32 exercices", "Résolvez 5/x=2.", "x=2,5."),
        (93, "3. Mathématiques et raisonnement — 32 exercices", "Un capital de 100 000 F augmente de 8 %. Montant?", "108 000 F."),
        (94, "3. Mathématiques et raisonnement — 32 exercices", "Moyenne pondérée : 10 coefficient 2 et 16 coefficient 3.", "13,6."),
        (95, "3. Mathématiques et raisonnement — 32 exercices", "Un triangle rectangle a des côtés 6 et 8. Hypoténuse?", "10."),
        (96, "3. Mathématiques et raisonnement — 32 exercices", "Pourquoi vérifier l’ordre de grandeur d’un résultat?", "Pour détecter une erreur de calcul ou d’unité."),

        (97, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Rôle principal du cœur?", "Propulser le sang dans la circulation."),
        (98, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Rôle des globules rouges?", "Transporter principalement l’oxygène."),
        (99, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Où se produisent les échanges gazeux pulmonaires?", "Au niveau des alvéoles."),
        (100, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Rôle des reins?", "Filtrer le sang et participer à la régulation de l’eau et des ions."),
        (101, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez écosystème.", "Ensemble des êtres vivants, du milieu et de leurs interactions."),
        (102, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Rôle des décomposeurs?", "Dégrader la matière organique et contribuer au recyclage des éléments."),
        (103, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi protéger la biodiversité?", "Elle soutient des fonctions écologiques et la résilience des écosystèmes."),
        (104, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez chaîne alimentaire.", "Suite de relations trophiques montrant le transfert de matière et d’énergie."),
        (105, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Qu’est-ce qu’une ressource renouvelable?", "Ressource pouvant se reconstituer à une échelle compatible avec son usage."),
        (106, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez pollution de l’eau.", "Introduction de substances ou agents dégradant la qualité de l’eau."),
        (107, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi l’eau potable doit-elle être contrôlée?", "Pour limiter les risques sanitaires."),
        (108, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Rôle du lavage des mains?", "Réduire la transmission de microorganismes."),
        (109, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez nutrition équilibrée.", "Apport diversifié et adapté en énergie et nutriments."),
        (110, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi le sommeil est-il important chez l’enfant?", "Il contribue à la croissance, récupération et consolidation des apprentissages."),
        (111, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Quel est le rôle du calcium?", "Notamment la formation et l’entretien des os et des dents."),
        (112, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi l’activité physique est-elle importante?", "Elle contribue au développement moteur et à la santé."),
        (113, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez vaccination.", "Prévention visant à préparer le système immunitaire contre un agent ou antigène."),
        (114, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Différence entre infection et maladie?", "Une infection correspond à la présence et multiplication d’un agent; la maladie implique des manifestations cliniques."),
        (115, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez fièvre.", "Élévation régulée de la température corporelle lors d’une réponse physiologique."),
        (116, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi ventiler une salle de classe?", "Pour renouveler l’air et réduire l’accumulation de certains polluants."),
        (117, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez changement climatique.", "Modification durable des caractéristiques climatiques sur des périodes longues."),
        (118, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Deux conséquences possibles de la sécheresse?", "Baisse des ressources en eau et pertes agricoles."),
        (119, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi planter des arbres peut-il aider les sols?", "Les racines limitent l’érosion et la végétation améliore la couverture du sol."),
        (120, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez photosynthèse.", "Processus par lequel les végétaux chlorophylliens produisent de la matière organique grâce à la lumière."),
        (121, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Quel gaz les plantes utilisent-elles dans la photosynthèse?", "Le dioxyde de carbone."),
        (122, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez cycle de l’eau.", "Circulation de l’eau entre atmosphère, surfaces, sols et réservoirs."),
        (123, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi l’alimentation scolaire doit-elle être diversifiée?", "Pour couvrir les besoins nutritionnels et soutenir le développement."),
        (124, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Comment prévenir les accidents en classe?", "Identifier les risques, organiser l’espace et expliquer les règles."),
        (125, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi apprendre les gestes de premiers secours?", "Pour réagir rapidement et protéger une personne en attendant les secours."),
        (126, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Définissez hygiène collective.", "Ensemble des pratiques visant à protéger la santé d’un groupe."),
        (127, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi l’environnement influence-t-il la santé?", "Air, eau, alimentation, habitat et conditions de vie peuvent modifier les risques."),
        (128, "4. Sciences, environnement et santé de l’enfant — 32 exercices", "Pourquoi une cour de récréation doit-elle être organisée avec des règles de sécurité?", "Pour réduire les risques d’accident tout en permettant une activité adaptée aux enfants."),

        (129, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez le Sahel.", "Bande de transition semi-aride au sud du Sahara."),
        (130, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi Dakar constitue-t-elle un pôle majeur?", "Elle concentre des fonctions administratives, économiques, universitaires et de transport."),
        (131, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez densité de population.", "Nombre d’habitants par unité de surface."),
        (132, "5. Histoire, géographie et culture générale — 32 exercices", "Distinguez migration interne et internationale.", "La première reste dans le pays; la seconde franchit une frontière."),
        (133, "5. Histoire, géographie et culture générale — 32 exercices", "Qu’est-ce que l’urbanisation?", "Croissance de la population urbaine et transformation des espaces."),
        (134, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi le littoral est-il stratégique?", "Il concentre des activités portuaires, halieutiques, touristiques et urbaines."),
        (135, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez désertification.", "Dégradation des terres dans les zones sèches sous influences climatiques et humaines."),
        (136, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi les mangroves sont-elles importantes?", "Elles protègent les côtes, abritent des espèces et soutiennent des activités."),
        (137, "5. Histoire, géographie et culture générale — 32 exercices", "Climat et météo : différence?", "La météo décrit le court terme; le climat les caractéristiques sur une longue durée."),
        (138, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi recenser une population?", "Pour connaître sa structure et planifier les politiques publiques."),
        (139, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez bassin versant.", "Territoire dont les eaux convergent vers un même exutoire."),
        (140, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi les transports structurent-ils les territoires?", "Ils facilitent les flux et renforcent certains pôles."),
        (141, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez développement durable.", "Répondre aux besoins présents en préservant les possibilités futures."),
        (142, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi créer des aires protégées?", "Conserver habitats, espèces et fonctions écologiques."),
        (143, "5. Histoire, géographie et culture générale — 32 exercices", "Deux effets possibles de l’érosion côtière?", "Recul du rivage et dommages aux infrastructures."),
        (144, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez métropole.", "Grande ville exerçant des fonctions de commandement et d’attraction."),
        (145, "5. Histoire, géographie et culture générale — 32 exercices", "Qu’est-ce qu’une carte thématique?", "Carte représentant un phénomène particulier."),
        (146, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi gérer durablement les ressources en eau?", "Parce que plusieurs usages dépendent d’une ressource limitée."),
        (147, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez citoyenneté.", "Statut comportant droits, devoirs et participation à la vie collective."),
        (148, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi l’histoire est-elle utile à l’enseignant?", "Elle développe compréhension du temps, contextualisation et esprit critique."),
        (149, "5. Histoire, géographie et culture générale — 32 exercices", "Distinguez source primaire et secondaire.", "La source primaire provient directement de la période étudiée; la secondaire l’analyse."),
        (150, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi confronter plusieurs sources historiques?", "Pour comparer les informations et leurs points de vue."),
        (151, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez patrimoine culturel.", "Biens, pratiques et savoirs reconnus comme héritage culturel."),
        (152, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi valoriser les langues nationales dans l’éducation?", "Elles peuvent soutenir compréhension, identité et transmission culturelle."),
        (153, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez mobilité.", "Déplacement de personnes entre différents lieux."),
        (154, "5. Histoire, géographie et culture générale — 32 exercices", "Effet d’une forte croissance urbaine sans planification?", "Pressions sur logement, transport, assainissement et services."),
        (155, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi étudier les activités économiques locales?", "Pour comprendre les ressources, emplois et dynamiques territoriales."),
        (156, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez frontière.", "Limite politique séparant des territoires."),
        (157, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi les risques naturels doivent-ils être intégrés à l’aménagement?", "Pour réduire l’exposition et la vulnérabilité."),
        (158, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez transition démographique.", "Évolution d’un régime de forte natalité et mortalité vers des niveaux plus faibles."),
        (159, "5. Histoire, géographie et culture générale — 32 exercices", "Pourquoi l’éducation contribue-t-elle au développement humain?", "Elle élargit connaissances, compétences et possibilités d’action."),
        (160, "5. Histoire, géographie et culture générale — 32 exercices", "Définissez esprit critique.", "Capacité à examiner preuves, sources, arguments et incertitudes."),

        (161, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez développement cognitif.", "Évolution des capacités de perception, mémoire, raisonnement et résolution de problèmes."),
        (162, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi l’attention est-elle essentielle à l’apprentissage?", "Elle permet de sélectionner et traiter les informations pertinentes."),
        (163, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez mémoire de travail.", "Système permettant de maintenir et manipuler temporairement des informations."),
        (164, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi fractionner une consigne complexe?", "Pour diminuer la charge cognitive et sécuriser les étapes."),
        (165, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez motivation intrinsèque.", "Engagement suscité principalement par l’intérêt ou la satisfaction de l’activité."),
        (166, "6. Psychologie de l’enfant et développement — 32 exercices", "Motivation extrinsèque?", "Engagement influencé par une récompense, une conséquence ou une pression extérieure."),
        (167, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi valoriser l’effort et les stratégies?", "Cela favorise une perception dynamique des progrès."),
        (168, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez estime de soi.", "Évaluation qu’une personne fait de sa propre valeur."),
        (169, "6. Psychologie de l’enfant et développement — 32 exercices", "Comment soutenir un enfant qui craint l’erreur?", "Créer un climat sécurisé, valoriser les essais et utiliser l’erreur pour apprendre."),
        (170, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi le jeu peut-il être pédagogique?", "Il permet exploration, langage, règles, coopération et résolution de problèmes."),
        (171, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez socialisation.", "Processus d’acquisition des normes, valeurs, rôles et comportements sociaux."),
        (172, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi les interactions entre pairs sont-elles utiles?", "Elles favorisent langage, coopération et confrontation des points de vue."),
        (173, "6. Psychologie de l’enfant et développement — 32 exercices", "Qu’est-ce qu’un conflit socio-cognitif?", "Situation où la confrontation de points de vue pousse à réorganiser le raisonnement."),
        (174, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez autorégulation.", "Capacité à planifier, surveiller et ajuster son activité."),
        (175, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi enseigner des stratégies de mémorisation?", "Pour rendre l’apprentissage plus efficace et autonome."),
        (176, "6. Psychologie de l’enfant et développement — 32 exercices", "Qu’est-ce qu’une représentation initiale?", "Conception que l’apprenant possède avant un enseignement."),
        (177, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi identifier les représentations initiales?", "Pour construire l’enseignement à partir des conceptions existantes."),
        (178, "6. Psychologie de l’enfant et développement — 32 exercices", "Comment favoriser le langage oral?", "Questions ouvertes, reformulation, échanges structurés et récits."),
        (179, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi la répétition espacée est-elle utile?", "Elle renforce la récupération des connaissances dans le temps."),
        (180, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez transfert d’apprentissage.", "Utilisation d’un acquis dans une nouvelle situation."),
        (181, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi varier les contextes d’exercice?", "Pour éviter un apprentissage limité à un seul modèle."),
        (182, "6. Psychologie de l’enfant et développement — 32 exercices", "Comment aider un élève impulsif?", "Règles courtes, anticipation, tâches découpées et feedback immédiat."),
        (183, "6. Psychologie de l’enfant et développement — 32 exercices", "Comment soutenir un élève très lent?", "Analyser la cause, ajuster la quantité de travail et accorder des aides adaptées."),
        (184, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi éviter les comparaisons humiliantes?", "Elles peuvent détériorer motivation, confiance et relation éducative."),
        (185, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez inclusion.", "Organisation permettant la participation et les apprentissages de tous."),
        (186, "6. Psychologie de l’enfant et développement — 32 exercices", "Égalité et équité?", "Même traitement contre adaptation des moyens selon les besoins."),
        (187, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi la relation enseignant-élève compte-t-elle?", "Elle influence climat, engagement et sécurité psychologique."),
        (188, "6. Psychologie de l’enfant et développement — 32 exercices", "Comment repérer une difficulté sans diagnostiquer soi-même?", "Observer des faits, documenter et orienter vers les professionnels compétents."),
        (189, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi associer les familles?", "Pour partager informations et soutenir la continuité éducative."),
        (190, "6. Psychologie de l’enfant et développement — 32 exercices", "Définissez empathie professionnelle.", "Comprendre le point de vue d’autrui tout en conservant le cadre professionnel."),
        (191, "6. Psychologie de l’enfant et développement — 32 exercices", "Pourquoi respecter le rythme de développement?", "Pour adapter les attentes aux capacités et éviter des exigences inappropriées."),
        (192, "6. Psychologie de l’enfant et développement — 32 exercices", "Comment encourager l’autonomie?", "Donner choix encadrés, outils et responsabilités progressives."),

        (193, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Définissez climat scolaire.", "Qualité des relations, sécurité, règles et conditions de vie et d’apprentissage dans l’établissement."),
        (194, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi établir des règles de classe?", "Pour sécuriser les interactions et rendre les attentes prévisibles."),
        (195, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Comment construire une règle avec les élèves?", "Clarifier son objectif, son contenu et ses conséquences dans le cadre institutionnel."),
        (196, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi la cohérence éducative est-elle importante?", "Des règles stables rendent les comportements attendus plus lisibles."),
        (197, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Définissez discrimination.", "Traitement défavorable fondé sur un critère interdit ou illégitime."),
        (198, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Comment prévenir les discriminations?", "Règles explicites, vigilance, sensibilisation et traitement équitable."),
        (199, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Qu’est-ce que le harcèlement scolaire?", "Répétition de comportements hostiles ou humiliants créant un déséquilibre et une souffrance."),
        (200, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Que faire face à un signalement de harcèlement?", "Protéger, recueillir les faits, alerter selon les procédures et assurer le suivi."),
        (201, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi l’inclusion concerne-t-elle toute l’école?", "Elle implique pédagogie, organisation, accessibilité et culture collective."),
        (202, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Qu’est-ce qu’un aménagement pédagogique?", "Adaptation permettant à un élève d’accéder aux apprentissages sans modifier nécessairement l’objectif essentiel."),
        (203, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi travailler avec une équipe éducative?", "Pour croiser les observations et coordonner les réponses."),
        (204, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Définissez projet d’école.", "Cadre collectif fixant des priorités et actions adaptées au contexte de l’établissement."),
        (205, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi analyser les besoins du milieu?", "Pour construire des actions pertinentes et réalistes."),
        (206, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Qu’est-ce qu’une communauté éducative?", "Ensemble des acteurs contribuant à la vie et à la mission éducative de l’établissement."),
        (207, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi la participation des parents peut-elle être utile?", "Elle soutient le suivi et la coopération autour de l’enfant."),
        (208, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Comment gérer un désaccord avec un parent?", "Écouter, rester factuel, rappeler le cadre et rechercher une solution conforme aux règles."),
        (209, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi protéger la confidentialité?", "Pour respecter la vie privée et les obligations professionnelles."),
        (210, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Définissez responsabilité professionnelle.", "Obligation d’agir conformément aux missions, règles et principes de son métier."),
        (211, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi tenir des traces de suivi?", "Pour objectiver les évolutions et assurer la continuité."),
        (212, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Comment conduire une réunion efficace?", "Objectif, ordre du jour, temps de parole, décisions et compte rendu."),
        (213, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi évaluer une action éducative?", "Pour vérifier ses effets et décider des ajustements."),
        (214, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Définissez partenariat éducatif.", "Coopération organisée entre acteurs autour d’objectifs éducatifs."),
        (215, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Comment favoriser l’intégration d’un nouvel élève?", "Accueil, repères, tutorat éventuel et activités de coopération."),
        (216, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi enseigner les règles de vie collective?", "Pour développer responsabilité, respect et autonomie sociale."),
        (217, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Définissez médiation.", "Processus visant à aider des parties à résoudre un différend avec un tiers impartial."),
        (218, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi prévenir plutôt que sanctionner systématiquement?", "La prévention agit sur les causes et construit des comportements durables."),
        (219, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Comment réagir à une violence en classe?", "Sécuriser, séparer si nécessaire, alerter et appliquer les procédures."),
        (220, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi l’observation est-elle un outil professionnel?", "Elle fournit des faits pour adapter l’accompagnement."),
        (221, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Définissez conseil de classe.", "Instance de suivi collectif des élèves et de la vie scolaire selon les règles institutionnelles."),
        (222, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi valoriser les réussites?", "Pour renforcer engagement et perception des progrès."),
        (223, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Comment favoriser la coopération entre élèves?", "Rôles complémentaires, objectif commun et critères collectifs."),
        (224, "7. Sciences de l’éducation, inclusion et vie scolaire — 32 exercices", "Pourquoi faire un bilan après une activité?", "Pour identifier acquis, difficultés et améliorations à apporter."),

        (225, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez service public.", "Activité répondant à un besoin d’intérêt général selon un cadre juridique."),
        (226, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi l’école joue-t-elle un rôle civique?", "Elle transmet connaissances, règles communes et capacités de participation."),
        (227, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Citez deux exemples de responsabilités civiques adaptées à la vie scolaire.", "Participation à la vie collective avec droits et responsabilités."),
        (228, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi respecter les différences?", "Pour garantir dignité, égalité et inclusion."),
        (229, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Quelle méthode permet de distinguer une information vérifiée d’une affirmation non étayée?", "Analyse raisonnée des sources, preuves et arguments."),
        (230, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Comment vérifier une information numérique?", "Examiner auteur, date, source, preuves et recoupements."),
        (231, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi protéger les données personnelles des enfants?", "Pour préserver leur vie privée et leur sécurité."),
        (232, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi une école devrait-elle intégrer des pratiques de consommation responsables?", "Articulation des dimensions économique, sociale et environnementale dans le temps."),
        (233, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi l’assainissement est-il une question éducative?", "Il réduit les risques sanitaires et améliore les conditions d’apprentissage."),
        (234, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez prévention sanitaire.", "Actions visant à réduire la probabilité ou la gravité de problèmes de santé."),
        (235, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi l’éducation nutritionnelle est-elle importante?", "Elle aide à développer des habitudes favorables à la santé."),
        (236, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Qu’est-ce qu’une alimentation diversifiée?", "Alimentation comprenant une variété d’aliments couvrant différents besoins nutritionnels."),
        (237, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi lutter contre la stigmatisation?", "Elle peut exclure et empêcher la demande d’aide."),
        (238, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez égalité des chances.", "Principe visant à réduire les obstacles injustifiés à l’accès et à la réussite."),
        (239, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi l’accès à l’éducation est-il un enjeu collectif?", "Il influence compétences, participation sociale et développement."),
        (240, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez bénévolat.", "Activité réalisée volontairement sans rémunération dans un cadre organisé ou non."),
        (241, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi l’engagement communautaire peut-il soutenir une école?", "Il peut mobiliser ressources, compétences et soutien local."),
        (242, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez média.", "Moyen de diffusion d’informations ou de contenus à un public."),
        (243, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi distinguer fait et opinion?", "Pour éviter de présenter une interprétation comme une information établie."),
        (244, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Qu’est-ce qu’une source officielle?", "Information publiée par une institution ou organisme compétent."),
        (245, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi la date d’une information est-elle importante?", "Le contexte et les données peuvent évoluer."),
        (246, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez rumeur.", "Information non vérifiée qui circule entre personnes ou médias."),
        (247, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi la rumeur peut-elle nuire à l’école?", "Elle peut provoquer confusion, peur ou atteinte à la réputation."),
        (248, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez solidarité.", "Disposition à soutenir les autres et à agir pour le bien collectif."),
        (249, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi l’éducation à l’environnement commence-t-elle à l’école?", "Elle permet de comprendre les ressources, risques et comportements responsables."),
        (250, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez risque.", "Combinaison de probabilité d’un événement et de conséquences potentielles."),
        (251, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi préparer un plan d’urgence scolaire?", "Pour organiser les réactions face à des situations dangereuses."),
        (252, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez premiers secours.", "Gestes immédiats destinés à protéger et aider avant la prise en charge spécialisée."),
        (253, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi signaler une situation dangereuse?", "Pour permettre une intervention et prévenir d’autres incidents."),
        (254, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Définissez santé mentale.", "État de bien-être permettant notamment de faire face aux contraintes et de fonctionner dans la vie quotidienne."),
        (255, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Pourquoi créer un climat d’écoute?", "Pour faciliter l’expression des difficultés et l’orientation vers une aide appropriée."),
        (256, "8. Culture générale, citoyenneté et santé scolaire — 32 exercices", "Quel rôle l’enseignant peut-il jouer en matière de santé?", "Observer, prévenir, transmettre des informations adaptées et orienter sans se substituer aux professionnels de santé."),

        (257, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment lire un sujet de concours efficacement?", "Identifier consigne, verbes d’action, limites du sujet et critères implicites."),
        (258, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi analyser les mots-clés avant de répondre?", "Ils déterminent précisément ce qui est demandé."),
        (259, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment gérer une épreuve chronométrée?", "Répartir le temps, commencer par les tâches maîtrisées et réserver une relecture."),
        (260, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Que faire devant une question inconnue?", "Raisonner à partir des notions connues, ne pas inventer et revenir dessus si le temps le permet."),
        (261, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi relire une copie?", "Pour corriger fautes, oublis, unités et incohérences."),
        (262, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment construire un plan de dissertation?", "Définir le sujet, poser une problématique puis organiser des idées complémentaires."),
        (263, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi illustrer une réponse?", "Un exemple concret rend le raisonnement vérifiable et compréhensible."),
        (264, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment préparer un oral de motivation?", "Relier parcours, qualités, expérience et projet à la formation visée."),
        (265, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Que faire si le jury demande une précision?", "Répondre directement puis justifier avec un exemple."),
        (266, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment réagir à une question déstabilisante?", "Prendre quelques secondes, reformuler mentalement et répondre avec calme."),
        (267, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi éviter les réponses récitées?", "Une compréhension réelle permet d’adapter la réponse à la question."),
        (268, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment organiser une semaine de révision?", "Répartir matières, exercices, corrections, rappels et repos."),
        (269, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi tenir un cahier d’erreurs?", "Pour transformer les erreurs en objectifs de révision."),
        (270, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment analyser une mauvaise note?", "Identifier si la cause relève des connaissances, de la méthode, du temps ou de l’attention."),
        (271, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi faire des simulations?", "Pour entraîner connaissances, gestion du temps et comportement d’épreuve."),
        (272, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment préparer le matériel la veille?", "Vérifier convocation, pièce nécessaire, instruments autorisés et trajet."),
        (273, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi arriver en avance?", "Pour réduire les imprévus et commencer dans de bonnes conditions."),
        (274, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment répondre à une mise en situation professionnelle?", "Identifier problème, règles, priorités, action et suivi."),
        (275, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Un parent conteste une décision : démarche?", "Écouter, rester factuel, expliquer les critères et rappeler la procédure."),
        (276, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Un élève refuse une activité : que rechercher?", "Cause possible, compréhension de la consigne, difficulté, émotion ou besoin particulier."),
        (277, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Deux élèves se disputent : première priorité?", "Garantir la sécurité et interrompre l’escalade."),
        (278, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment traiter une information confidentielle?", "La conserver de manière sécurisée et la transmettre uniquement selon les règles."),
        (279, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi la ponctualité est-elle importante?", "Elle participe à la fiabilité du service et à la continuité pédagogique."),
        (280, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment préparer une présentation de trois minutes?", "Une introduction courte, deux ou trois idées structurées et une conclusion."),
        (281, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi contrôler sa voix à l’oral?", "Pour améliorer intelligibilité, rythme et confiance perçue."),
        (282, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment répondre « pourquoi le CREM? »?", "Relier motivation pour l’enseignement, service éducatif et projet professionnel."),
        (283, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Que faire si une consigne écrite semble contradictoire?", "Relire l’ensemble et demander une clarification selon les règles de l’épreuve."),
        (284, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment utiliser les 30 dernières minutes d’une épreuve?", "Finir les réponses essentielles puis vérifier structure, calculs et corrections."),
        (285, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi écrire lisiblement?", "Une copie lisible facilite l’évaluation du contenu."),
        (286, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment éviter la dispersion pendant les révisions?", "Définir un objectif par séance et limiter les distractions."),
        (287, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Pourquoi alterner connaissances et exercices?", "Les rappels construisent la base; les exercices vérifient la mobilisation."),
        (288, "9. Méthodologie du concours, français pratique et situations professionnelles — 32 exercices", "Comment établir une priorité de révision?", "Combiner importance de la notion, fréquence d’erreur et temps disponible."),

        (289, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Définissez une réunion pédagogique.", "Temps de travail collectif consacré à la préparation, au suivi ou à l’amélioration des pratiques."),
        (290, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi préparer un ordre du jour?", "Pour cadrer les objectifs, organiser le temps et faciliter les décisions."),
        (291, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Qu’est-ce qu’un compte rendu?", "Document synthétisant les échanges, décisions et actions à suivre."),
        (292, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi conserver des traces pédagogiques?", "Pour assurer le suivi et faciliter la continuité du travail."),
        (293, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Quelles qualités caractérisent une posture professionnelle de l’enseignant?", "Obligation d’exercer sa mission conformément aux règles et aux objectifs du service."),
        (294, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi respecter la confidentialité des dossiers scolaires?", "Pour protéger la vie privée des élèves."),
        (295, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment communiquer une difficulté scolaire à une famille?", "Présenter des faits observables, expliquer les besoins et proposer des pistes de collaboration."),
        (296, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi éviter les jugements personnels dans un rapport?", "Pour rester factuel, professionnel et vérifiable."),
        (297, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Qu’est-ce qu’un projet pédagogique?", "Ensemble organisé d’actions visant des objectifs éducatifs définis."),
        (298, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi fixer des indicateurs pour un projet?", "Pour pouvoir suivre les progrès et apprécier les résultats."),
        (299, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Définissez partenariat école-famille.", "Coopération entre l’établissement et les familles autour de la réussite et du bien-être de l’enfant."),
        (300, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment préparer un entretien avec un parent?", "Rassembler les faits, définir l’objectif et prévoir des propositions concrètes."),
        (301, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi écouter avant de répondre à une plainte?", "Pour comprendre précisément le problème et éviter une réponse fondée sur une supposition."),
        (302, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment gérer une information contradictoire?", "Vérifier les sources, distinguer faits et interprétations puis documenter la situation."),
        (303, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi travailler en équipe éducative?", "Pour croiser les compétences et coordonner les interventions."),
        (304, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Qu’est-ce qu’un conseil pédagogique?", "Cadre collectif de réflexion sur les pratiques et les apprentissages."),
        (305, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi analyser les résultats d’une classe?", "Pour repérer les acquis, difficultés et priorités de remédiation."),
        (306, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment utiliser un tableau de suivi?", "En renseignant des indicateurs simples, réguliers et pertinents."),
        (307, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi éviter la surcharge administrative?", "Pour préserver le temps consacré aux apprentissages et à l’accompagnement."),
        (308, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Définissez leadership pédagogique.", "Capacité à mobiliser une équipe autour de l’amélioration des apprentissages."),
        (309, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi partager les bonnes pratiques?", "Pour mutualiser les solutions et améliorer collectivement les pratiques."),
        (310, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment organiser une activité extrascolaire éducative?", "Définir objectif, public, encadrement, ressources, sécurité et évaluation."),
        (311, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi prévoir les risques d’une sortie scolaire?", "Pour réduire les incidents et organiser les réponses nécessaires."),
        (312, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Que doit contenir une fiche d’activité?", "Objectif, public, durée, matériel, étapes, consignes et critères de réussite."),
        (313, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi évaluer une activité après sa réalisation?", "Pour identifier ce qui a fonctionné et ce qui doit être amélioré."),
        (314, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment gérer un retard répété d’un élève?", "Observer les causes, dialoguer et appliquer les règles de suivi de l’établissement."),
        (315, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi la ponctualité de l’enseignant compte-t-elle?", "Elle contribue à la régularité et au modèle professionnel donné aux élèves."),
        (316, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment préparer une séance en cas d’absence de matériel numérique?", "Prévoir une activité équivalente hors ligne."),
        (317, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi avoir un plan de secours pédagogique?", "Pour maintenir l’apprentissage malgré un imprévu."),
        (318, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment accueillir un nouvel enseignant dans une équipe?", "Présenter fonctionnement, ressources, règles, interlocuteurs et pratiques essentielles."),
        (319, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Pourquoi la formation continue est-elle utile?", "Elle permet d’actualiser connaissances, méthodes et compétences professionnelles."),
        (320, "10. Organisation de l’école, administration et profession enseignante — 32 exercices", "Comment fixer un objectif de développement professionnel?", "Le rendre précis, mesurable, réaliste et associé à une échéance.")
    ]

    exercises = [{"id": q[0], "section": q[1], "question": f"Exercice {q[0]}. {q[2]}", "answer": f"Correction : {q[3]}"} for q in q_data]

    sims = [
        {"title": "Concours blanc 1 — Pédagogie et français", "items": [
            {"num": 1, "text": "Construisez une situation-problème de collège et trois critères de réussite."},
            {"num": 2, "text": "Expliquez le rôle de l’évaluation formative."},
            {"num": 3, "text": "Corrigez : « Les notions que les élèves ont étudié sont importantes. »"},
            {"num": 4, "text": "Formulez une problématique sur école et citoyenneté."},
            {"num": 5, "text": "Proposez un plan en deux parties."}
        ]},
        {"title": "Concours blanc 2 — Sciences et géographie", "items": [
            {"num": 1, "text": "Expliquez deux effets de l’urbanisation rapide."},
            {"num": 2, "text": "Définissez désertification et deux mesures de prévention."},
            {"num": 3, "text": "Résolvez 4x−9=27."},
            {"num": 4, "text": "26 admis sur 40 : calculez le taux."},
            {"num": 5, "text": "Expliquez le rôle des globules rouges."}
        ]},
        {"title": "Concours blanc 3 — Éducation et numérique", "items": [
            {"num": 1, "text": "Expliquez inclusion et équité."},
            {"num": 2, "text": "Proposez trois actions contre le décrochage."},
            {"num": 3, "text": "Définissez fracture numérique."},
            {"num": 4, "text": "Donnez quatre critères de vérification d’une information."},
            {"num": 5, "text": "Expliquez le phishing et sa prévention."}
        ]},
        {"title": "Concours blanc 4 — Oral et situations professionnelles", "items": [
            {"num": 1, "text": "Présentez votre motivation en deux minutes."},
            {"num": 2, "text": "Un parent conteste une note : quelle démarche?"},
            {"num": 3, "text": "Un élève perturbe la classe : quelle intervention?"},
            {"num": 4, "text": "Comment analyser une simulation?"},
            {"num": 5, "text": "Construisez une semaine de révision."}
        ]}
    ]

    plan = [
        {"period": "Jours 1–3", "task": "pédagogie, didactique et objectifs."},
        {"period": "Jours 4–6", "task": "français, expression et communication."},
        {"period": "Jours 7–9", "task": "mathématiques et raisonnement."},
        {"period": "Jours 10–12", "task": "sciences, santé et environnement."},
        {"period": "Jours 13–15", "task": "histoire, géographie et culture générale."},
        {"period": "Jours 16–18", "task": "psychologie de l'enfant et développement."},
        {"period": "Jours 19–21", "task": "inclusion, vie scolaire et situations éducatives."},
        {"period": "Jours 22–23", "task": "citoyenneté, santé scolaire et esprit critique."},
        {"period": "Jours 24–25", "task": "organisation scolaire, méthodologie et oral."},
        {"period": "Jour 26", "task": "concours blanc 1 + correction."},
        {"period": "Jour 27", "task": "concours blanc 2 + correction."},
        {"period": "Jour 28", "task": "concours blanc 3 + correction."},
        {"period": "Jour 29", "task": "concours blanc 4 + correction."},
        {"period": "Jour 30", "task": "carnet d’erreurs, consolidation et préparation pratique."}
    ]

    return {
        "id": "annale-crem-sn",
        "title": "ANNALES CONCOURS AU SÉNÉGAL",
        "subtitle": "CREM — FASCICULE COMPLET DE PRÉPARATION",
        "total_exercises": 320,
        "headerText": "Anales Concours au Sénégal — CREM",
        "footerFormat": "{headerText} Page {pageNum}",
        "intro": "320 exercices distincts • corrections • 4 concours blancs • plan 30 jours\n\nVersion reconstruite de zéro : contenu renforcé, 10 domaines et contrôle automatique des 320 énoncés principaux pour éliminer les doublons.",
        "summary_sections": sections,
        "exercises": exercises,
        "exam_simulations": sims,
        "study_plan": plan,
        "quality_control": "Contrôle qualité : 320 exercices principaux / 320 énoncés uniques vérifiés automatiquement. Les 4 concours blancs sont complémentaires."
    }
